// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

@CodeSpec('text.SbpMessages', source: ['content', 'SEER', 'SAEV'])
@DocSpec([
  DocRef('content', 'supplies the message key, its base copy and its role'),
  DocRef('SEER', 'supplies the element label and hint resources these keys realise'),
  DocRef('SAEV', 'supplies the action label resources these keys realise'),
])
class SbpMessages {
  /// Page title of the order work list (SCR-01).
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
  ])
  @CsText(baseCopy: 'Orders')
  static const CsMessageKey screenOrdersTitle =
      CsMessageKey('screen.orders.title');

  /// Label of the state selector on the work list filter bar.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
    DocRef('SEER', 'supplies the element label resource this key realises'),
  ])
  @CsText(baseCopy: 'State')
  static const CsMessageKey screenOrdersFilterState =
      CsMessageKey('screen.orders.filter.state');

  /// Helper text of the state selector.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
    DocRef('SEER', 'supplies the element hint resource this key realises'),
  ])
  @CsText(baseCopy: 'Show only orders in the selected lifecycle state')
  static const CsMessageKey screenOrdersFilterStateHint =
      CsMessageKey('screen.orders.filter.state.hint');

  /// Row action that navigates from the work list to order detail.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
    DocRef('SAEV', 'supplies the action label resource this key realises'),
  ])
  @CsText(baseCopy: 'Open')
  static const CsMessageKey screenOrdersActionOpen =
      CsMessageKey('screen.orders.action.open');

  /// Shown on the work list when the filtered queue is empty, and as the status column's empty-data copy.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
  ])
  @CsText(baseCopy: 'No orders match the selected state filter')
  static const CsMessageKey screenOrdersEmpty =
      CsMessageKey('screen.orders.empty');

  /// Recovery action offered on the empty work list.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
  ])
  @CsText(baseCopy: 'Clear filter')
  static const CsMessageKey screenOrdersEmptyActionClear =
      CsMessageKey('screen.orders.empty.action.clear');

  /// Page title of order detail (SCR-02).
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
  ])
  @CsText(baseCopy: 'Order {orderId}')
  static const CsMessageKey screenOrderTitle =
      CsMessageKey('screen.order.title');

  /// Submit action on an order line.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
    DocRef('SAEV', 'supplies the action label resource this key realises'),
  ])
  @CsText(baseCopy: 'Amend line')
  static const CsMessageKey screenOrderActionAmend =
      CsMessageKey('screen.order.action.amend');

  /// Header action that releases a credit or stock hold.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
    DocRef('SAEV', 'supplies the action label resource this key realises'),
  ])
  @CsText(baseCopy: 'Release hold')
  static const CsMessageKey screenOrderActionRelease =
      CsMessageKey('screen.order.action.release');

  /// Shown on order detail when a line amendment fails validation or reservation.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
  ])
  @CsText(baseCopy: 'The amendment could not be applied')
  static const CsMessageKey screenOrderAmendError =
      CsMessageKey('screen.order.amend.error');

  /// Recovery action offered after a rejected amendment.
  @DocSpec([
    DocRef('content', 'supplies the message key, its base copy and its role'),
  ])
  @CsText(baseCopy: 'Retry')
  static const CsMessageKey screenOrderAmendActionRetry =
      CsMessageKey('screen.order.amend.action.retry');
}
