// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: the sample Solution Blueprint (D00)
// Spec model version: 1.1

import 'package:tom_code_specs/tom_code_specs.dart';

/// A person or organisation that places orders.
///
/// A party that places orders.
@CodeSpec(
  'dataAccess.Customer',
  source: ['DAENT-IDEN', 'content', 'DAATT-IDEN', 'DAATT-DATA'],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'supplies the entity, its table and its storage placement'),
  DocRef('content', 'supplies the entity narrative'),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
])
@CsTable('customers')
class Customer {
  /// The address order confirmations are sent to.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'email', columnType: 'VARCHAR')
  late String email;

  /// The name the customer trades under.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'display_name', columnType: 'VARCHAR')
  late String displayName;
}
