// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: the sample Solution Blueprint (D00)
// Spec model version: 1.1

import 'package:tom_code_specs/tom_code_specs.dart';

/// A single order placed by a customer.
///
/// One accepted customer order.
@CodeSpec(
  'dataAccess.Order',
  source: ['DAENT-IDEN', 'content', 'DAATT-IDEN', 'DAATT-DATA'],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'supplies the entity, its table and its storage placement'),
  DocRef('content', 'supplies the entity narrative'),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
])
@CsTable('orders')
class Order {
  /// The moment the order was accepted.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'placed_at', columnType: 'TIMESTAMP')
  late DateTime placedAt;
}
