// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// Applies a quantity change to one order line before dispatch, re-pricing and re-reserving only the affected line under optimistic concurrency.
@CodeSpec('serverApi.AmendOrderLineRequest', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the request shape, each member it carries and the rule set '
    'constraining the new quantity',
  ),
])
class AmendOrderLineRequest {
  /// The order the amended line belongs to.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late String orderId;

  /// The line whose quantity changes.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late String lineId;

  /// The new ordered quantity; must satisfy the quantity-positive constraint on OrderLine.quantity.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and the rule set '
      'constraining it',
    ),
  ])
  @CsValidation(rules: 'required, min:1')
  late int newQuantity;

  /// The order version the clerk read; a stale version is rejected with ORDER_VERSION_CONFLICT.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late int orderVersion;

  /// The clerk's justification note, when one was entered.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  String? justification;
}
