// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// Applies a quantity change to one order line before dispatch, re-pricing and re-reserving only the affected line under optimistic concurrency.
@CodeSpec('serverApi.AmendOrderLineResponse', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the response shape and each member it carries',
  ),
])
class AmendOrderLineResponse {
  /// The fresh price snapshot applied to the amended line.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late double unitPrice;

  /// Whether stock was re-reserved for the amended line.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late bool reserved;

  /// The order state after the amendment (Confirmed when fully satisfied); a value of the OrderStatus domain enum.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late String orderStatus;

  /// The order version after the amendment, for the next optimistic write.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late int orderVersion;
}
