// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

import 'order_dto.dart';

/// Returns one state-filtered page of the order work list in queue order.
@CodeSpec('serverApi.FetchOrderWorkListResponse', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the response shape and each member it carries',
  ),
])
class FetchOrderWorkListResponse {
  /// The page of matching orders in queue order.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its multiplicity and the Order data entity '
      'it is typed by',
    ),
  ])
  late List<OrderDto> orders;

  /// Total matching orders across all pages.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  late int totalCount;
}
