// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// Returns one state-filtered page of the order work list in queue order.
@CodeSpec('serverApi.FetchOrderWorkListRequest', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the request shape and each member it carries',
  ),
])
class FetchOrderWorkListRequest {
  /// Show only orders in this lifecycle state; absent means every open state.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and the OrderStatus domain '
      'enum it selects from',
    ),
  ])
  String? stateFilter;

  /// Zero-based page index; defaults to the first page.
  @DocSpec([
    DocRef(
      'content',
      'supplies the member type, its requiredness and its description',
    ),
  ])
  int? page;
}
