// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// The application's own operation surface. Both operations return the shared
/// Result envelope; the client-side handling of each call is stated on the
/// interaction step that cites the operation.
@CodeSpec('serverApi.SbpOperations', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the operation registry and the name of each operation it lists',
  ),
])
class SbpOperations {
  /// Applies a quantity change to one order line before dispatch, re-pricing and re-reserving only the affected line under optimistic concurrency.
  @DocSpec([
    DocRef('content', 'supplies the operation name'),
  ])
  @CsEndpoint('amendOrderLine')
  static const CsOperationRef amendOrderLine = CsOperationRef('amendOrderLine');

  /// Returns one state-filtered page of the order work list in queue order.
  @DocSpec([
    DocRef('content', 'supplies the operation name'),
  ])
  @CsEndpoint('fetchOrderWorkList')
  static const CsOperationRef fetchOrderWorkList =
      CsOperationRef('fetchOrderWorkList');
}
