// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

import '../domain_enum/order_channel.dart';
import '../domain_enum/order_status.dart';

/// A customer order captured from EDI or REST and driven through the lifecycle. Realizes FR-01, FR-04, FR-05, FR-06.
@CodeSpec(
  'serverApi.OrderDto',
  source: ['DAENT-IDEN', 'DAATT-IDEN', 'DAATT-DATA', 'DAATT-DTEN'],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'supplies the entity this wire DTO is the row shape of'),
  DocRef('DAATT-IDEN', 'supplies the attributes the DTO mirrors as members'),
  DocRef('DAATT-DATA', 'supplies each member’s value type'),
  DocRef(
    'DAATT-DTEN',
    'names the domain enums that type the enumeration-kind members',
  ),
])
class OrderDto {
  /// Stable order identifier.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the attribute this member mirrors'),
    DocRef('DAATT-DATA', 'supplies the value type'),
  ])
  late String orderId;

  /// Reference to the ordering customer.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the attribute this member mirrors'),
    DocRef('DAATT-DATA', 'supplies the value type'),
  ])
  late String customerId;

  /// Capture channel: EDI or REST.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the attribute this member mirrors'),
    DocRef('DAATT-DATA', 'supplies the value type'),
    DocRef(
      'DAATT-DTEN',
      'names the domain enum (OrderChannel) that types this member',
    ),
  ])
  late OrderChannel channel;

  /// Lifecycle state (Captured..Closed, with Hold).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the attribute this member mirrors'),
    DocRef('DAATT-DATA', 'supplies the value type'),
    DocRef(
      'DAATT-DTEN',
      'names the domain enum (OrderStatus) that types this member',
    ),
  ])
  late OrderStatus status;

  /// Capture timestamp (UTC).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the attribute this member mirrors'),
    DocRef('DAATT-DATA', 'supplies the value type'),
  ])
  late DateTime createdAt;
}
