// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// A wholesale or e-commerce customer that places orders. Realizes FR-01.
@CodeSpec(
  'dataAccess.Customer',
  source: ['DAENT-IDEN', 'DAATT-IDEN', 'DAATT-DATA', 'DAATT-SECU'],
)
@DocSpec([
  DocRef(
    'DAENT-IDEN',
    'supplies the entity, its table and its storage placement',
  ),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
  DocRef(
    'DAATT-SECU',
    'records the sensitivity level and PII marking of the stored attributes',
  ),
])
@CsTable('mom_customer')
class Customer {
  /// Stable customer identifier.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    column: 'customer_id',
    columnType: 'uuid',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late String customerId;

  /// Customer legal name (PII).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    columnType: 'varchar(200)',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late String name;

  /// Approved credit limit used by validation.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    column: 'credit_limit',
    columnType: 'numeric(14,2)',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late double creditLimit;
}
