// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';
import 'package:tom_core_server/tom_core_server.dart';

import 'order_line.dart';

@CodeSpec('dataAccess.OrderLineRepository', source: ['DAENT-IDEN'])
@DocSpec([
  DocRef('DAENT-IDEN', 'supplies the entity and key this repository reads'),
])
@CsRepository()
abstract class OrderLineRepository extends TomRepository<OrderLine, String> {}
