// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// A customer order captured from EDI or REST and driven through the lifecycle. Realizes FR-01, FR-04, FR-05, FR-06.
@CodeSpec(
  'dataAccess.Order',
  source: [
    'DAENT-IDEN',
    'DAATT-IDEN',
    'DAATT-DATA',
    'DAATT-SECU',
    'ENRLE-IDEN',
    'ENRLE-CARD',
    'ENRLE-NAVI',
    'ENRLE-SOUR-REF',
    'ENRLE-TARG-REF',
  ],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'supplies the entity, its table and its storage placement'),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
  DocRef('DAATT-SECU', 'records the sensitivity level and PII marking of the stored attributes'),
  DocRef('ENRLE-IDEN', 'records the relationships this entity participates in'),
  DocRef('ENRLE-CARD', 'records the cardinalities of those relationships'),
  DocRef('ENRLE-NAVI', 'records their navigability and foreign-key location'),
  DocRef('ENRLE-SOUR-REF', 'records the source entity of each relationship'),
  DocRef('ENRLE-TARG-REF', 'records the target entity of each relationship'),
])
@CsTable('mom_order')
class Order {
  /// Stable order identifier.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'order_id', columnType: 'uuid')
  late String orderId;

  /// Reference to the ordering customer.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'customer_id', columnType: 'uuid')
  late String customerId;

  /// Capture channel: EDI or REST.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(columnType: 'varchar(8)')
  late String channel;

  /// Lifecycle state (Captured..Closed, with Hold).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(columnType: 'varchar(16)')
  late String status;

  /// Capture timestamp (UTC).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'created_at', columnType: 'timestamptz')
  late DateTime createdAt;
}
