// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:meridian_codespec_shared/meridian_codespec_shared.dart';
import 'package:tom_code_specs/tom_code_specs.dart';

import '../domain_enum/order_channel.dart';

/// A customer order captured from EDI or REST and driven through the lifecycle. Realizes FR-01, FR-04, FR-05, FR-06.
@CodeSpec(
  'dataAccess.Order',
  source: [
    'DAENT-IDEN',
    'DAATT-IDEN',
    'DAATT-DATA',
    'DAATT-DTEN',
    'DAATT-SECU',
    'ENRLE-IDEN',
    'ENRLE-CARD',
    'ENRLE-NAVI',
    'ENRLE-SOUR-REF',
    'ENRLE-TARG-REF',
  ],
)
@DocSpec([
  DocRef(
    'DAENT-IDEN',
    'supplies the entity, its table and its storage placement',
  ),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
  DocRef(
    'DAATT-DTEN',
    'names the domain enum that types the enumeration-kind columns',
  ),
  DocRef(
    'DAATT-SECU',
    'records the sensitivity level and PII marking of the stored attributes',
  ),
  DocRef('ENRLE-IDEN', 'records the relationships this entity participates in'),
  DocRef('ENRLE-CARD', 'records the cardinalities of those relationships'),
  DocRef('ENRLE-NAVI', 'records their navigability and foreign-key location'),
  DocRef('ENRLE-SOUR-REF', 'records the source entity of each relationship'),
  DocRef('ENRLE-TARG-REF', 'records the target entity of each relationship'),
])
@CsTable('mom_order')
class Order {
  /// Stable order identifier.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    column: 'order_id',
    columnType: 'uuid',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late String orderId;

  /// Reference to the ordering customer.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    column: 'customer_id',
    columnType: 'uuid',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late String customerId;

  /// Capture channel: EDI or REST.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-DTEN',
      'names the domain enum (OrderChannel) that types this column',
    ),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    columnType: 'varchar(8)',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late OrderChannel channel;

  /// Lifecycle state (Captured..Closed, with Hold).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-DTEN',
      'names the domain enum (OrderStatus) that types this column',
    ),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    columnType: 'varchar(16)',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late OrderStatus status;

  /// Capture timestamp (UTC).
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    column: 'created_at',
    columnType: 'timestamptz',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late DateTime createdAt;
}
