// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// A sellable product referenced by order lines and priced by the price list. Realizes FR-02, FR-03.
@CodeSpec(
  'dataAccess.Product',
  source: ['DAENT-IDEN', 'DAATT-IDEN', 'DAATT-DATA', 'DAATT-SECU'],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'supplies the entity, its table and its storage placement'),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
  DocRef('DAATT-SECU', 'records the sensitivity level and PII marking of the stored attributes'),
])
@CsTable('mom_product')
class Product {
  /// Stable product identifier.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'product_id', columnType: 'uuid')
  late String productId;

  /// Stock-keeping unit.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(columnType: 'varchar(40)')
  late String sku;

  /// Product display name.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(columnType: 'varchar(200)')
  late String name;
}
