// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// A sellable product referenced by order lines and priced by the price list. Realizes FR-02, FR-03.
@CodeSpec(
  'dataAccess.Product',
  source: ['DAENT-IDEN', 'DAATT-IDEN', 'DAATT-DATA', 'DAATT-SECU', 'content'],
)
@DocSpec([
  DocRef(
    'DAENT-IDEN',
    'supplies the entity, its table and its storage placement',
  ),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
  DocRef(
    'DAATT-SECU',
    'records the sensitivity level and PII marking of the stored attributes',
  ),
  DocRef('content', 'supplies the rule set and its arguments'),
])
@CsTable('mom_product')
class Product {
  /// Stable product identifier.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    column: 'product_id',
    columnType: 'uuid',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late String productId;

  /// Stock-keeping unit.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
    DocRef('content', 'supplies the rule set and its arguments'),
  ])
  @CsColumn(
    columnType: 'varchar(40)',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  @CsValidation(rules: r'required, pattern:^[A-Z0-9]{4}-[A-Z0-9]{4}$')
  late String sku;

  /// Product display name.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
    DocRef(
      'DAATT-SECU',
      'records the sensitivity level and PII marking of the stored attributes',
    ),
  ])
  @CsColumn(
    columnType: 'varchar(200)',
    sensitivityLevel: CsSensitivityLevel.internal,
    isPii: false,
  )
  late String name;
}
