// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

import '../data_access/customer.dart';

@CodeSpec('serviceUnit.CustomerService', source: ['DAENT-CLAS'])
@DocSpec([
  DocRef('DAENT-CLAS', 'supplies the bounded context and aggregate root'),
])
@CsServiceUnit(rootAggregate: Customer, boundedContext: 'Customer')
abstract class CustomerService {}
