// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';
import 'package:tom_core_server/tom_core_server.dart';

import '../data_access/order.dart';

@CodeSpec(
  'serviceUnit.OrderService',
  source: ['DAENT-CLAS', 'INID', 'SCID', 'EXTEN-RESU'],
)
@DocSpec([
  DocRef('DAENT-CLAS', 'supplies the bounded context and aggregate root'),
  DocRef('INID', 'records the use cases this service unit realises'),
  DocRef('SCID', 'records the key scenarios exercising this service unit'),
  DocRef('EXTEN-RESU', 'records the resume step of the amend extension flow'),
])
@tomService
@CsServiceUnit(rootAggregate: Order, boundedContext: 'Ordering')
abstract class OrderService {}
