/// Tests for the Dart whole-model accessor emitter
/// (lib/src/som_dart_model_emitter.dart, SOM §10.3).
///
/// The library it emits is the answer to a defect: `toMarkdown` and
/// `validateDocument` both take a whole `SpecModel` and no facade exposed one,
/// so a consumer had to resolve the package's own directory layout by hand.
///
/// The payload is embedded rather than read back from the shipped
/// `meta/spec_model.meta.json` because `Isolate.resolvePackageUri` returns
/// `null` in an AOT binary — a file-reading accessor would read nothing and
/// say nothing. SME3 is the group that keeps the embedding honest: a literal
/// that does not survive escaping is a compile error at best and a silently
/// different model at worst.
library;

import 'dart:convert';

import 'package:test/test.dart';
import 'package:tom_specs_clitool/tom_specs_clitool.dart';

Map<String, dynamic> _meta() => {
  'metaSchemaVersion': 1,
  'modelVersion': 1,
  'modelVersionLabel': '1.1.0+test',
  'classCount': 1,
  'rootCount': 1,
  'containerRoot': 'DocSpecsProject',
  'roots': [
    {'type': 'Demo', 'title': 'Demo', 'sectionId': 'DEMO'},
  ],
  'classes': {
    'Demo': {
      'name': 'Demo',
      'sectionId': 'DEMO',
      'fields': [
        {'name': 'notes', 'kind': 'content', 'sectionId': 'NOTE'},
      ],
    },
  },
};

SomDartModelEmitter _emitter([Map<String, dynamic>? meta]) =>
    SomDartModelEmitter(meta ?? _meta(), packageName: 'tom_som_dart_v0');

void main() {
  group('SME1: the emitted library', () {
    test('declares the accessor and the payload constant', () {
      final src = _emitter().generateLibrary();
      expect(src, contains('SpecModel get somSpecModel'));
      expect(src, contains('const String somSpecModelJson ='));
    });

    test('is a generated-file banner plus a library directive', () {
      final src = _emitter().generateLibrary();
      expect(src, startsWith('// GENERATED by tom_specs_clitool'));
      expect(src, contains('do not edit by hand'));
      expect(src, contains('library;'));
    });

    test('imports the runtime that declares SpecModel', () {
      expect(
        _emitter().generateLibrary(),
        contains(
          "import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';",
        ),
      );
    });

    test('the accessor caches, so a second read does not re-parse', () {
      // The getter must be `??=` against a nullable field rather than a
      // top-level `final`: a `final` would parse at import time, which is the
      // cost the separate library exists to avoid.
      final src = _emitter().generateLibrary();
      expect(src, contains('_somSpecModel ??='));
      expect(src, contains('SpecModel? _somSpecModel;'));
    });

    test('the import shown in the doc comment is the one that works', () {
      // A consumer copies this line. It must name the model library, not the
      // facade — the facade does not export it, which is the whole point.
      expect(
        _emitter().generateLibrary(),
        contains(
          "/// import 'package:tom_som_dart_v0/tom_som_dart_v0_model.dart';",
        ),
      );
    });
  });

  group('SME2: the payload is the meta map, minified', () {
    test('round-trips to the same map', () {
      final meta = _meta();
      final decoded = jsonDecode(_emitter(meta).payload);
      expect(decoded, equals(meta));
    });

    test('carries no indentation — that is 4 MB of the real model', () {
      expect(_emitter().payload, isNot(contains('\n')));
    });
  });

  group('SME3: the string literal survives every hostile character', () {
    /// The body of the emitted `somSpecModelJson` literal, quotes stripped.
    String literalBody(String value) {
      final meta = _meta();
      (meta['classes'] as Map)['Demo']['doc'] = value;
      final src = _emitter(meta).generateLibrary();
      const open = "const String somSpecModelJson = '";
      return src.substring(
        src.indexOf(open) + open.length,
        src.lastIndexOf("';"),
      );
    }

    /// Every character in [body] that would end or reopen the literal while
    /// *not* preceded by a backslash — i.e. every reason it would not compile,
    /// or would compile to something other than what was encoded.
    ///
    /// Asserting this rather than round-tripping through the inverse escape is
    /// deliberate, and was arrived at the hard way: the inverse-escape version
    /// of this test **passed with the `\$` escape deleted from the emitter**,
    /// because a symmetric inverse skips exactly what the forward pass skipped.
    /// A test that cannot fail is worse than none.
    List<String> unescaped(String body) {
      final found = <String>[];
      for (var i = 0; i < body.length; i++) {
        if (body[i] == r'\') {
          i++; // the escape consumes the next character
          continue;
        }
        if (body[i] == "'" || body[i] == r'$') found.add('$i:${body[i]}');
      }
      return found;
    }

    test('a single quote is escaped — the payload has 2,908 of them', () {
      // This is why the literal cannot be a raw string.
      final body = literalBody("it's a section");
      expect(body, contains(r"\'"));
      expect(unescaped(body), isEmpty);
    });

    test('a dollar sign is escaped — otherwise it opens an interpolation', () {
      // The failure mode that is not always a compile error: `$id` in prose
      // interpolates if a matching name is in scope.
      final body = literalBody(r'costs $5 and $id');
      expect(body, contains(r'\$'));
      expect(unescaped(body), isEmpty);
    });

    test('a backslash is escaped before anything it could double', () {
      expect(unescaped(literalBody(r'a\b')), isEmpty);
    });

    test('a backslash immediately before a quote', () {
      // The ordering trap: escaping the quote first would leave `\\'`, which
      // ends the literal early.
      expect(unescaped(literalBody(r"a\'b")), isEmpty);
    });

    test('all three together, and a newline', () {
      expect(unescaped(literalBody('a\\b\'c\$d\ne')), isEmpty);
    });

    test('non-ASCII text needs no escaping and gets none', () {
      final body = literalBody('Ürsprung — naïve “quotes”');
      expect(unescaped(body), isEmpty);
      expect(body, contains('Ürsprung'));
    });

    test('the real payload shape: nothing unescaped anywhere in it', () {
      // The whole emitted literal, not just the one seeded value — a stray
      // quote in any other meta field would be just as fatal.
      expect(unescaped(literalBody(r"quote ' dollar $ slash \")), isEmpty);
    });
  });

  group('SME4: what the banner tells a reader', () {
    test('it states why the payload is embedded rather than read', () {
      // The reason is not obvious and the next reader will want to shrink the
      // file. Without this, embedding looks like an arbitrary choice.
      final src = _emitter().generateLibrary();
      expect(src, contains('resolvePackageUri'));
      expect(src, contains('AOT'));
    });

    test('the versionLabel reaches the banner', () {
      final src = SomDartModelEmitter(
        _meta(),
        packageName: 'tom_som_dart_v1',
        versionLabel: 'v1',
      ).generateLibrary();
      expect(src, contains('(v1)'));
    });
  });
}
