name: tom_specs_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  tom_core_kernel:
    path: ../../core/tom_core_kernel

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
