// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:meridian_codespec_shared/meridian_codespec_shared.dart';
import 'package:tom_code_specs/tom_code_specs.dart';

@CodeSpec('serverCall.AmendOrderLineCallCollaborator', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the step list this collaborator carries, the behaviour each '
    'step states and the condition the branch is taken under',
  ),
])
@CsCollaborator()
abstract class AmendOrderLineCallCollaborator {
  /// Puts the line id, the new quantity and the order version onto the amendment command.
  @DocSpec([
    DocRef('content', 'supplies the behaviour this step states'),
  ])
  Future<void> assembleRequestStageTheCoreFields(
    AmendOrderLineRequest request,
  );

  /// Only when the clerk entered a justification
  @DocSpec([
    DocRef('content', 'supplies the condition this branch is taken under'),
  ])
  Future<bool> assembleRequestAttachTheJustificationApplies(
    AmendOrderLineRequest request,
  );

  /// Adds the clerk's justification note to the command.
  @DocSpec([
    DocRef('content', 'supplies the behaviour this step states'),
  ])
  Future<void> assembleRequestAttachTheJustification(
    AmendOrderLineRequest request,
  );

  /// Applies the returned price snapshot and reservation state to the open line.
  @DocSpec([
    DocRef('content', 'supplies the behaviour this step states'),
  ])
  Future<void> handleResponseApplyThePriceSnapshot(
    AmendOrderLineResponse response,
  );

  /// Leaves the line at its stored quantity and shows screen.order.amend.error beside the field.
  @DocSpec([
    DocRef('content', 'supplies the behaviour this step states'),
  ])
  Future<void> handleErrorSurfaceTheRejection(ErrorResult error);
}
