// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:meridian_codespec_shared/meridian_codespec_shared.dart';
import 'package:tom_code_specs/tom_code_specs.dart';

import 'fetch_order_work_list_call_collaborator.dart';

/// Order shows state Confirmed with both lines priced and reserved.
@CodeSpec('serverCall.FetchOrderWorkListCall', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the step that issues this call, the operation it cites and '
    'the steps of each handling body',
  ),
])
@CsServerCall(SbpOperations.fetchOrderWorkList)
class FetchOrderWorkListCall {
  late final FetchOrderWorkListCallCollaborator collaborator;

  /// Order shows state Confirmed with both lines priced and reserved.
  @DocSpec([
    DocRef(
      'content',
      'supplies the behaviour text this fallback body throws',
    ),
  ])
  Future<void> assembleRequest(FetchOrderWorkListRequest request) {
    throw UnsupportedError(
      'Order shows state Confirmed with both lines priced and reserved.',
    );
  }

  /// Renders the returned page of work-list rows into the order table.
  @DocSpec([
    DocRef(
      'content',
      'supplies the steps of this body and the behaviour each step states',
    ),
  ])
  Future<void> handleResponse(FetchOrderWorkListResponse response) async {
    await collaborator.handleResponseRenderTheWorkListPage(response);
  }

  /// Order shows state Confirmed with both lines priced and reserved.
  @DocSpec([
    DocRef(
      'content',
      'supplies the behaviour text this fallback body throws',
    ),
  ])
  Future<void> handleError(ErrorResult error) {
    throw UnsupportedError(
      'Order shows state Confirmed with both lines priced and reserved.',
    );
  }
}
