// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: the sample Solution Blueprint (D00)
// Spec model version: 1.1

import 'package:tom_code_specs/tom_code_specs.dart';
import 'package:tom_core_server/tom_core_server.dart';

import '../data_access/customer.dart';

/// A person or organisation that places orders.
///
/// A party that places orders.
@CodeSpec(
  'services.CustomerService',
  source: ['DAENT-IDEN', 'DAENT-CLAS', 'content'],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'names the aggregate root this service unit owns'),
  DocRef('DAENT-CLAS', 'supplies the aggregate and the bounded context that caps it'),
  DocRef('content', 'supplies the entity narrative'),
])
@CsServiceUnit(rootAggregate: Customer, boundedContext: 'Ordering')
@tomService
abstract class CustomerService {
  static const List<Type> ownedEntities = [Customer];
}
