import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;

void main(List<String> args) {
  final inputPath = args.isNotEmpty ? args.first : 'assets/sdk_summary.sum';
  final outputDir = args.length > 1 ? args[1] : 'lib/src/sdk_summary';

  final bytes = File(inputPath).readAsBytesSync();
  final base64String = base64Encode(bytes);

  const chunkSize = 60000; // ~60 KB per chunk
  final chunks = <String>[];
  for (var i = 0; i < base64String.length; i += chunkSize) {
    final end = (i + chunkSize).clamp(0, base64String.length);
    chunks.add(base64String.substring(i, end));
  }

  final dir = Directory(outputDir);
  if (dir.existsSync()) dir.deleteSync(recursive: true);
  dir.createSync(recursive: true);

  final imports = StringBuffer();
  final list = StringBuffer();

  for (var i = 0; i < chunks.length; i++) {
    final index = (i + 1).toString().padLeft(3, '0');
    final fileName = 'chunk_$index.dart';
    final constName = 'sdkSummaryChunk$index';

    File(p.join(outputDir, fileName)).writeAsStringSync(
      '${_banner(fileName)}\n'
      '${_chunkDoc(i + 1, chunks.length)}'
      "const $constName =\n    '${chunks[i]}';\n",
    );

    imports.writeln("import '$fileName';");
    list.writeln('  $constName,');
  }

  File(p.join(outputDir, 'sdk_summary_chunks.dart')).writeAsStringSync(
    '${_banner('sdk_summary_chunks.dart')}\n'
    '$imports\n'
    '/// The base64 slices of the bundled SDK summary, in concatenation order.\n'
    '///\n'
    '/// Order is the whole contract: the slices are cut at fixed byte offsets\n'
    '/// with no regard for what falls where, so concatenating them in any other\n'
    '/// order yields a string that still decodes and then fails deep inside the\n'
    '/// analyzer with an error that names nothing about this list.\n'
    'const sdkSummaryChunks = [\n'
    '$list];\n',
  );

  print(
    'Split ${bytes.length} bytes (${base64String.length} base64 chars) '
    'into ${chunks.length} chunks in $outputDir',
  );
}

/// The generated-file banner every emitted file opens with.
///
/// Stated on the file itself rather than only in this tool, because the reader
/// who needs it is the one who has opened the file and is about to edit it.
String _banner(String fileName) => '''
// GENERATED by tool/split_sdk_summary.dart — do not edit by hand.
// $fileName
''';

/// The doc comment carried by one chunk constant.
///
/// [index] is 1-based to match the file name; [total] is the slice count, which
/// changes whenever the SDK summary is rebuilt.
String _chunkDoc(int index, int total) => '''
/// Base64 slice $index of $total of the bundled Dart SDK analyzer summary.
///
/// The summary is embedded in source rather than shipped as an asset so the
/// tool can build an `AnalysisDriver` with **no installed Dart SDK** — see
/// `createAnalysisDriver` in `lib/src/analyzer_bootstrap.dart`. It is split
/// because a single string literal of that size is slow to parse and hostile
/// to diff.
///
/// The slice carries no meaning on its own: it is cut at a fixed character
/// offset, not at any boundary of the encoded data, and is only ever
/// concatenated back in order by `sdkSummaryChunks`.
''';
