/// Consolidated DocSpecs parsing + validation (SOM §14): the embedded,
/// runtime-owned equivalent of the `tom_doc_scanner` + `tom_doc_specs` split,
/// redesigned as one coherent API. This is the reference implementation the
/// other eight language runtimes port; the Dart violation messages are the
/// golden reference — every port must produce the same `rule` / `sectionId` /
/// `line` triples.
///
/// Three capabilities, one module:
///
///  1. **Parse** — [DocSpecsDocument.parse] reads any DocSpecs `*.md`
///     *schema-free* into a generic section tree ([DocSpecsSection]): ids,
///     titles, heading levels, body text, source lines. Fenced code blocks
///     shield their lines from heading detection ([MarkdownFenceTracker], the
///     exact semantics of the [SpecDocumentMarkdown] codec).
///  2. **Validate** — [DocSpecsValidator.validate] checks a parsed document
///     against a [DocSpecsSchema] (a `*.docspecs-schema.yaml` as generated by
///     the schema generator , SOM §13) and returns a structured
///     [DocSpecsViolation] list. Validation **never fails fast** — the full
///     list is always produced; a document is valid iff the list is empty.
///  3. **Bind** — [bindDocSpecsMarkdown] maps the same markdown onto the SOM
///     metadata tree, delegating to [SpecDocumentMarkdown.parse] (SOM §11.7).
///
/// Supported schema features (the SOM §14 scope): section-types (`prefix`,
/// `pattern-check-id`, `subsection-types` with `min-count`/`max-count`,
/// `format`, `text-required`, `min-text-length`/`max-text-length`,
/// `description`), form-types (fields with `required` and `pattern-check`),
/// and the `document:` structure (top-level sections, `optional`).
/// `validation-prompt` values are carried as data. Anything else — generator
/// placeholders, database-schema sections, custom tags — is **ignored on
/// load** and named in [DocSpecsSchema.warnings]; nothing is silently
/// dropped.
library;

import 'package:yaml/yaml.dart';

import 'spec_document.dart';
import 'spec_document_markdown.dart';
import 'spec_model.dart';

/// The SOM §14 violation rule vocabulary — identical across all nine runtimes.
enum DocSpecsViolationRule {
  /// A heading's id resolves to no section-type, or to a type not allowed at
  /// its nesting position.
  unknownSection,

  /// A required section (document slot or `min-count >= 1` subsection) has no
  /// occurrence.
  missingRequiredSection,

  /// A section id fails its type's `pattern-check-id`.
  idPatternMismatch,

  /// A subsection occurs, but fewer times than its `min-count`.
  tooFewItems,

  /// A subsection occurs more times than its numeric `max-count`.
  tooManyItems,

  /// A `required` form field is absent (or empty) in a form-formatted section.
  missingRequiredField,

  /// A form field value fails its `pattern-check`.
  fieldPatternMismatch,

  /// A `text-required` section has no body text.
  textRequired,

  /// A section's body text length is outside `min-text-length` /
  /// `max-text-length`.
  textLengthOut,

  /// The document/root shape does not match — wrong root id vs `title-format`,
  /// or a non-form `format` section without the demanded fenced block.
  formatMismatch,

  /// A heading line without a parseable `<!--[SECTION-ID]-->` comment.
  malformedHeading,
}

/// One structured violation (SOM §14): the [rule], the offending [sectionId]
/// (when one exists), the bound runtime [path] (when resolvable), the 1-based
/// source [line], and a human-readable [message].
class DocSpecsViolation {
  /// [rule], [line] and [message] are required — they are the three every
  /// violation can always state, since even a heading too malformed to yield
  /// an id still occupies a source line.
  ///
  /// [sectionId] and [path] are optional because each may genuinely not
  /// exist: a `malformedHeading` has no id to name, and no violation raised
  /// by this validator resolves a runtime [path] at all (binding is a
  /// separate step — see [bindDocSpecsMarkdown]), so it is `null` throughout
  /// the current implementation and reserved for callers that fold binding
  /// results into the same list.
  DocSpecsViolation({
    required this.rule,
    required this.line,
    required this.message,
    this.sectionId,
    this.path,
  });

  /// Which rule was broken. This — not [message] — is the machine-readable
  /// verdict, and it is part of the cross-runtime contract: all nine
  /// languages must report the same rule for the same document, so a
  /// consumer that branches on the prose instead will diverge between ports.
  final DocSpecsViolationRule rule;

  /// The DocSpecs id of the offending section, or `null` when none is
  /// available (a malformed heading, or an empty document).
  ///
  /// For a cardinality or required-subsection finding this names the
  /// **parent** — the section whose child count is wrong — because the
  /// missing child has no id to point at.
  final String? sectionId;

  /// The bound SOM runtime path, when one is resolvable. Always `null` from
  /// [DocSpecsValidator.validate], which works schema-to-markdown and never
  /// consults a [SpecModel]; it exists so binding-tier findings can share
  /// this type.
  final String? path;

  /// The **1-based** source line, so it can be handed to an editor unchanged.
  ///
  /// It points at the *heading* of the section at fault rather than at the
  /// offending body line, with one exception: a `fieldPatternMismatch`
  /// points at the form field's own line when that line was seen.
  final int line;

  /// The human-readable explanation. Display text only — it is deliberately
  /// not stable API, and an authored `error-message` on the failing
  /// pattern-check replaces the generated wording when one exists.
  final String message;

  @override
  String toString() =>
      'line $line: ${rule.name}${sectionId != null ? ' [$sectionId]' : ''}'
      '${path != null ? ' ($path)' : ''} — $message';
}

// ---------------------------------------------------------------------------
// 1. Generic (schema-free) markdown parse
// ---------------------------------------------------------------------------

/// One section of a schema-free DocSpecs parse: its [id] (null for a
/// malformed heading), heading [title], markdown [level], 1-based heading
/// [line], accumulated [bodyLines] (each with its own source line =
/// [bodyStartLine] + index), and nested [children].
class DocSpecsSection {
  /// All four arguments are required, [id] included even though it is
  /// nullable: a heading always has a position and a title, and whether it
  /// carries an id is exactly the fact the parse has to record, so leaving it
  /// unstated is never right. [bodyLines] and [children] are filled in by
  /// [DocSpecsDocument.parse] as it walks past the heading.
  DocSpecsSection({
    required this.id,
    required this.title,
    required this.level,
    required this.line,
  });

  /// The `<!--[SECTION-ID]-->` machine identity, or `null` when the heading
  /// carried no such comment (SOM §11.2).
  ///
  /// `null` is not merely "unknown": it has already been reported as a
  /// [DocSpecsViolationRule.malformedHeading] by the parse, which is why the
  /// validator skips such a section silently instead of reporting it twice.
  final String? id;

  /// The heading text with the id comment stripped — the section's headline.
  /// Never `null`: a heading with only an id comment yields the empty string.
  ///
  /// Note that the id, not this, is the identity; the title is authored prose
  /// and no rule in this validator matches on it.
  final String title;

  /// The markdown heading depth (`#` = 1). **Uncapped** — SOM §11.2 makes
  /// depth 1 + section depth with no ceiling and requires DocSpecs tooling to
  /// accept `#{7,}`, so a reader must not assume the CommonMark limit of 6.
  ///
  /// Nesting is derived from this alone: the parse pops its stack until the
  /// top is shallower, so a skipped level nests rather than erroring.
  final int level;

  /// The **1-based** source line of the heading itself. Every violation
  /// raised against this section reports this line, so it is what an editor
  /// jumps to.
  final int line;

  /// The raw body lines directly under this heading (before any child
  /// heading), in source order.
  final List<String> bodyLines = [];

  /// The source line of the first body line (heading line + 1).
  int get bodyStartLine => line + 1;

  /// The directly nested sections, in source order.
  ///
  /// Order is load-bearing for the reader, not for validation: cardinality is
  /// counted per section-type name, so the same type may appear repeatedly
  /// and interleaved with others without that alone being a violation. It is
  /// the *counts*, matched against the parent type's `subsection-types`, that
  /// decide.
  final List<DocSpecsSection> children = [];

  /// The trimmed body text (leading/trailing blank lines removed).
  String get text {
    var start = 0;
    var end = bodyLines.length;
    while (start < end && bodyLines[start].trim().isEmpty) {
      start++;
    }
    while (end > start && bodyLines[end - 1].trim().isEmpty) {
      end--;
    }
    return bodyLines.sublist(start, end).join('\n');
  }
}

/// A schema-free DocSpecs markdown parse: the declared schema header (if
/// any), the top-level [sections], and the parse-time [violations]
/// (malformed headings). Validation against a schema is a separate step —
/// [DocSpecsValidator.validate] — which folds these violations into its
/// result.
class DocSpecsDocument {
  DocSpecsDocument._();

  /// The `<!-- docspec: schema-id/version -->` declaration, when present.
  String? declaredSchema;

  /// Top-level (usually one: the document root) sections in source order.
  final List<DocSpecsSection> sections = [];

  /// Parse-time violations: [DocSpecsViolationRule.malformedHeading] for each
  /// heading without a `<!--[SECTION-ID]-->` comment.
  final List<DocSpecsViolation> violations = [];

  static final RegExp _docspecHeader =
      RegExp(r'^<!--\s*docspec:\s*(\S+)\s*-->\s*$');

  /// Parses [text] into the generic section tree. Any markdown is accepted;
  /// structural problems surface as [violations], never as exceptions.
  static DocSpecsDocument parse(String text) {
    final doc = DocSpecsDocument._();
    final fence = MarkdownFenceTracker();
    final stack = <DocSpecsSection>[];
    final lines = text.split('\n');
    for (var i = 0; i < lines.length; i++) {
      final raw = lines[i];
      final lineNo = i + 1;
      final trimmed = raw.trimRight();
      if (!fence.inFence) {
        if (stack.isEmpty && doc.declaredSchema == null) {
          final d = _docspecHeader.firstMatch(trimmed);
          if (d != null) {
            doc.declaredSchema = d.group(1);
            continue;
          }
        }
        final h = SpecDocumentMarkdown.headingLine.firstMatch(trimmed);
        if (h != null) {
          final level = h.group(1)!.length;
          final rest = h.group(2)!.trim();
          final c = SpecDocumentMarkdown.headlineComment.firstMatch(rest);
          final section = DocSpecsSection(
            id: c?.group(1),
            // group(2) is the optional key=value region (codespecs_mapping.md
            // §9.2 codeSpec); the title is group(3). For a bare heading with no
            // comment, the whole rest is the title.
            title: c != null ? c.group(3)!.trim() : rest,
            level: level,
            line: lineNo,
          );
          if (c == null) {
            doc.violations.add(DocSpecsViolation(
              rule: DocSpecsViolationRule.malformedHeading,
              line: lineNo,
              message: 'heading "$rest" carries no <!--[SECTION-ID]--> '
                  'headline comment',
            ));
          }
          while (stack.isNotEmpty && stack.last.level >= level) {
            stack.removeLast();
          }
          (stack.isEmpty ? doc.sections : stack.last.children).add(section);
          stack.add(section);
          continue;
        }
      }
      if (stack.isNotEmpty) stack.last.bodyLines.add(raw);
      fence.feed(raw);
    }
    return doc;
  }
}

// ---------------------------------------------------------------------------
// 2. Schema loading
// ---------------------------------------------------------------------------

/// The DocSpecs id transform used for prefix matching: every run of
/// non-alphanumeric characters becomes `_` — the exact transform the schema
/// generator applies when deriving a `prefix:` from a section id (the
/// DocSpecs prefix grammar forbids dashes).
String docSpecsIdTransform(String id) =>
    id.replaceAll(RegExp(r'[^a-zA-Z0-9_]+'), '_');

/// A `pattern-check` / `pattern-check-id` rule: the regex [pattern] plus the
/// authored [errorMessage].
class DocSpecsPatternCheck {
  /// [pattern] is required and [errorMessage] is not, mirroring the schema's
  /// two spellings: a check written as a bare scalar carries only the regex,
  /// while the map form adds authored wording. A check with no regex has no
  /// meaning, so there is no default for it.
  DocSpecsPatternCheck({required this.pattern, this.errorMessage});

  /// The regex source as authored in the schema, uncompiled.
  ///
  /// Held as a string rather than a `RegExp` because it crosses to eight
  /// other runtimes verbatim; each compiles it with its own engine. The
  /// corollary is that it is only validated when first applied — a
  /// syntactically invalid pattern loads without complaint and throws from
  /// [matches].
  ///
  /// It is applied with `hasMatch`, i.e. **unanchored**: a schema that means
  /// "the whole id" must write `^…$` itself. Generated schemas do
  /// (`^GOAL-ITEM-.+$`, SOM §13).
  final String pattern;

  /// The schema's authored `error-message`, or `null`.
  ///
  /// When present it *replaces* the generated violation wording rather than
  /// supplementing it, so it has to be a complete sentence about the failure
  /// — the id and the pattern it failed are not appended.
  final String? errorMessage;

  /// Whether [value] satisfies [pattern], compiling the regex on each call.
  ///
  /// Throws `FormatException` when the authored pattern is not valid regex —
  /// deliberately not caught here, because a broken schema is a schema
  /// defect, and swallowing it would silently pass every value the check was
  /// meant to reject.
  bool matches(String value) => RegExp(pattern).hasMatch(value);
}

/// One subsection slot of a section-type: `min-count` (default 0) and
/// `max-count` (`null` = infinite).
class DocSpecsSubsectionRule {
  /// Both bounds are required, [maxCount] included even though it is
  /// nullable, so that "unbounded" is always an explicit `null` rather than
  /// an omitted argument. The schema loader supplies the defaults (`0` and
  /// `null`) when the YAML states neither.
  DocSpecsSubsectionRule({required this.minCount, required this.maxCount});

  /// The minimum number of occurrences; `0` means optional.
  ///
  /// A shortfall is reported two different ways on purpose:
  /// [DocSpecsViolationRule.missingRequiredSection] when the count is zero —
  /// the subsection is absent — and
  /// [DocSpecsViolationRule.tooFewItems] when some occur but not enough.
  /// Derived from `@Min` (SOM §13).
  final int minCount;

  /// The maximum number of occurrences, or `null` for unbounded.
  ///
  /// `null` covers both an absent `max-count` and the literal `infinite` a
  /// generated list container writes, which is why the loader accepts only an
  /// `int` here and treats everything else as no ceiling — an unparseable
  /// bound must not silently become a strict one.
  final int? maxCount;
}

/// One `section-types:` entry of a DocSpecs schema.
class DocSpecsSectionType {
  /// Only [name] and [prefix] are required — the identity a
  /// `subsection-types` entry refers to, and the string resolution matches
  /// on. Without either, the type could be declared but never reached.
  ///
  /// Every other argument is a constraint that defaults to "unconstrained",
  /// so a type that merely declares a slot in the tree needs none of them: no
  /// id pattern, no children, no format, no text requirement.
  DocSpecsSectionType({
    required this.name,
    required this.prefix,
    this.patternCheckId,
    this.subsectionTypes = const {},
    this.format,
    this.textRequired = false,
    this.minTextLength,
    this.maxTextLength,
    this.description,
    this.validationPrompt,
  });

  /// The type's key in `section-types:` — its section id lower-cased
  /// (SOM §13).
  ///
  /// This is the name `subsection-types:` and `document: sections:` refer to,
  /// and the name that appears in violation messages, so it is the vocabulary
  /// a schema author and a reader of the output share.
  final String name;

  /// The id prefix (in transformed grammar — see [docSpecsIdTransform]) a
  /// heading id must start with to resolve to this type.
  final String prefix;

  /// The `pattern-check-id` a heading's id must satisfy, or `null` when the
  /// prefix match is the whole requirement.
  ///
  /// Applied *after* resolution, not as part of it: a heading that matches
  /// the prefix but fails this is an
  /// [DocSpecsViolationRule.idPatternMismatch] against this type, never an
  /// unknown section. Generated schemas carry it on list-element types, where
  /// it is the `@SectionIdPattern` stem compiled to `.+` (SOM §13) — so it
  /// checks that the stem survived, not how the item was numbered.
  final DocSpecsPatternCheck? patternCheckId;

  /// Allowed child section-type names → cardinality.
  final Map<String, DocSpecsSubsectionRule> subsectionTypes;

  /// A form-type name (`*-form`) or a raw content format (`code`, `mermaid`).
  final String? format;

  /// Whether an empty body is a [DocSpecsViolationRule.textRequired]
  /// violation. Derived from `@TextRequired` (SOM §13).
  ///
  /// Ignored for a form-formatted section, whose body is field lines rather
  /// than prose — see [format].
  final bool textRequired;

  /// The minimum body length in **characters** of the trimmed body text
  /// (`@MinLength`), or `null` for no floor.
  ///
  /// Checked only when the body is non-empty: an empty body is either
  /// [textRequired]'s finding or no finding at all, so a floor cannot double
  /// as a "must have text" rule. That asymmetry is what lets a generated list
  /// container state `min-text-length: 0` / `max-text-length: 0` — an
  /// always-empty body (SOM §13) — and have an empty one pass.
  final int? minTextLength;

  /// The maximum body length in characters (`@MaxLength`), or `null` for no
  /// ceiling. Reported together with [minTextLength] as one
  /// [DocSpecsViolationRule.textLengthOut], never as two findings.
  final int? maxTextLength;

  /// Author-facing guidance for the section, taken from `@ContentHelp` or the
  /// model's doc comment (SOM §13). Carried for editors and prompts; no rule
  /// here reads it.
  final String? description;

  /// Carried as data (SOM §14) — not interpreted by this validator.
  final String? validationPrompt;
}

/// One field of a `form-types:` entry.
class DocSpecsFormField {
  /// Only [name] is required; a field that is neither mandatory nor
  /// pattern-checked still has to be declared, because an *undeclared* label
  /// is not read as a field at all — [DocSpecsValidator] matches body lines
  /// against this list, so anything missing from it is swallowed as
  /// continuation text of the preceding field.
  DocSpecsFormField({
    required this.name,
    this.required = false,
    this.description,
    this.patternCheck,
  });

  /// The schema's `fieldname`. Matching against a `FieldName:` body line is
  /// **case-insensitive** (SOM §11.4 rule 1), so two fields differing only in
  /// case would collide — the loader keeps whichever it read last.
  final String name;

  /// Whether absence — or a present-but-empty value — is a
  /// [DocSpecsViolationRule.missingRequiredField].
  ///
  /// Note that empty counts as missing: a bare `Field:` line satisfies
  /// nothing, because the flush step drops a value that trims to nothing.
  final bool required;

  /// Author-facing guidance, generated from the model field's `hint`
  /// (SOM §13). Carried as data; no rule reads it.
  final String? description;

  /// The `pattern-check` the field's value must satisfy, or `null`.
  ///
  /// Checked only when a value is present, and *skipped entirely* for a
  /// missing required field — that case already reported
  /// [DocSpecsViolationRule.missingRequiredField], and a second finding on
  /// the same line would be noise. An optional field left empty is therefore
  /// never a pattern violation.
  final DocSpecsPatternCheck? patternCheck;
}

/// One `form-types:` entry: an ordered field list.
class DocSpecsFormType {
  /// Both arguments are required: a form-type with no name could not be
  /// referenced by a section-type's `format:`, and an empty [fields] list is
  /// a legitimate (if vacuous) form, so it must be stated rather than
  /// defaulted.
  DocSpecsFormType({required this.name, required this.fields});

  /// The `form-types:` key — by generator convention `<id>-form` (SOM §13),
  /// and the exact string a section-type's `format:` must carry to select
  /// this form. A `format:` naming no known form-type is not an error: it
  /// falls through to the fenced-block rule instead.
  final String name;

  /// The declared fields in `@Form` order (SOM §13), which is the order the
  /// markdown emitter writes them in.
  ///
  /// Validation itself is order-insensitive — a document may state the fields
  /// in any order, and only the declared *set* is checked — so this order
  /// matters for emission and display, not for the verdict.
  final List<DocSpecsFormField> fields;
}

/// One `document: sections:` slot: the backing section-type and whether the
/// slot is optional.
class DocSpecsDocumentSection {
  /// Both arguments are required; in particular [optional] has no default,
  /// so a slot's requiredness is always an explicit statement. The loader
  /// supplies `false` — required — when the YAML says nothing, matching
  /// SOM §13, where a top-level section is listed because `@Min` ≥ 1.
  DocSpecsDocumentSection({required this.sectionType, required this.optional});

  /// The [DocSpecsSectionType.name] backing this slot.
  ///
  /// It defaults to the slot's own key when the YAML entry does not name one,
  /// so slot key and type name usually coincide — but they are matched
  /// separately: root children are matched by *type*, while a
  /// [DocSpecsViolationRule.missingRequiredSection] names the *slot key*.
  final String sectionType;

  /// Whether the document may omit this slot.
  ///
  /// A required slot with no occurrence is reported once against the document
  /// root, not per missing heading. Note the counting is by section-type, so
  /// two slots backed by the same type are both satisfied by one occurrence.
  final bool optional;
}

/// A loaded `*.docspecs-schema.yaml` (the schema-generator output format , SOM §13): the
/// `title-format`, the ordered [sectionTypes] (file order — descending prefix
/// length in generated schemas, so first-startsWith-match is longest-prefix
/// resolution), the [formTypes], and the [documentSections]. Schema features
/// outside the SOM §14 scope are ignored on load and named in [warnings].
class DocSpecsSchema {
  DocSpecsSchema._();

  /// The schema's `title-format` — the literal level-1 heading a conforming
  /// document must open with, e.g. `# <!--[DEMO]--> Demo Document`
  /// (SOM §13).
  ///
  /// Only the id inside it is enforced ([rootSectionId]); the title text is
  /// not compared, since a document names itself. `null` when the schema
  /// declares none, in which case the root heading id is unconstrained.
  String? titleFormat;

  /// Section types in file order; resolution takes the **first** type whose
  /// [DocSpecsSectionType.prefix] is a prefix of the transformed id.
  final List<DocSpecsSectionType> sectionTypes = [];
  /// The same types indexed by [DocSpecsSectionType.name], for the by-name
  /// lookups `subsection-types:` and `document: sections:` need.
  ///
  /// A second view of [sectionTypes], not a second population: the two are
  /// filled together, and this one loses file order — which is why prefix
  /// resolution must go through the list and never through this map.
  final Map<String, DocSpecsSectionType> sectionTypesByName = {};

  /// The `form-types:` keyed by name. A section-type's `format:` is looked up
  /// here first; a miss means the format is a raw content format (`code`,
  /// `mermaid`, …) demanding a fenced block instead.
  final Map<String, DocSpecsFormType> formTypes = {};

  /// The `document: sections:` slots keyed by their YAML key.
  ///
  /// The key is what a [DocSpecsViolationRule.missingRequiredSection] names,
  /// while membership of a root child is decided by
  /// [DocSpecsDocumentSection.sectionType] — so the two differ whenever a
  /// slot renames its type.
  final Map<String, DocSpecsDocumentSection> documentSections = {};

  /// Every schema feature encountered but not interpreted, named — nothing is
  /// silently dropped.
  final List<String> warnings = [];

  /// The root section id demanded by [titleFormat], when derivable.
  String? get rootSectionId {
    final tf = titleFormat;
    if (tf == null) return null;
    return RegExp(r'<!--\[([^\]]+)\]-->').firstMatch(tf)?.group(1);
  }

  static const _sectionTypeKeys = {
    'prefix',
    'pattern-check-id',
    'subsection-types',
    'format',
    'text-required',
    'min-text-length',
    'max-text-length',
    'description',
    'validation-prompt',
  };

  /// Loads a schema from its YAML [text]. Malformed YAML throws; unsupported
  /// features are collected into [DocSpecsSchema.warnings] instead.
  static DocSpecsSchema fromYamlText(String text) {
    final schema = DocSpecsSchema._();
    final rootNode = loadYaml(text);
    if (rootNode is! Map) {
      throw FormatException('docspecs schema must be a YAML map');
    }
    final root = rootNode;
    for (final key in root.keys) {
      final k = '$key';
      switch (k) {
        case 'title-format':
          schema.titleFormat = '${root[key]}';
        case 'section-types':
          _loadSectionTypes(schema, root[key]);
        case 'form-types':
          _loadFormTypes(schema, root[key]);
        case 'document':
          _loadDocument(schema, root[key]);
        case 'schema' || 'version' || 'name' || 'description':
          break; // informational headers — accepted, no semantics here.
        default:
          schema.warnings.add('unsupported top-level schema key "$k" ignored');
      }
    }
    return schema;
  }

  static DocSpecsPatternCheck? _patternCheck(Object? node) {
    if (node == null) return null;
    if (node is Map) {
      return DocSpecsPatternCheck(
        pattern: '${node['pattern']}',
        errorMessage:
            node['error-message'] == null ? null : '${node['error-message']}',
      );
    }
    return DocSpecsPatternCheck(pattern: '$node');
  }

  static void _loadSectionTypes(DocSpecsSchema schema, Object? node) {
    if (node is! Map) return;
    for (final entry in node.entries) {
      final name = '${entry.key}';
      final st = entry.value;
      if (st is! Map) continue;
      final subs = <String, DocSpecsSubsectionRule>{};
      final subsNode = st['subsection-types'];
      if (subsNode is Map) {
        for (final s in subsNode.entries) {
          final rule = s.value;
          final min = rule is Map ? rule['min-count'] : null;
          final max = rule is Map ? rule['max-count'] : null;
          subs['${s.key}'] = DocSpecsSubsectionRule(
            minCount: min is int ? min : 0,
            maxCount: max is int ? max : null, // 'infinite' or absent → null
          );
        }
      }
      for (final key in st.keys) {
        if (!_sectionTypeKeys.contains('$key')) {
          schema.warnings.add(
              'unsupported key "$key" on section-type "$name" ignored');
        }
      }
      final type = DocSpecsSectionType(
        name: name,
        prefix: '${st['prefix'] ?? docSpecsIdTransform(name.toUpperCase())}',
        patternCheckId: _patternCheck(st['pattern-check-id']),
        subsectionTypes: subs,
        format: st['format'] == null ? null : '${st['format']}',
        textRequired: st['text-required'] == true,
        minTextLength:
            st['min-text-length'] is int ? st['min-text-length'] as int : null,
        maxTextLength:
            st['max-text-length'] is int ? st['max-text-length'] as int : null,
        description: st['description'] == null ? null : '${st['description']}',
        validationPrompt: st['validation-prompt'] == null
            ? null
            : '${st['validation-prompt']}',
      );
      schema.sectionTypes.add(type);
      schema.sectionTypesByName[name] = type;
    }
  }

  static void _loadFormTypes(DocSpecsSchema schema, Object? node) {
    if (node is! Map) return;
    for (final entry in node.entries) {
      final name = '${entry.key}';
      final ft = entry.value;
      if (ft is! Map) continue;
      for (final key in ft.keys) {
        if ('$key' != 'fields') {
          schema.warnings
              .add('unsupported key "$key" on form-type "$name" ignored');
        }
      }
      final fields = <DocSpecsFormField>[];
      final fieldsNode = ft['fields'];
      if (fieldsNode is List) {
        for (final f in fieldsNode) {
          if (f is! Map) continue;
          fields.add(DocSpecsFormField(
            name: '${f['fieldname']}',
            required: f['required'] == true,
            description:
                f['description'] == null ? null : '${f['description']}',
            patternCheck: _patternCheck(f['pattern-check']),
          ));
        }
      }
      schema.formTypes[name] = DocSpecsFormType(name: name, fields: fields);
    }
  }

  static void _loadDocument(DocSpecsSchema schema, Object? node) {
    if (node is! Map) return;
    for (final key in node.keys) {
      final k = '$key';
      if (k == 'sections') {
        final sections = node[key];
        if (sections is! Map) continue;
        for (final s in sections.entries) {
          final v = s.value;
          schema.documentSections['${s.key}'] = DocSpecsDocumentSection(
            sectionType:
                v is Map ? '${v['section-type'] ?? s.key}' : '${s.key}',
            optional: v is Map && v['optional'] == true,
          );
        }
      } else if (k != 'name' && k != 'description') {
        schema.warnings.add('unsupported document key "$k" ignored');
      }
    }
  }

  /// Resolves a heading [id] to its section-type: the first type (file order)
  /// whose [DocSpecsSectionType.prefix] prefixes the transformed id.
  DocSpecsSectionType? resolveSectionType(String id) {
    final transformed = docSpecsIdTransform(id);
    for (final t in sectionTypes) {
      if (transformed.startsWith(t.prefix)) return t;
    }
    return null;
  }
}

// ---------------------------------------------------------------------------
// 3. Validation
// ---------------------------------------------------------------------------

/// Validates a schema-free [DocSpecsDocument] against a [DocSpecsSchema]
/// (SOM §14). Stateless per document; [validate] always returns the complete
/// violation list (never fail-fast); a document is valid iff it is empty.
class DocSpecsValidator {
  /// Binds the validator to one [schema]. The schema is the only state, so an
  /// instance is reusable across any number of documents and safe to hold for
  /// the life of a session — construct it once per schema, not per document.
  DocSpecsValidator(this.schema);

  /// The schema every check is made against.
  ///
  /// Note that nothing here compares it to the document's own
  /// `<!-- docspec: … -->` declaration
  /// ([DocSpecsDocument.declaredSchema]) — picking the right schema for a
  /// document is the caller's job, and validating against the wrong one
  /// yields a long, plausible-looking violation list rather than an error.
  final DocSpecsSchema schema;

  /// Convenience: parse + validate in one call.
  List<DocSpecsViolation> validateMarkdown(String markdown) =>
      validate(DocSpecsDocument.parse(markdown));

  /// Checks [doc] against [schema] and returns **every** finding; the
  /// document is valid iff the list is empty (SOM §14).
  ///
  /// Never fails fast and never throws on a malformed document — a document
  /// too broken to walk yields violations, not an exception. The one thing
  /// that can throw is a schema whose `pattern` is invalid regex, which is a
  /// schema defect rather than a document one.
  ///
  /// The result opens with the parse-time findings [doc] already carried
  /// (malformed headings), then the root checks, then a depth-first walk — so
  /// the list is *roughly* source order but not sorted; sort on
  /// [DocSpecsViolation.line] if presentation order matters.
  ///
  /// Two structural rules bound the walk: a document with no heading at all
  /// is a single [DocSpecsViolationRule.formatMismatch] and stops there, and
  /// only the **first** top-level section is treated as the root — every
  /// further one is an [DocSpecsViolationRule.unknownSection] and is not
  /// descended into, so its subtree is never reported.
  List<DocSpecsViolation> validate(DocSpecsDocument doc) {
    final v = <DocSpecsViolation>[...doc.violations];
    if (doc.sections.isEmpty) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.formatMismatch,
        line: 1,
        message: 'document has no root heading',
      ));
      return v;
    }
    final rootId = schema.rootSectionId;
    final root = doc.sections.first;
    if (rootId != null && root.id != rootId) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.formatMismatch,
        sectionId: root.id,
        line: root.line,
        message: 'root heading id "${root.id}" does not match the schema '
            'title-format id "$rootId"',
      ));
    }
    for (final extra in doc.sections.skip(1)) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.unknownSection,
        sectionId: extra.id,
        line: extra.line,
        message: 'unexpected additional top-level section',
      ));
    }
    _validateDocumentSections(root, v);
    return v;
  }

  /// Root children must occupy `document: sections:` slots; required slots
  /// must be present.
  void _validateDocumentSections(
      DocSpecsSection root, List<DocSpecsViolation> v) {
    final counts = <String, int>{};
    for (final child in root.children) {
      final type = _resolveChild(child, v);
      if (type == null) continue;
      if (!schema.documentSections.values
          .any((s) => s.sectionType == type.name)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.unknownSection,
          sectionId: child.id,
          line: child.line,
          message: 'section-type "${type.name}" is not a top-level document '
              'section',
        ));
        continue;
      }
      counts[type.name] = (counts[type.name] ?? 0) + 1;
      _validateSection(child, type, v);
    }
    for (final slot in schema.documentSections.entries) {
      if (!slot.value.optional && (counts[slot.value.sectionType] ?? 0) == 0) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.missingRequiredSection,
          sectionId: slot.key,
          line: root.line,
          message: 'required document section "${slot.key}" '
              '(type "${slot.value.sectionType}") is missing',
        ));
      }
    }
  }

  DocSpecsSectionType? _resolveChild(
      DocSpecsSection child, List<DocSpecsViolation> v) {
    final id = child.id;
    if (id == null) return null; // already reported as malformedHeading.
    final type = schema.resolveSectionType(id);
    if (type == null) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.unknownSection,
        sectionId: id,
        line: child.line,
        message: 'section id "$id" resolves to no section-type of the schema',
      ));
    }
    return type;
  }

  void _validateSection(DocSpecsSection section, DocSpecsSectionType type,
      List<DocSpecsViolation> v) {
    final id = section.id!;
    final pc = type.patternCheckId;
    if (pc != null && !pc.matches(id)) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.idPatternMismatch,
        sectionId: id,
        line: section.line,
        message: pc.errorMessage ??
            'section id "$id" does not match pattern "${pc.pattern}"',
      ));
    }

    _validateText(section, type, v);
    _validateFormat(section, type, v);

    // Children: membership + cardinality against subsection-types.
    final counts = <String, int>{};
    for (final child in section.children) {
      final childType = _resolveChild(child, v);
      if (childType == null) continue;
      if (!type.subsectionTypes.containsKey(childType.name)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.unknownSection,
          sectionId: child.id,
          line: child.line,
          message: 'section-type "${childType.name}" is not an allowed '
              'subsection of "${type.name}"',
        ));
        continue;
      }
      counts[childType.name] = (counts[childType.name] ?? 0) + 1;
      _validateSection(child, childType, v);
    }
    for (final sub in type.subsectionTypes.entries) {
      final count = counts[sub.key] ?? 0;
      if (count < sub.value.minCount) {
        v.add(count == 0
            ? DocSpecsViolation(
                rule: DocSpecsViolationRule.missingRequiredSection,
                sectionId: id,
                line: section.line,
                message: 'required subsection "${sub.key}" of "${type.name}" '
                    'is missing',
              )
            : DocSpecsViolation(
                rule: DocSpecsViolationRule.tooFewItems,
                sectionId: id,
                line: section.line,
                message: 'subsection "${sub.key}" occurs $count time(s), '
                    'minimum is ${sub.value.minCount}',
              ));
      }
      final max = sub.value.maxCount;
      if (max != null && count > max) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.tooManyItems,
          sectionId: id,
          line: section.line,
          message:
              'subsection "${sub.key}" occurs $count time(s), maximum is $max',
        ));
      }
    }
  }

  void _validateText(DocSpecsSection section, DocSpecsSectionType type,
      List<DocSpecsViolation> v) {
    // Form-formatted sections carry field lines, not free text.
    if (type.format != null && schema.formTypes.containsKey(type.format)) {
      return;
    }
    final text = section.text;
    if (type.textRequired && text.isEmpty) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.textRequired,
        sectionId: section.id,
        line: section.line,
        message: 'section requires body text but has none',
      ));
      return;
    }
    if (text.isEmpty) return;
    final min = type.minTextLength;
    final max = type.maxTextLength;
    if ((min != null && text.length < min) ||
        (max != null && text.length > max)) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.textLengthOut,
        sectionId: section.id,
        line: section.line,
        message: 'body text length ${text.length} is outside '
            '[${min ?? 0}, ${max ?? '∞'}]',
      ));
    }
  }

  void _validateFormat(DocSpecsSection section, DocSpecsSectionType type,
      List<DocSpecsViolation> v) {
    final format = type.format;
    if (format == null) return;
    final form = schema.formTypes[format];
    if (form != null) {
      _validateForm(section, form, v);
      return;
    }
    // A non-form format (`code`, `mermaid`, …) demands a fenced block.
    final fence = MarkdownFenceTracker();
    var sawFence = false;
    for (final line in section.bodyLines) {
      fence.feed(line);
      if (fence.inFence) sawFence = true;
    }
    if (!sawFence) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.formatMismatch,
        sectionId: section.id,
        line: section.line,
        message: 'section format "$format" demands a fenced code block, '
            'but the body contains none',
      ));
    }
  }

  static final RegExp _fieldLabel = RegExp(r'^([A-Za-z][A-Za-z0-9_]*): ?(.*)$');

  /// Parses the section body in the DocSpecs plain-text form format
  /// (`FieldName: value`, case-insensitive labels, continuation lines) and
  /// checks required fields + field pattern-checks. Text before the first
  /// recognised label is tolerated here (the binding parse reports it).
  void _validateForm(DocSpecsSection section, DocSpecsFormType form,
      List<DocSpecsViolation> v) {
    final byLower = {for (final f in form.fields) f.name.toLowerCase(): f};
    final values = <String, String>{};
    final fieldLines = <String, int>{};
    final fence = MarkdownFenceTracker();
    String? current;
    var currentLines = <String>[];

    void flush() {
      final field = current;
      if (field == null) return;
      final text = currentLines.join('\n').trim();
      if (text.isNotEmpty) values[field] = text;
      currentLines = <String>[];
    }

    for (var i = 0; i < section.bodyLines.length; i++) {
      final line = section.bodyLines[i];
      if (!fence.inFence) {
        final m = _fieldLabel.firstMatch(line);
        final field = m != null ? byLower[m.group(1)!.toLowerCase()] : null;
        if (field != null) {
          flush();
          current = field.name;
          fieldLines[field.name] = section.bodyStartLine + i;
          currentLines = [m!.group(2)!];
          fence.feed(line);
          continue;
        }
      }
      if (current != null) currentLines.add(line);
      fence.feed(line);
    }
    flush();

    for (final field in form.fields) {
      final value = values[field.name];
      if (field.required && (value == null || value.isEmpty)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.missingRequiredField,
          sectionId: section.id,
          line: section.line,
          message: 'required form field "${field.name}" of "${form.name}" '
              'is missing',
        ));
        continue;
      }
      final pc = field.patternCheck;
      if (value != null && pc != null && !pc.matches(value)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.fieldPatternMismatch,
          sectionId: section.id,
          line: fieldLines[field.name] ?? section.line,
          message: pc.errorMessage ??
              'form field "${field.name}" does not match pattern '
                  '"${pc.pattern}"',
        ));
      }
    }
  }
}

// ---------------------------------------------------------------------------
// 4. Binding onto the SOM metadata tree (SOM §14 capability 3)
// ---------------------------------------------------------------------------

/// Binds a DocSpecs markdown [text] onto the SOM metadata tree of [model],
/// staging values against [document]'s path grammar — the SOM §11.7 entry point,
/// delegated to [SpecDocumentMarkdown.parse].
SpecMarkdownResult bindDocSpecsMarkdown(
        SpecModel model, SpecDocument document, String text) =>
    SpecDocumentMarkdown(model, document).parse(text);
