/// Consolidated DocSpecs parsing + validation (DR1 §6): the embedded,
/// runtime-owned equivalent of the `tom_doc_scanner` + `tom_doc_specs` split,
/// redesigned as one coherent API. This is the reference implementation the
/// other eight language runtimes port; the Dart violation messages are the
/// golden reference — every port must produce the same `rule` / `sectionId` /
/// `line` triples.
///
/// Three capabilities, one module:
///
///  1. **Parse** — [DocSpecsDocument.parse] reads any DocSpecs `*.md`
///     *schema-free* into a generic section tree ([DocSpecsSection]): ids,
///     titles, heading levels, body text, source lines. Fenced code blocks
///     shield their lines from heading detection ([MarkdownFenceTracker], the
///     exact semantics of the [SpecDocumentMarkdown] codec).
///  2. **Validate** — [DocSpecsValidator.validate] checks a parsed document
///     against a [DocSpecsSchema] (a `*.docspecs-schema.yaml` as generated by
///     the DR3 schema generator) and returns a structured
///     [DocSpecsViolation] list. Validation **never fails fast** — the full
///     list is always produced; a document is valid iff the list is empty.
///  3. **Bind** — [bindDocSpecsMarkdown] maps the same markdown onto the SOM
///     metadata tree, delegating to [SpecDocumentMarkdown.parse] (DR1 §1.7).
///
/// Supported schema features (the DR1 §6 scope): section-types (`prefix`,
/// `pattern-check-id`, `subsection-types` with `min-count`/`max-count`,
/// `format`, `text-required`, `min-text-length`/`max-text-length`,
/// `description`), form-types (fields with `required` and `pattern-check`),
/// and the `document:` structure (top-level sections, `optional`).
/// `validation-prompt` values are carried as data. Anything else — generator
/// placeholders, database-schema sections, custom tags — is **ignored on
/// load** and named in [DocSpecsSchema.warnings]; nothing is silently
/// dropped (DR1 §7).
library;

import 'package:yaml/yaml.dart';

import 'spec_document.dart';
import 'spec_document_markdown.dart';
import 'spec_model.dart';

/// The DR1 §6 violation rule vocabulary — identical across all nine runtimes.
enum DocSpecsViolationRule {
  /// A heading's id resolves to no section-type, or to a type not allowed at
  /// its nesting position.
  unknownSection,

  /// A required section (document slot or `min-count >= 1` subsection) has no
  /// occurrence.
  missingRequiredSection,

  /// A section id fails its type's `pattern-check-id`.
  idPatternMismatch,

  /// A subsection occurs, but fewer times than its `min-count`.
  tooFewItems,

  /// A subsection occurs more times than its numeric `max-count`.
  tooManyItems,

  /// A `required` form field is absent (or empty) in a form-formatted section.
  missingRequiredField,

  /// A form field value fails its `pattern-check`.
  fieldPatternMismatch,

  /// A `text-required` section has no body text.
  textRequired,

  /// A section's body text length is outside `min-text-length` /
  /// `max-text-length`.
  textLengthOut,

  /// The document/root shape does not match — wrong root id vs `title-format`,
  /// or a non-form `format` section without the demanded fenced block.
  formatMismatch,

  /// A heading line without a parseable `<!--[SECTION-ID]-->` comment.
  malformedHeading,
}

/// One structured violation (DR1 §6): the [rule], the offending [sectionId]
/// (when one exists), the bound runtime [path] (when resolvable), the 1-based
/// source [line], and a human-readable [message].
class DocSpecsViolation {
  DocSpecsViolation({
    required this.rule,
    required this.line,
    required this.message,
    this.sectionId,
    this.path,
  });

  final DocSpecsViolationRule rule;
  final String? sectionId;
  final String? path;
  final int line;
  final String message;

  @override
  String toString() =>
      'line $line: ${rule.name}${sectionId != null ? ' [$sectionId]' : ''}'
      '${path != null ? ' ($path)' : ''} — $message';
}

// ---------------------------------------------------------------------------
// 1. Generic (schema-free) markdown parse
// ---------------------------------------------------------------------------

/// One section of a schema-free DocSpecs parse: its [id] (null for a
/// malformed heading), heading [title], markdown [level], 1-based heading
/// [line], accumulated [bodyLines] (each with its own source line =
/// [bodyStartLine] + index), and nested [children].
class DocSpecsSection {
  DocSpecsSection({
    required this.id,
    required this.title,
    required this.level,
    required this.line,
  });

  final String? id;
  final String title;
  final int level;
  final int line;

  /// The raw body lines directly under this heading (before any child
  /// heading), in source order.
  final List<String> bodyLines = [];

  /// The source line of the first body line (heading line + 1).
  int get bodyStartLine => line + 1;

  final List<DocSpecsSection> children = [];

  /// The trimmed body text (leading/trailing blank lines removed).
  String get text {
    var start = 0;
    var end = bodyLines.length;
    while (start < end && bodyLines[start].trim().isEmpty) {
      start++;
    }
    while (end > start && bodyLines[end - 1].trim().isEmpty) {
      end--;
    }
    return bodyLines.sublist(start, end).join('\n');
  }
}

/// A schema-free DocSpecs markdown parse: the declared schema header (if
/// any), the top-level [sections], and the parse-time [violations]
/// (malformed headings). Validation against a schema is a separate step —
/// [DocSpecsValidator.validate] — which folds these violations into its
/// result.
class DocSpecsDocument {
  DocSpecsDocument._();

  /// The `<!-- docspec: schema-id/version -->` declaration, when present.
  String? declaredSchema;

  /// Top-level (usually one: the document root) sections in source order.
  final List<DocSpecsSection> sections = [];

  /// Parse-time violations: [DocSpecsViolationRule.malformedHeading] for each
  /// heading without a `<!--[SECTION-ID]-->` comment.
  final List<DocSpecsViolation> violations = [];

  static final RegExp _docspecHeader =
      RegExp(r'^<!--\s*docspec:\s*(\S+)\s*-->\s*$');

  /// Parses [text] into the generic section tree. Any markdown is accepted;
  /// structural problems surface as [violations], never as exceptions.
  static DocSpecsDocument parse(String text) {
    final doc = DocSpecsDocument._();
    final fence = MarkdownFenceTracker();
    final stack = <DocSpecsSection>[];
    final lines = text.split('\n');
    for (var i = 0; i < lines.length; i++) {
      final raw = lines[i];
      final lineNo = i + 1;
      final trimmed = raw.trimRight();
      if (!fence.inFence) {
        if (stack.isEmpty && doc.declaredSchema == null) {
          final d = _docspecHeader.firstMatch(trimmed);
          if (d != null) {
            doc.declaredSchema = d.group(1);
            continue;
          }
        }
        final h = SpecDocumentMarkdown.headingLine.firstMatch(trimmed);
        if (h != null) {
          final level = h.group(1)!.length;
          final rest = h.group(2)!.trim();
          final c = SpecDocumentMarkdown.headlineComment.firstMatch(rest);
          final section = DocSpecsSection(
            id: c?.group(1),
            title: c != null ? c.group(2)!.trim() : rest,
            level: level,
            line: lineNo,
          );
          if (c == null) {
            doc.violations.add(DocSpecsViolation(
              rule: DocSpecsViolationRule.malformedHeading,
              line: lineNo,
              message: 'heading "$rest" carries no <!--[SECTION-ID]--> '
                  'headline comment',
            ));
          }
          while (stack.isNotEmpty && stack.last.level >= level) {
            stack.removeLast();
          }
          (stack.isEmpty ? doc.sections : stack.last.children).add(section);
          stack.add(section);
          continue;
        }
      }
      if (stack.isNotEmpty) stack.last.bodyLines.add(raw);
      fence.feed(raw);
    }
    return doc;
  }
}

// ---------------------------------------------------------------------------
// 2. Schema loading
// ---------------------------------------------------------------------------

/// The DocSpecs id transform used for prefix matching: every run of
/// non-alphanumeric characters becomes `_` — the exact transform the DR3
/// generator applies when deriving a `prefix:` from a section id (the
/// DocSpecs prefix grammar forbids dashes).
String docSpecsIdTransform(String id) =>
    id.replaceAll(RegExp(r'[^a-zA-Z0-9_]+'), '_');

/// A `pattern-check` / `pattern-check-id` rule: the regex [pattern] plus the
/// authored [errorMessage].
class DocSpecsPatternCheck {
  DocSpecsPatternCheck({required this.pattern, this.errorMessage});

  final String pattern;
  final String? errorMessage;

  bool matches(String value) => RegExp(pattern).hasMatch(value);
}

/// One subsection slot of a section-type: `min-count` (default 0) and
/// `max-count` (`null` = infinite).
class DocSpecsSubsectionRule {
  DocSpecsSubsectionRule({required this.minCount, required this.maxCount});

  final int minCount;
  final int? maxCount;
}

/// One `section-types:` entry of a DocSpecs schema.
class DocSpecsSectionType {
  DocSpecsSectionType({
    required this.name,
    required this.prefix,
    this.patternCheckId,
    this.subsectionTypes = const {},
    this.format,
    this.textRequired = false,
    this.minTextLength,
    this.maxTextLength,
    this.description,
    this.validationPrompt,
  });

  final String name;

  /// The id prefix (in transformed grammar — see [docSpecsIdTransform]) a
  /// heading id must start with to resolve to this type.
  final String prefix;

  final DocSpecsPatternCheck? patternCheckId;

  /// Allowed child section-type names → cardinality.
  final Map<String, DocSpecsSubsectionRule> subsectionTypes;

  /// A form-type name (`*-form`) or a raw content format (`code`, `mermaid`).
  final String? format;

  final bool textRequired;
  final int? minTextLength;
  final int? maxTextLength;
  final String? description;

  /// Carried as data (DR1 §6) — not interpreted by this validator.
  final String? validationPrompt;
}

/// One field of a `form-types:` entry.
class DocSpecsFormField {
  DocSpecsFormField({
    required this.name,
    this.required = false,
    this.description,
    this.patternCheck,
  });

  final String name;
  final bool required;
  final String? description;
  final DocSpecsPatternCheck? patternCheck;
}

/// One `form-types:` entry: an ordered field list.
class DocSpecsFormType {
  DocSpecsFormType({required this.name, required this.fields});

  final String name;
  final List<DocSpecsFormField> fields;
}

/// One `document: sections:` slot: the backing section-type and whether the
/// slot is optional.
class DocSpecsDocumentSection {
  DocSpecsDocumentSection({required this.sectionType, required this.optional});

  final String sectionType;
  final bool optional;
}

/// A loaded `*.docspecs-schema.yaml` (the DR3 output format): the
/// `title-format`, the ordered [sectionTypes] (file order — descending prefix
/// length in generated schemas, so first-startsWith-match is longest-prefix
/// resolution), the [formTypes], and the [documentSections]. Schema features
/// outside the DR1 §6 scope are ignored on load and named in [warnings].
class DocSpecsSchema {
  DocSpecsSchema._();

  String? titleFormat;

  /// Section types in file order; resolution takes the **first** type whose
  /// [DocSpecsSectionType.prefix] is a prefix of the transformed id.
  final List<DocSpecsSectionType> sectionTypes = [];
  final Map<String, DocSpecsSectionType> sectionTypesByName = {};
  final Map<String, DocSpecsFormType> formTypes = {};
  final Map<String, DocSpecsDocumentSection> documentSections = {};

  /// Every schema feature encountered but not interpreted, named (DR1 §7:
  /// nothing is silently dropped).
  final List<String> warnings = [];

  /// The root section id demanded by [titleFormat], when derivable.
  String? get rootSectionId {
    final tf = titleFormat;
    if (tf == null) return null;
    return RegExp(r'<!--\[([^\]]+)\]-->').firstMatch(tf)?.group(1);
  }

  static const _sectionTypeKeys = {
    'prefix',
    'pattern-check-id',
    'subsection-types',
    'format',
    'text-required',
    'min-text-length',
    'max-text-length',
    'description',
    'validation-prompt',
  };

  /// Loads a schema from its YAML [text]. Malformed YAML throws; unsupported
  /// features are collected into [DocSpecsSchema.warnings] instead.
  static DocSpecsSchema fromYamlText(String text) {
    final schema = DocSpecsSchema._();
    final rootNode = loadYaml(text);
    if (rootNode is! Map) {
      throw FormatException('docspecs schema must be a YAML map');
    }
    final root = rootNode;
    for (final key in root.keys) {
      final k = '$key';
      switch (k) {
        case 'title-format':
          schema.titleFormat = '${root[key]}';
        case 'section-types':
          _loadSectionTypes(schema, root[key]);
        case 'form-types':
          _loadFormTypes(schema, root[key]);
        case 'document':
          _loadDocument(schema, root[key]);
        case 'schema' || 'version' || 'name' || 'description':
          break; // informational headers — accepted, no semantics here.
        default:
          schema.warnings.add('unsupported top-level schema key "$k" ignored');
      }
    }
    return schema;
  }

  static DocSpecsPatternCheck? _patternCheck(Object? node) {
    if (node == null) return null;
    if (node is Map) {
      return DocSpecsPatternCheck(
        pattern: '${node['pattern']}',
        errorMessage:
            node['error-message'] == null ? null : '${node['error-message']}',
      );
    }
    return DocSpecsPatternCheck(pattern: '$node');
  }

  static void _loadSectionTypes(DocSpecsSchema schema, Object? node) {
    if (node is! Map) return;
    for (final entry in node.entries) {
      final name = '${entry.key}';
      final st = entry.value;
      if (st is! Map) continue;
      final subs = <String, DocSpecsSubsectionRule>{};
      final subsNode = st['subsection-types'];
      if (subsNode is Map) {
        for (final s in subsNode.entries) {
          final rule = s.value;
          final min = rule is Map ? rule['min-count'] : null;
          final max = rule is Map ? rule['max-count'] : null;
          subs['${s.key}'] = DocSpecsSubsectionRule(
            minCount: min is int ? min : 0,
            maxCount: max is int ? max : null, // 'infinite' or absent → null
          );
        }
      }
      for (final key in st.keys) {
        if (!_sectionTypeKeys.contains('$key')) {
          schema.warnings.add(
              'unsupported key "$key" on section-type "$name" ignored');
        }
      }
      final type = DocSpecsSectionType(
        name: name,
        prefix: '${st['prefix'] ?? docSpecsIdTransform(name.toUpperCase())}',
        patternCheckId: _patternCheck(st['pattern-check-id']),
        subsectionTypes: subs,
        format: st['format'] == null ? null : '${st['format']}',
        textRequired: st['text-required'] == true,
        minTextLength:
            st['min-text-length'] is int ? st['min-text-length'] as int : null,
        maxTextLength:
            st['max-text-length'] is int ? st['max-text-length'] as int : null,
        description: st['description'] == null ? null : '${st['description']}',
        validationPrompt: st['validation-prompt'] == null
            ? null
            : '${st['validation-prompt']}',
      );
      schema.sectionTypes.add(type);
      schema.sectionTypesByName[name] = type;
    }
  }

  static void _loadFormTypes(DocSpecsSchema schema, Object? node) {
    if (node is! Map) return;
    for (final entry in node.entries) {
      final name = '${entry.key}';
      final ft = entry.value;
      if (ft is! Map) continue;
      for (final key in ft.keys) {
        if ('$key' != 'fields') {
          schema.warnings
              .add('unsupported key "$key" on form-type "$name" ignored');
        }
      }
      final fields = <DocSpecsFormField>[];
      final fieldsNode = ft['fields'];
      if (fieldsNode is List) {
        for (final f in fieldsNode) {
          if (f is! Map) continue;
          fields.add(DocSpecsFormField(
            name: '${f['fieldname']}',
            required: f['required'] == true,
            description:
                f['description'] == null ? null : '${f['description']}',
            patternCheck: _patternCheck(f['pattern-check']),
          ));
        }
      }
      schema.formTypes[name] = DocSpecsFormType(name: name, fields: fields);
    }
  }

  static void _loadDocument(DocSpecsSchema schema, Object? node) {
    if (node is! Map) return;
    for (final key in node.keys) {
      final k = '$key';
      if (k == 'sections') {
        final sections = node[key];
        if (sections is! Map) continue;
        for (final s in sections.entries) {
          final v = s.value;
          schema.documentSections['${s.key}'] = DocSpecsDocumentSection(
            sectionType:
                v is Map ? '${v['section-type'] ?? s.key}' : '${s.key}',
            optional: v is Map && v['optional'] == true,
          );
        }
      } else if (k != 'name' && k != 'description') {
        schema.warnings.add('unsupported document key "$k" ignored');
      }
    }
  }

  /// Resolves a heading [id] to its section-type: the first type (file order)
  /// whose [DocSpecsSectionType.prefix] prefixes the transformed id.
  DocSpecsSectionType? resolveSectionType(String id) {
    final transformed = docSpecsIdTransform(id);
    for (final t in sectionTypes) {
      if (transformed.startsWith(t.prefix)) return t;
    }
    return null;
  }
}

// ---------------------------------------------------------------------------
// 3. Validation
// ---------------------------------------------------------------------------

/// Validates a schema-free [DocSpecsDocument] against a [DocSpecsSchema]
/// (DR1 §6). Stateless per document; [validate] always returns the complete
/// violation list (never fail-fast); a document is valid iff it is empty.
class DocSpecsValidator {
  DocSpecsValidator(this.schema);

  final DocSpecsSchema schema;

  /// Convenience: parse + validate in one call.
  List<DocSpecsViolation> validateMarkdown(String markdown) =>
      validate(DocSpecsDocument.parse(markdown));

  List<DocSpecsViolation> validate(DocSpecsDocument doc) {
    final v = <DocSpecsViolation>[...doc.violations];
    if (doc.sections.isEmpty) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.formatMismatch,
        line: 1,
        message: 'document has no root heading',
      ));
      return v;
    }
    final rootId = schema.rootSectionId;
    final root = doc.sections.first;
    if (rootId != null && root.id != rootId) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.formatMismatch,
        sectionId: root.id,
        line: root.line,
        message: 'root heading id "${root.id}" does not match the schema '
            'title-format id "$rootId"',
      ));
    }
    for (final extra in doc.sections.skip(1)) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.unknownSection,
        sectionId: extra.id,
        line: extra.line,
        message: 'unexpected additional top-level section',
      ));
    }
    _validateDocumentSections(root, v);
    return v;
  }

  /// Root children must occupy `document: sections:` slots; required slots
  /// must be present.
  void _validateDocumentSections(
      DocSpecsSection root, List<DocSpecsViolation> v) {
    final counts = <String, int>{};
    for (final child in root.children) {
      final type = _resolveChild(child, v);
      if (type == null) continue;
      if (!schema.documentSections.values
          .any((s) => s.sectionType == type.name)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.unknownSection,
          sectionId: child.id,
          line: child.line,
          message: 'section-type "${type.name}" is not a top-level document '
              'section',
        ));
        continue;
      }
      counts[type.name] = (counts[type.name] ?? 0) + 1;
      _validateSection(child, type, v);
    }
    for (final slot in schema.documentSections.entries) {
      if (!slot.value.optional && (counts[slot.value.sectionType] ?? 0) == 0) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.missingRequiredSection,
          sectionId: slot.key,
          line: root.line,
          message: 'required document section "${slot.key}" '
              '(type "${slot.value.sectionType}") is missing',
        ));
      }
    }
  }

  DocSpecsSectionType? _resolveChild(
      DocSpecsSection child, List<DocSpecsViolation> v) {
    final id = child.id;
    if (id == null) return null; // already reported as malformedHeading.
    final type = schema.resolveSectionType(id);
    if (type == null) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.unknownSection,
        sectionId: id,
        line: child.line,
        message: 'section id "$id" resolves to no section-type of the schema',
      ));
    }
    return type;
  }

  void _validateSection(DocSpecsSection section, DocSpecsSectionType type,
      List<DocSpecsViolation> v) {
    final id = section.id!;
    final pc = type.patternCheckId;
    if (pc != null && !pc.matches(id)) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.idPatternMismatch,
        sectionId: id,
        line: section.line,
        message: pc.errorMessage ??
            'section id "$id" does not match pattern "${pc.pattern}"',
      ));
    }

    _validateText(section, type, v);
    _validateFormat(section, type, v);

    // Children: membership + cardinality against subsection-types.
    final counts = <String, int>{};
    for (final child in section.children) {
      final childType = _resolveChild(child, v);
      if (childType == null) continue;
      if (!type.subsectionTypes.containsKey(childType.name)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.unknownSection,
          sectionId: child.id,
          line: child.line,
          message: 'section-type "${childType.name}" is not an allowed '
              'subsection of "${type.name}"',
        ));
        continue;
      }
      counts[childType.name] = (counts[childType.name] ?? 0) + 1;
      _validateSection(child, childType, v);
    }
    for (final sub in type.subsectionTypes.entries) {
      final count = counts[sub.key] ?? 0;
      if (count < sub.value.minCount) {
        v.add(count == 0
            ? DocSpecsViolation(
                rule: DocSpecsViolationRule.missingRequiredSection,
                sectionId: id,
                line: section.line,
                message: 'required subsection "${sub.key}" of "${type.name}" '
                    'is missing',
              )
            : DocSpecsViolation(
                rule: DocSpecsViolationRule.tooFewItems,
                sectionId: id,
                line: section.line,
                message: 'subsection "${sub.key}" occurs $count time(s), '
                    'minimum is ${sub.value.minCount}',
              ));
      }
      final max = sub.value.maxCount;
      if (max != null && count > max) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.tooManyItems,
          sectionId: id,
          line: section.line,
          message:
              'subsection "${sub.key}" occurs $count time(s), maximum is $max',
        ));
      }
    }
  }

  void _validateText(DocSpecsSection section, DocSpecsSectionType type,
      List<DocSpecsViolation> v) {
    // Form-formatted sections carry field lines, not free text.
    if (type.format != null && schema.formTypes.containsKey(type.format)) {
      return;
    }
    final text = section.text;
    if (type.textRequired && text.isEmpty) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.textRequired,
        sectionId: section.id,
        line: section.line,
        message: 'section requires body text but has none',
      ));
      return;
    }
    if (text.isEmpty) return;
    final min = type.minTextLength;
    final max = type.maxTextLength;
    if ((min != null && text.length < min) ||
        (max != null && text.length > max)) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.textLengthOut,
        sectionId: section.id,
        line: section.line,
        message: 'body text length ${text.length} is outside '
            '[${min ?? 0}, ${max ?? '∞'}]',
      ));
    }
  }

  void _validateFormat(DocSpecsSection section, DocSpecsSectionType type,
      List<DocSpecsViolation> v) {
    final format = type.format;
    if (format == null) return;
    final form = schema.formTypes[format];
    if (form != null) {
      _validateForm(section, form, v);
      return;
    }
    // A non-form format (`code`, `mermaid`, …) demands a fenced block.
    final fence = MarkdownFenceTracker();
    var sawFence = false;
    for (final line in section.bodyLines) {
      fence.feed(line);
      if (fence.inFence) sawFence = true;
    }
    if (!sawFence) {
      v.add(DocSpecsViolation(
        rule: DocSpecsViolationRule.formatMismatch,
        sectionId: section.id,
        line: section.line,
        message: 'section format "$format" demands a fenced code block, '
            'but the body contains none',
      ));
    }
  }

  static final RegExp _fieldLabel = RegExp(r'^([A-Za-z][A-Za-z0-9_]*): ?(.*)$');

  /// Parses the section body in the DocSpecs plain-text form format
  /// (`FieldName: value`, case-insensitive labels, continuation lines) and
  /// checks required fields + field pattern-checks. Text before the first
  /// recognised label is tolerated here (the binding parse reports it).
  void _validateForm(DocSpecsSection section, DocSpecsFormType form,
      List<DocSpecsViolation> v) {
    final byLower = {for (final f in form.fields) f.name.toLowerCase(): f};
    final values = <String, String>{};
    final fieldLines = <String, int>{};
    final fence = MarkdownFenceTracker();
    String? current;
    var currentLines = <String>[];

    void flush() {
      final field = current;
      if (field == null) return;
      final text = currentLines.join('\n').trim();
      if (text.isNotEmpty) values[field] = text;
      currentLines = <String>[];
    }

    for (var i = 0; i < section.bodyLines.length; i++) {
      final line = section.bodyLines[i];
      if (!fence.inFence) {
        final m = _fieldLabel.firstMatch(line);
        final field = m != null ? byLower[m.group(1)!.toLowerCase()] : null;
        if (field != null) {
          flush();
          current = field.name;
          fieldLines[field.name] = section.bodyStartLine + i;
          currentLines = [m!.group(2)!];
          fence.feed(line);
          continue;
        }
      }
      if (current != null) currentLines.add(line);
      fence.feed(line);
    }
    flush();

    for (final field in form.fields) {
      final value = values[field.name];
      if (field.required && (value == null || value.isEmpty)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.missingRequiredField,
          sectionId: section.id,
          line: section.line,
          message: 'required form field "${field.name}" of "${form.name}" '
              'is missing',
        ));
        continue;
      }
      final pc = field.patternCheck;
      if (value != null && pc != null && !pc.matches(value)) {
        v.add(DocSpecsViolation(
          rule: DocSpecsViolationRule.fieldPatternMismatch,
          sectionId: section.id,
          line: fieldLines[field.name] ?? section.line,
          message: pc.errorMessage ??
              'form field "${field.name}" does not match pattern '
                  '"${pc.pattern}"',
        ));
      }
    }
  }
}

// ---------------------------------------------------------------------------
// 4. Binding onto the SOM metadata tree (DR1 §6 capability 3)
// ---------------------------------------------------------------------------

/// Binds a DocSpecs markdown [text] onto the SOM metadata tree of [model],
/// staging values against [document]'s path grammar — the §1.7 entry point,
/// delegated to [SpecDocumentMarkdown.parse].
SpecMarkdownResult bindDocSpecsMarkdown(
        SpecModel model, SpecDocument document, String text) =>
    SpecDocumentMarkdown(model, document).parse(text);
