#!/usr/bin/env bash
# GENERATED by tom_specs_clitool generate_som — do not edit by hand.
# JDK-only fallback for `mvn package`: compile the generic runtime + the
# generated typed facade with `javac`, then package *only* the facade classes
# into build/tom_som_java_v0-<version>.jar. Build the runtime jar first
# (../tom_som_java_runtime/build_jar.sh) if you need it on the classpath.
#
# The runtime source location is read from tom_som_build.json (runtimeSourcePath,
# relative to this project) and the version from pom.xml, so the script is
# portable across checkouts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

runtime_rel="$(grep -o '"runtimeSourcePath"[[:space:]]*:[[:space:]]*"[^"]*"' \
  "$here/tom_som_build.json" | sed -E 's/.*"([^"]*)"$/\1/')"
runtime="$(cd "$here/$runtime_rel" && pwd)"
version="$(grep -o '<version>[^<]*</version>' "$here/pom.xml" | head -1 \
  | sed -E 's/<version>([^<]*)<\/version>/\1/')"

classes="$here/build/classes"
rm -rf "$here/build"
mkdir -p "$classes"

# Compile the facade; javac pulls in the runtime sources it depends on from the
# source path automatically.
javac -d "$classes" -sourcepath "$here/src:$runtime" \
  "$here"/src/tom_som_java_v0/*.java

# Package only the facade package (the runtime ships its own jar).
jar --create --file "$here/build/tom_som_java_v0-$version.jar" \
  -C "$classes" tom_som_java_v0

echo "built $here/build/tom_som_java_v0-$version.jar"
