// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';
import 'package:tom_core_codespecs/tom_core_codespecs.dart';

@CodeSpec(
  'navigation.orderWorkListRoute',
  source: ['content', 'SCECL', 'SCENPR', 'SCETR', 'AZREQ-ROLE'],
)
@DocSpec([
  DocRef('content', 'supplies the route, its path and its stable id'),
  DocRef('SCECL', 'supplies the screen category, route pattern and parent screen of the routed screen'),
  DocRef('SCENPR', 'records the page title resource and layout preset of the routed screen'),
  DocRef('SCETR', 'records the use cases, requirements and entities the routed screen serves'),
  DocRef('AZREQ-ROLE', 'supplies the roles required to access the routed screen'),
])
@CsRoute()
final TomRouteDefinition orderWorkListRoute = TomRouteDefinition(
  routeId: 'order-work-list',
  path: '/orders',
);

@CodeSpec('navigation.orderDetailRoute', source: ['content'])
@DocSpec([
  DocRef('content', 'supplies the route, its path and its stable id'),
])
@CsRoute()
final TomRouteDefinition orderDetailRoute = TomRouteDefinition(
  routeId: 'order-detail',
  path: '/orders/:orderId',
  parameters: ['orderId'],
);
