// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: the Room Booking Solution Blueprint (D00)
// Spec model version: 1.1

import 'package:tom_code_specs/tom_code_specs.dart';

/// A held period on a room.
///
/// One room, held for one period, by one member of staff.
@CodeSpec(
  'dataAccess.Booking',
  source: ['DAENT-IDEN', 'content', 'DAATT-IDEN', 'DAATT-DATA'],
)
@DocSpec([
  DocRef(
    'DAENT-IDEN',
    'supplies the entity, its table and its storage placement',
  ),
  DocRef('content', 'supplies the entity narrative'),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
])
@CsTable('bookings')
class Booking {
  /// When the booking begins, inclusive.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'starts_at', columnType: 'TIMESTAMP')
  late DateTime startsAt;

  /// When the booking ends, exclusive.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'ends_at', columnType: 'TIMESTAMP')
  late DateTime endsAt;
}
