// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: the Room Booking Solution Blueprint (D00)
// Spec model version: 1.1

import 'package:tom_code_specs/tom_code_specs.dart';

/// A meeting room that staff can book.
///
/// A bookable meeting room.
@CodeSpec(
  'dataAccess.Room',
  source: ['DAENT-IDEN', 'content', 'DAATT-IDEN', 'DAATT-DATA'],
)
@DocSpec([
  DocRef(
    'DAENT-IDEN',
    'supplies the entity, its table and its storage placement',
  ),
  DocRef('content', 'supplies the entity narrative'),
  DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
  DocRef('DAATT-DATA', 'supplies the storage type'),
])
@CsTable('rooms')
class Room {
  /// The name on the door.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'name', columnType: 'VARCHAR')
  late String name;

  /// How many people the room seats.
  @DocSpec([
    DocRef('DAATT-IDEN', 'supplies the stored attribute and its column'),
    DocRef('DAATT-DATA', 'supplies the storage type'),
  ])
  @CsColumn(column: 'capacity', columnType: 'INTEGER')
  late int capacity;
}
