# GENERATED by tom_specs_clitool generate_som — do not edit by hand.
"""Data package for the DocSpecs schemas (one folder per document root).

In an installed wheel this folder is the importable package ``tom_som_python_v0_schemas``
(mapped from `schemas/` in pyproject.toml's ``[tool.setuptools.package-dir]``);
in a source checkout it is the plain ``schemas/`` sibling of the
``tom_som_python_v0`` module. Resolve it through ``tom_som_python_v0_data`` rather than
importing it directly — the folder is data, not code.
"""
