// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';
import 'package:tom_core_codespecs/tom_core_codespecs.dart';

/// Filter the queue by lifecycle state.
@CodeSpec('layout.Scr01Sec1Layout', source: ['content', 'SSEL'])
@DocSpec([
  DocRef('content', 'supplies the section, its purpose and its type'),
  DocRef('SSEL', 'supplies the layout direction and display order'),
])
@CsLayout('SCR-01-SEC-1')
class Scr01Sec1Layout {
  @DocSpec([
    DocRef('SSEL', 'supplies the layout direction and display order'),
  ])
  final TomLayoutContainerNode base = TomLayoutContainerNode(
    nodeId: 'SCR-01-SEC-1',
    kind: TomLayoutContainerKind.row,
  );
}
