// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// The shared application error codes the Result envelope's error arm carries.
@CodeSpec('errorResult.SbpErrorCodes', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies each error code with its severity, and fixes the '
    'result-envelope shape the codes are returned in',
  ),
])
@CsError()
class SbpErrorCodes {
  @DocSpec([
    DocRef('content', 'supplies the error code and its severity'),
  ])
  @CsError(severity: CsErrorSeverity.error)
  static const CsErrorCode validationFailed = CsErrorCode('VALIDATION_FAILED');

  @DocSpec([
    DocRef('content', 'supplies the error code and its severity'),
  ])
  @CsError(severity: CsErrorSeverity.error)
  static const CsErrorCode orderAlreadyDispatched =
      CsErrorCode('ORDER_ALREADY_DISPATCHED');

  @DocSpec([
    DocRef('content', 'supplies the error code and its severity'),
  ])
  @CsError(severity: CsErrorSeverity.warning)
  static const CsErrorCode orderVersionConflict =
      CsErrorCode('ORDER_VERSION_CONFLICT');
}
