// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// The capture channel an order arrived through. Types the Order.channel attribute.
@CodeSpec('domainEnum.OrderChannel', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the enum name, its backing type and default, and each value id '
    'and description',
  ),
])
@CsEnum()
enum OrderChannel {
  /// The wholesale electronic data interchange channel.
  edi,

  /// The public REST order API.
  rest,
}
