// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: meridian_order_management.md (D00)
// Spec model version: 1.0.0+3.50e0102

import 'package:tom_code_specs/tom_code_specs.dart';

/// The order lifecycle state (Captured -> Validated -> Priced -> Reserved -> Confirmed -> Fulfilled -> Closed, with Hold and Cancelled). Types the Order.status attribute.
@CodeSpec('domainEnum.OrderStatus', source: ['content'])
@DocSpec([
  DocRef(
    'content',
    'supplies the enum name, its backing type and default, and each value id '
    'and description',
  ),
])
@CsEnum()
enum OrderStatus {
  /// Accepted from EDI or REST; lifecycle entry state.
  captured,

  /// Customer and product references verified.
  validated,

  /// Unit prices snapshotted onto every line.
  priced,

  /// Stock reserved for every line.
  reserved,

  /// Confirmed to the customer with a fulfilment window.
  confirmed,

  /// Dispatched; the public tracking page reflects it.
  fulfilled,

  /// Invoiced and complete; terminal state.
  closed,

  /// Awaiting manual review; resumes at the transition that placed it on hold.
  hold,

  /// Cancelled before dispatch, with an audited reason; terminal state.
  cancelled,
}
