# GENERATED by tom_specs_clitool generate_som — do not edit by hand.
"""Installed-location resolution for the data files shipped with
``tom_som_python_v0`` (SOM §17.3).

The distribution carries two non-code data trees: ``meta/`` (the lossless
object-model meta-data, ``spec_model.meta.json``) and ``schemas/`` (the
DocSpecs schemas, one folder per document root). In a source checkout they are
sibling folders of this module; in an installed wheel they are the importable
data packages ``tom_som_python_v0_meta_data`` and ``tom_som_python_v0_schemas``
(mapped in pyproject.toml). These helpers resolve either layout — installed
package first, checkout sibling second — so consumers never hard-code a
checkout-relative path.
"""

from __future__ import annotations

import importlib.util
import os

_HERE = os.path.dirname(os.path.abspath(__file__))


def _resolve(dir_name, package_name, probe):
    """The on-disk folder holding the ``dir_name`` data tree.

    Tries the installed data package first (a wheel install), then the
    source-checkout sibling folder. ``probe`` is a file expected inside a
    correct resolution, so an unrelated top-level package cannot shadow the
    data by name alone.
    """
    spec = importlib.util.find_spec(package_name)
    if spec is not None and spec.origin:
        root = os.path.dirname(os.path.abspath(spec.origin))
        if os.path.exists(os.path.join(root, probe)):
            return root
    sibling = os.path.join(_HERE, dir_name)
    if os.path.exists(os.path.join(sibling, probe)):
        return sibling
    raise FileNotFoundError(
        "cannot resolve the '%s' data tree of tom_som_python_v0: neither the "
        "installed package '%s' nor the checkout sibling '%s' carries '%s'"
        % (dir_name, package_name, sibling, probe))


def spec_model_meta_path():
    """Path of the shipped ``spec_model.meta.json`` (the lossless class graph)."""
    return os.path.join(
        _resolve("meta", "tom_som_python_v0_meta_data", "spec_model.meta.json"),
        "spec_model.meta.json")


def schemas_root():
    """Root folder of the shipped DocSpecs schemas (one subfolder per root)."""
    return _resolve("schemas", "tom_som_python_v0_schemas", "__init__.py")


def spec_model():
    """The whole object model this package was generated from (SOM §10.3).

    ``to_markdown`` and ``validate_document`` both take a whole ``SpecModel``,
    so this is the one call that makes them usable from an installed
    distribution::

        from tom_som_python_v0_data import spec_model

        md = to_markdown(doc, spec_model())

    Read from the shipped ``spec_model.meta.json`` rather than embedded,
    because a Python distribution can genuinely carry and locate its own data
    files — ``spec_model_meta_path`` above resolves the wheel and the checkout
    alike and raises when neither carries it. (The Dart plane embeds the same
    payload instead: an AOT binary cannot resolve its package directory, so a
    file read there returns nothing without saying so.)

    Parsed on each call. The parse is a few hundred milliseconds; holding a
    module-level cache would make the model a process-lifetime singleton that a
    caller cannot refresh, and callers that want one can bind the result.
    """
    import json

    from tom_som_runtime import SpecModel

    with open(spec_model_meta_path(), encoding="utf-8") as fh:
        return SpecModel.from_json(json.load(fh))
