# GENERATED by tom_specs_clitool generate_som — do not edit by hand.
"""Installed-location resolution for the data files shipped with
``tom_som_python_v0`` (SOM §17.3).

The distribution carries two non-code data trees: ``meta/`` (the lossless
object-model meta-data, ``spec_model.meta.json``) and ``schemas/`` (the
DocSpecs schemas, one folder per document root). In a source checkout they are
sibling folders of this module; in an installed wheel they are the importable
data packages ``tom_som_python_v0_meta_data`` and ``tom_som_python_v0_schemas``
(mapped in pyproject.toml). These helpers resolve either layout — installed
package first, checkout sibling second — so consumers never hard-code a
checkout-relative path.
"""

from __future__ import annotations

import importlib.util
import os

_HERE = os.path.dirname(os.path.abspath(__file__))


def _resolve(dir_name, package_name, probe):
    """The on-disk folder holding the ``dir_name`` data tree.

    Tries the installed data package first (a wheel install), then the
    source-checkout sibling folder. ``probe`` is a file expected inside a
    correct resolution, so an unrelated top-level package cannot shadow the
    data by name alone.
    """
    spec = importlib.util.find_spec(package_name)
    if spec is not None and spec.origin:
        root = os.path.dirname(os.path.abspath(spec.origin))
        if os.path.exists(os.path.join(root, probe)):
            return root
    sibling = os.path.join(_HERE, dir_name)
    if os.path.exists(os.path.join(sibling, probe)):
        return sibling
    raise FileNotFoundError(
        "cannot resolve the '%s' data tree of tom_som_python_v0: neither the "
        "installed package '%s' nor the checkout sibling '%s' carries '%s'"
        % (dir_name, package_name, sibling, probe))


def spec_model_meta_path():
    """Path of the shipped ``spec_model.meta.json`` (the lossless class graph)."""
    return os.path.join(
        _resolve("meta", "tom_som_python_v0_meta_data", "spec_model.meta.json"),
        "spec_model.meta.json")


def schemas_root():
    """Root folder of the shipped DocSpecs schemas (one subfolder per root)."""
    return _resolve("schemas", "tom_som_python_v0_schemas", "__init__.py")
