// GENERATED by TomSpecs Phase 4 (CodeSpecs) — do not edit.
// Source document: the Room Booking Solution Blueprint (D00)
// Spec model version: 1.1

import 'package:tom_code_specs/tom_code_specs.dart';
import 'package:tom_core_server/tom_core_server.dart';

import '../data_access/booking.dart';

/// A held period on a room.
///
/// One room, held for one period, by one member of staff.
@CodeSpec(
  'services.BookingService',
  source: ['DAENT-IDEN', 'DAENT-CLAS', 'content'],
)
@DocSpec([
  DocRef('DAENT-IDEN', 'names the aggregate root this service unit owns'),
  DocRef(
    'DAENT-CLAS',
    'supplies the aggregate and the bounded context that caps it',
  ),
  DocRef('content', 'supplies the entity narrative'),
])
@CsServiceUnit(rootAggregate: Booking, boundedContext: 'Booking')
@tomService
abstract class BookingService {
  static const List<Type> ownedEntities = [Booking];
}
