# GENERATED by tom_specs_clitool generate_som — do not edit by hand.
"""Data package for the lossless object-model meta-data (spec_model.meta.json).

In an installed wheel this folder is the importable package ``tom_som_python_v0_meta_data``
(mapped from `meta/` in pyproject.toml's ``[tool.setuptools.package-dir]``);
in a source checkout it is the plain ``meta/`` sibling of the
``tom_som_python_v0`` module. Resolve it through ``tom_som_python_v0_data`` rather than
importing it directly — the folder is data, not code.
"""
