package tom_som_runtime;

import java.util.List;

/**
 * One area's extract: the area's context plus every routed entry, in SOM
 * document order.
 */
public final class CodeSpecsExtract {
  /**
   * The version of the emitted extract artifact's on-disk shape. Bumped when the
   * YAML or Markdown layout changes in a way a reader could notice.
   *
   * <p>2: entries carry {@code headline} — the enclosing section instance's
   * headline, copy-only (stored headline, else the {@code @Headline} type
   * default, else null).
   *
   * <p>3: entries carry {@code instanceId} — the nearest enclosing list-item
   * instance's <b>stored</b> section id (the {@code <!--[…]-->} id the document
   * serializes), copy-only; null when no enclosing instance stores one.
   */
  public static final int FORMAT_VERSION = 3;

  /** The area this extract is for. */
  public final CodeSpecsArea area;

  /** The {@code codespecs_mapping.md} §4.1/§4.4.3 source the catalogue names. */
  public final String catalogSource;

  /** The section segment of the document root the entries were collected from. */
  public final String documentRoot;

  /** The area codes this area may cite (§4.4.3), for the agent's prompt. */
  public final List<String> citableParts;

  /** The §4.2 projects the area's code lands in (§4.4.3, via the slices). */
  public final List<String> projects;

  /** The routed entries, in SOM document order. */
  public final List<CodeSpecsExtractEntry> entries;

  public CodeSpecsExtract(
      CodeSpecsArea area,
      String catalogSource,
      String documentRoot,
      List<String> citableParts,
      List<String> projects,
      List<CodeSpecsExtractEntry> entries) {
    this.area = area;
    this.catalogSource = catalogSource;
    this.documentRoot = documentRoot;
    this.citableParts = citableParts;
    this.projects = projects;
    this.entries = entries;
  }

  /** The extract's file name stem — {@code CE-FM.extract}. */
  public String fileStem() {
    return area.code + ".extract";
  }

  /**
   * The artifact of record ({@code codespecs_mapping.md} §1.1.1). Scalars are
   * emitted as JSON strings, which are valid YAML 1.2 double-quoted scalars — so
   * one escaping rule, identical in all nine runtimes, covers every value a
   * specification can hold.
   */
  public String toYaml() {
    StringBuilder b = new StringBuilder();
    line(b, "# " + area.code + ".extract.yaml — generated by "
        + "spec_codespecs_extract. Do not edit.");
    line(b, "extract:");
    line(b, "  formatVersion: " + FORMAT_VERSION);
    line(b, "  catalogSource: " + yamlString(catalogSource));
    line(b, "  area:");
    line(b, "    code: " + yamlString(area.code));
    line(b, "    canonicalId: " + yamlString(area.canonicalId));
    line(b, "    part: " + yamlString(area.kindValue()));
    line(b, "    annotations: " + yamlStringList(area.annotations));
    line(b, "    builtOn: " + yamlString(area.builtOn));
    line(b, "    attributeSurface: " + yamlString(area.attributeSurface));
    line(b, "    slices: " + yamlIntList(area.slices));
    line(b, "    authoringSteps: " + yamlIntList(area.authoringSteps));
    line(b, "    projects: " + yamlStringList(projects));
    line(b, "    citableParts: " + yamlStringList(citableParts));
    line(b, "  document:");
    line(b, "    root: " + yamlString(documentRoot));
    line(b, "    entryCount: " + entries.size());
    if (entries.isEmpty()) {
      line(b, "  entries: []");
      return b.toString();
    }
    line(b, "  entries:");
    for (CodeSpecsExtractEntry e : entries) {
      line(b, "    - sectionId: " + yamlString(e.sectionId));
      line(b, "      headline: " + yamlNullableString(e.headline));
      line(b, "      instanceId: " + yamlNullableString(e.instanceId));
      line(b, "      path: " + yamlString(e.path));
      line(b, "      className: " + yamlString(e.className));
      line(b, "      fieldName: " + yamlString(e.fieldName));
      line(b, "      formField: " + yamlNullableString(e.formField));
      line(b, "      routedBy: " + yamlString(e.routedBy));
      line(b, "      routedAt: " + yamlString(e.routedAt));
      line(b, "      routingNote: " + yamlNullableString(e.routingNote));
      line(b, "      value: " + yamlString(e.value));
    }
    return b.toString();
  }

  /**
   * The rendered view. Regenerated from the YAML's own data — nothing reads the
   * Markdown as input — and exists because the agent reads it far better than it
   * reads YAML.
   */
  public String toMarkdown() {
    StringBuilder b = new StringBuilder();
    line(b, "# " + area.code + " — " + area.canonicalId);
    line(b, "");
    line(b, "Generated by `spec_codespecs_extract` from the specification "
        + "document rooted at `" + documentRoot + "`.");
    line(b, "`" + area.code + ".extract.yaml` beside this file is the artifact of "
        + "record; this is a view of it.");
    line(b, "");
    line(b, "## Area");
    line(b, "");
    line(b, "| | |");
    line(b, "|---|---|");
    line(b, "| CE code | `" + area.code + "` |");
    line(b, "| Canonical id | `" + area.canonicalId + "` |");
    line(b, "| `@CodeSpecKind` value | `" + area.kindValue() + "` |");
    line(b, "| `Cs*` annotations | " + mdCodeList(area.annotations) + " |");
    line(b, "| Built on | " + mdCell(area.builtOn) + " |");
    line(b, "| Attribute surface | " + mdCell(area.attributeSurface) + " |");
    line(b, "| Slice(s) | " + mdIntList(area.slices) + " |");
    line(b, "| Authoring step(s) | " + mdIntList(area.authoringSteps) + " |");
    line(b, "| Project(s) | " + mdCodeList(projects) + " |");
    line(b, "| May cite | " + mdCodeList(citableParts) + " |");
    line(b, "| Catalogue source | " + mdCell(catalogSource) + " |");
    line(b, "");
    line(b, "## Entries (" + entries.size() + ")");
    line(b, "");
    if (entries.isEmpty()) {
      line(b, "_No section of this document is routed to "
          + "`" + area.kindValue() + "`._");
      return b.toString();
    }
    int n = 0;
    for (CodeSpecsExtractEntry e : entries) {
      n++;
      String member =
          e.formField == null ? e.fieldName : e.fieldName + "." + e.formField;
      line(b, "### " + n + ". `" + e.sectionId + "` — `" + e.className + "." + member + "`");
      line(b, "");
      if (e.headline != null) {
        line(b, "- headline: " + mdCell(e.headline));
      }
      if (e.instanceId != null) {
        line(b, "- instanceId: `" + e.instanceId + "`");
      }
      line(b, "- path: `" + e.path + "`");
      line(b, "- routed by: `" + e.routedBy + "` declared on `" + e.routedAt + "`");
      if (e.routingNote != null) {
        line(b, "- routing note: " + mdCell(e.routingNote));
      }
      line(b, "");
      String fence = fenceFor(e.value);
      line(b, fence + " text");
      line(b, e.value);
      line(b, fence);
      line(b, "");
    }
    return b.toString();
  }

  // --- shared emission helpers ----------------------------------------------

  /** Dart's {@code StringBuffer.writeln} — the one newline every emitter uses. */
  private static void line(StringBuilder b, String text) {
    b.append(text).append('\n');
  }

  /**
   * A JSON string literal, which is also a valid YAML 1.2 double-quoted scalar.
   * Hand-written rather than delegated to a JSON library so the nine ports have
   * one rule to transcribe rather than nine encoders to hope agree.
   *
   * <p>Iterates by <b>code point</b>, not UTF-16 code unit, so a surrogate pair
   * is emitted whole exactly as the Dart reference's {@code runes} loop does.
   */
  private static String yamlString(String value) {
    StringBuilder b = new StringBuilder("\"");
    for (int i = 0; i < value.length(); ) {
      int rune = value.codePointAt(i);
      i += Character.charCount(rune);
      switch (rune) {
        case 0x22:
          b.append("\\\"");
          break;
        case 0x5C:
          b.append("\\\\");
          break;
        case 0x08:
          b.append("\\b");
          break;
        case 0x0C:
          b.append("\\f");
          break;
        case 0x0A:
          b.append("\\n");
          break;
        case 0x0D:
          b.append("\\r");
          break;
        case 0x09:
          b.append("\\t");
          break;
        default:
          if (rune < 0x20) {
            String hex = Integer.toHexString(rune);
            b.append("\\u");
            for (int pad = hex.length(); pad < 4; pad++) {
              b.append('0');
            }
            b.append(hex);
          } else {
            b.appendCodePoint(rune);
          }
      }
    }
    b.append('"');
    return b.toString();
  }

  private static String yamlNullableString(String value) {
    return value == null ? "null" : yamlString(value);
  }

  private static String yamlStringList(List<String> values) {
    StringBuilder b = new StringBuilder("[");
    for (int i = 0; i < values.size(); i++) {
      if (i > 0) {
        b.append(", ");
      }
      b.append(yamlString(values.get(i)));
    }
    return b.append(']').toString();
  }

  private static String yamlIntList(List<Integer> values) {
    StringBuilder b = new StringBuilder("[");
    for (int i = 0; i < values.size(); i++) {
      if (i > 0) {
        b.append(", ");
      }
      b.append(values.get(i).intValue());
    }
    return b.append(']').toString();
  }

  /**
   * A markdown table cell: newlines folded to a space (a cell cannot hold one)
   * and {@code |} escaped. Applied only to catalogue prose, never to a stored
   * value — values go into fenced blocks, where they stay verbatim.
   */
  private static String mdCell(String value) {
    return value.replace("\n", " ").replace("|", "\\|");
  }

  private static String mdCodeList(List<String> values) {
    if (values.isEmpty()) {
      return "—";
    }
    StringBuilder b = new StringBuilder();
    for (int i = 0; i < values.size(); i++) {
      if (i > 0) {
        b.append(", ");
      }
      b.append('`').append(values.get(i)).append('`');
    }
    return b.toString();
  }

  private static String mdIntList(List<Integer> values) {
    if (values.isEmpty()) {
      return "—";
    }
    StringBuilder b = new StringBuilder();
    for (int i = 0; i < values.size(); i++) {
      if (i > 0) {
        b.append(", ");
      }
      b.append(values.get(i).intValue());
    }
    return b.toString();
  }

  /** The shortest backtick fence that cannot be closed by {@code value}'s own content. */
  private static String fenceFor(String value) {
    int longest = 0;
    int run = 0;
    for (int i = 0; i < value.length(); i++) {
      if (value.charAt(i) == 0x60) {
        run++;
        if (run > longest) {
          longest = run;
        }
      } else {
        run = 0;
      }
    }
    int width = longest >= 3 ? longest + 1 : 3;
    StringBuilder b = new StringBuilder();
    for (int i = 0; i < width; i++) {
      b.append('`');
    }
    return b.toString();
  }
}
