/// Emits the generated Java typed object model (`tom_som_java_v0`) from a
/// resolved [SpecModel].
///
/// The generated classes are an **editing facade** over the generic
/// `tom_som_java_runtime` `SpecDocument`: every typed accessor delegates to the
/// path-keyed memory representation, so a typed mutation is visible through the
/// generic path and vice-versa (spec §3). Each document-root class performs the
/// **instantiation-time version check** (`SomFacade.checkModelVersion`) against
/// the document's authoring stamp (§2.2) and exposes its own generated model
/// version (§2.1).
///
/// This is the Java counterpart of [SomDartEmitter] / `SomPythonEmitter` — the
/// same reachability walk, the same deterministic ordering, the same field-kind
/// mapping. Java's one-public-class-per-file rule is honoured by emitting a
/// single outer class `TomSomV0` whose every generated class/enum/form-class is
/// a `public static` nested type; siblings reference each other by simple name.
///
/// The facade is generated together with its **metadata module sibling**
/// (`TomSomV0Meta.java`, emitted by [SomJavaMetaEmitter], DR24): the root
/// loaders thread the root's generated `SomMetaTree` into the runtime
/// (`SpecDocument.fromYaml(yaml, tree)` / `fromFile(path, tree)`), and the
/// dot-notation / ID-tree access surfaces of DR1 §4 replace the retired flat
/// path-constant holders.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Generates the `tom_som_java_v0` `TomSomV0.java` source for a [SpecModel].
class SomJavaEmitter {
  final SpecModel model;
  final SpecReflection _ref;

  /// The version label of the generated project (`v0`, `v1`, …); names the
  /// `tom_som_<slug>_<label>` output project. It no longer drives the reported
  /// model version — see [modelVersionString].
  final String versionLabel;

  /// The document-root type names to generate. Empty ⇒ every root in the model.
  final List<String> documentRoots;

  SomJavaEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  }) : _ref = SpecReflection(model);

  /// The model version the generated object model reports (§2.1), `major.minor`,
  /// taken from the model's own version stamp (the `tom_specs_model` project
  /// version), not the project [versionLabel] — which only names the `_vN`
  /// output project.
  String get modelVersionString => model.modelVersionString;

  /// The roots to generate, resolved against [documentRoots] (empty ⇒ all).
  List<SpecRoot> get _selectedRoots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// Generated form-class names allocated so far in the current
  /// [generateLibrary] run, used to keep them globally unique. Reset at the
  /// start of every run so output stays deterministic.
  final Set<String> _usedFormNames = {};

  /// Returns a unique form-class name for [base], appending the smallest
  /// numeric suffix (`2`, `3`, …) that is not yet taken when [base] collides.
  String _allocFormName(String base) {
    if (_usedFormNames.add(base)) return base;
    var n = 2;
    while (!_usedFormNames.add('$base$n')) {
      n++;
    }
    return '$base$n';
  }

  // Indentation: the outer class body is at 2 spaces, its nested-type members at
  // 4, and their bodies at 6.
  static const String _i1 = '  ';
  static const String _i2 = '    ';
  static const String _i3 = '      ';

  /// Builds the complete generated `TomSomV0.java` as a single source string.
  String generateLibrary() {
    _usedFormNames.clear();
    final rootTypes = _selectedRoots.map((r) => r.type).toSet();
    final reachable = _reachableClasses(rootTypes);
    final enums = _reachableEnums(reachable);
    final formClasses = <_FormClass>[];

    final classBlocks = <String>[];
    for (final name in reachable.toList()..sort()) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      classBlocks.add(_emitClass(cls,
          isRoot: rootTypes.contains(name),
          collectForm: (fc) => formClasses.add(fc)));
    }

    final buffer = StringBuffer()
      ..writeln('// GENERATED by tom_specs_clitool SomJavaEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln('package tom_som_java_v0;')
      ..writeln()
      ..writeln('import tom_som_runtime.SomEditability;')
      ..writeln('import tom_som_runtime.SomFacade;')
      ..writeln('import tom_som_runtime.SomList;')
      ..writeln('import tom_som_runtime.SomNode;')
      ..writeln('import tom_som_runtime.SomScalar;')
      ..writeln('import tom_som_runtime.SpecDocument;')
      ..writeln()
      ..writeln('/** Typed object-model facade over the generic '
          '`tom_som_runtime` document. */')
      ..writeln('public final class TomSomV0 {')
      ..writeln('${_i1}private TomSomV0() {}')
      ..writeln();

    for (final e in enums) {
      buffer
        ..write(_emitEnum(e))
        ..writeln();
    }
    for (final block in classBlocks) {
      buffer
        ..write(block)
        ..writeln();
    }
    for (final fc in formClasses..sort((a, b) => a.name.compareTo(b.name))) {
      buffer
        ..write(fc.source)
        ..writeln();
    }
    // The flat path-constant holders (former § item 11) are retired: the
    // generated dot-notation / ID-tree access surfaces in the sibling
    // `TomSomV0Meta` module (DR24) supersede them.
    buffer.writeln('}');
    return buffer.toString();
  }

  // --- reachability -------------------------------------------------------

  Set<String> _reachableClasses(Set<String> rootTypes) {
    final visited = <String>{};
    final queue = <String>[...rootTypes];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      if (!visited.add(name)) continue;
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        switch (f.kind) {
          case SpecFieldKind.complex:
          case SpecFieldKind.section:
            if (f.type != null) queue.add(f.type!);
            break;
          case SpecFieldKind.list:
            if (f.elementIsComplex && f.elementType != null) {
              queue.add(f.elementType!);
            }
            break;
          case SpecFieldKind.form:
          case SpecFieldKind.content:
          case SpecFieldKind.enumValue:
          case SpecFieldKind.scalar:
            break;
        }
      }
    }
    return visited;
  }

  /// The distinct enum types referenced by reachable classes, with their values.
  List<_EnumType> _reachableEnums(Set<String> reachable) {
    final byName = <String, _EnumType>{};
    for (final name in reachable) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        if (f.kind == SpecFieldKind.enumValue && f.enumType != null) {
          byName.putIfAbsent(
              f.enumType!, () => _EnumType(f.enumType!, f.enumValues));
        }
      }
    }
    final result = byName.values.toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    return result;
  }

  // --- emit ---------------------------------------------------------------

  String _emitEnum(_EnumType e) {
    final b = StringBuffer()
      ..writeln('$_i1// Generated enum for `${e.name}` values.')
      ..writeln('${_i1}public enum ${e.name} {');
    for (var i = 0; i < e.values.length; i++) {
      final sep = i == e.values.length - 1 ? ';' : ',';
      // The constant *identifier* may be keyword-sanitised, but the carried
      // *token* keeps the original Dart constant name byte-for-byte so parse /
      // encode round-trips through `token`, not the identifier.
      b.writeln('$_i2${_acc(e.values[i])}("${_jstr(e.values[i])}")$sep');
    }
    b
      ..writeln()
      ..writeln('${_i2}public final String token;')
      ..writeln()
      ..writeln('$_i2${e.name}(String token) {')
      ..writeln('${_i3}this.token = token;')
      ..writeln('$_i2}')
      ..writeln()
      ..writeln('$_i2// Parses a stored token into a ${e.name}, or null.')
      ..writeln('${_i2}public static ${e.name} parse(String token) {')
      ..writeln('${_i3}if (token == null || token.isEmpty()) {')
      ..writeln('$_i3  return null;')
      ..writeln('$_i3}')
      ..writeln('${_i3}for (${e.name} v : values()) {')
      ..writeln('$_i3  if (v.token.equals(token)) {')
      ..writeln('$_i3    return v;')
      ..writeln('$_i3  }')
      ..writeln('$_i3}')
      ..writeln('${_i3}return null;')
      ..writeln('$_i2}')
      ..writeln('$_i1}');
    return b.toString();
  }

  String _emitClass(
    SpecClass cls, {
    required bool isRoot,
    required void Function(_FormClass) collectForm,
  }) {
    final b = StringBuffer();
    _writeDoc(b, cls.doc, _i1);
    b.writeln('${_i1}public static final class ${cls.name} extends SomNode {');

    if (isRoot) {
      final root = model.roots.firstWhere((r) => r.type == cls.name);
      final seg = _ref.rootSegment(root);
      b
        ..writeln('$_i2// The model version this object model was generated '
            'against (§2.1).')
        ..writeln('${_i2}public static final String MODEL_VERSION = '
            '"$modelVersionString";')
        ..writeln()
        ..writeln('$_i2// Creates the typed facade over doc at the document '
            'root and verifies the')
        ..writeln("$_i2// document's authoring documentVersion is editable "
            '(§2.2).')
        ..writeln('${_i2}public ${cls.name}(SpecDocument doc, '
            'String documentVersion) {')
        ..writeln('${_i3}super(doc, "${_jstr(seg)}");')
        ..writeln('${_i3}SomFacade.checkModelVersion(MODEL_VERSION, '
            'documentVersion);')
        ..writeln('$_i2}')
        ..writeln()
        ..writeln('${_i2}public ${cls.name}(SpecDocument doc) {')
        ..writeln('${_i3}this(doc, null);')
        ..writeln('$_i2}')
        ..writeln()
        ..writeln('$_i2// Loads a *.docspecs.yaml document and returns the typed '
            'root with the')
        ..writeln("$_i2// document's authoring stamp already applied (§ item 4) "
            '— one call for')
        ..writeln('$_i2// the former decode → loadJson → thread-documentVersion '
            'sequence. The')
        ..writeln("$_i2// root's generated metadata tree is threaded into the "
            'runtime (DR22),')
        ..writeln('$_i2// keying the YAML mapping off SomMetaTree instead of '
            'the meta-JSON model.')
        ..writeln('${_i2}public static ${cls.name} loadYaml(String yaml) {')
        ..writeln('${_i3}SpecDocument doc = SpecDocument.fromYaml(yaml, '
            'TomSomV0Meta.${cls.name}MetaTree);')
        ..writeln('${_i3}return new ${cls.name}(doc, doc.modelVersion());')
        ..writeln('$_i2}')
        ..writeln()
        ..writeln('$_i2// Loads a *.docspecs.yaml document from the file at '
            'path — the file')
        ..writeln('$_i2// companion to loadYaml.')
        ..writeln('${_i2}public static ${cls.name} loadFile(String path) {')
        ..writeln('${_i3}SpecDocument doc = SpecDocument.fromFile(path, '
            'TomSomV0Meta.${cls.name}MetaTree);')
        ..writeln('${_i3}return new ${cls.name}(doc, doc.modelVersion());')
        ..writeln('$_i2}')
        ..writeln()
        ..writeln("$_i2// This object model's own model version (major.minor), "
            'per §2.1.')
        ..writeln('${_i2}public String objectModelVersion() {')
        ..writeln('${_i3}return MODEL_VERSION;')
        ..writeln('$_i2}')
        ..writeln()
        ..writeln('$_i2// Classifies whether a document authored under '
            'documentVersion is')
        ..writeln('$_i2// editable by this object model, without throwing '
            '(§ item 8) — the')
        ..writeln("$_i2// non-throwing companion to the constructor's §2.2 "
            'check, so a read-only')
        ..writeln('$_i2// viewer can branch instead of catching '
            'SomVersionError.')
        ..writeln('${_i2}public static SomEditability editabilityFor('
            'String documentVersion) {')
        ..writeln('${_i3}return SomFacade.somEditabilityFor(MODEL_VERSION, '
            'documentVersion);')
        ..writeln('$_i2}');
    } else {
      b
        ..writeln('${_i2}public ${cls.name}(SpecDocument doc, String path) {')
        ..writeln('${_i3}super(doc, path);')
        ..writeln('$_i2}');
    }

    // § item 10: a content-bearing section overrides the `SomNode.canHaveContent`
    // structural default (`false`) to `true`, so "can this section hold body
    // text?" is answerable at the type level without probing `content()`.
    if (_hasContentLeaf(cls)) {
      b
        ..writeln()
        ..writeln('$_i2@Override')
        ..writeln('${_i2}public boolean canHaveContent() {')
        ..writeln('${_i3}return true;')
        ..writeln('$_i2}');
    }

    for (final f in cls.fields) {
      b.writeln();
      _writeField(b, cls, f, collectForm);
    }
    b.writeln('$_i1}');
    return b.toString();
  }

  /// Whether [cls] declares the standard `content` text leaf — the structural
  /// signal that its generated facade carries a `content()` accessor (§ item 10).
  bool _hasContentLeaf(SpecClass cls) => cls.fields
      .any((f) => f.name == 'content' && f.kind == SpecFieldKind.content);

  void _writeField(
    StringBuffer b,
    SpecClass cls,
    SpecField f,
    void Function(_FormClass) collectForm,
  ) {
    final seg = _ref.fieldSegment(f);
    final childPath = 'path + "/${_jstr(seg)}"';
    // Java-safe accessor identifier (the path segment above is untouched).
    final acc = _acc(f.name);
    switch (f.kind) {
      case SpecFieldKind.content:
      case SpecFieldKind.scalar:
        _emitStringProperty(b, acc, childPath, f.doc);
        break;
      case SpecFieldKind.enumValue:
        if (f.enumType == null) {
          _emitStringProperty(b, acc, childPath, f.doc);
        } else {
          final et = f.enumType!;
          _writeDoc(b, f.doc, _i2);
          b
            ..writeln('${_i2}public $et $acc() {')
            ..writeln('${_i3}return $et.parse(doc.content($childPath));')
            ..writeln('$_i2}')
            ..writeln()
            ..writeln('${_i2}public void $acc($et value) {')
            ..writeln('${_i3}doc.setContent($childPath, '
                'value != null ? value.token : "");')
            ..writeln('$_i2}');
        }
        break;
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = f.type;
        _writeDoc(b, f.doc, _i2);
        if (target == null) {
          b.writeln('$_i2// (skipped: ${f.name} has no target type)');
        } else {
          b
            ..writeln('${_i2}public $target $acc() {')
            ..writeln('${_i3}return new $target(doc, $childPath);')
            ..writeln('$_i2}');
        }
        break;
      case SpecFieldKind.list:
        _writeDoc(b, f.doc, _i2);
        // A pattern-bearing list passes its `@SectionIdPattern` so the facade
        // generates section ids on `add` (AA1 criteria 3–5); a scalar/plain
        // list omits it (pattern-less, `add` ignores id args).
        final patternArg = f.sectionIdPattern != null
            ? ', "${_jstr(f.sectionIdPattern!)}"'
            : '';
        if (f.elementIsComplex && f.elementType != null) {
          final et = f.elementType!;
          b
            ..writeln('${_i2}public SomList<$et> $acc() {')
            ..writeln('${_i3}return new SomList<>(doc, $childPath, '
                '(d, p) -> new $et(d, p)$patternArg);')
            ..writeln('$_i2}');
        } else {
          b
            ..writeln('${_i2}public SomList<SomScalar> $acc() {')
            ..writeln('${_i3}return new SomList<>(doc, $childPath, '
                '(d, p) -> new SomScalar(d, p)$patternArg);')
            ..writeln('$_i2}');
        }
        break;
      case SpecFieldKind.form:
        final formName = _allocFormName('${cls.name}${_pascal(f.name)}Form');
        collectForm(_FormClass(formName, _emitFormClass(formName, f)));
        _writeDoc(b, f.doc, _i2);
        b
          ..writeln('${_i2}public $formName $acc() {')
          ..writeln('${_i3}return new $formName(doc, $childPath);')
          ..writeln('$_i2}');
        break;
    }
  }

  void _emitStringProperty(
      StringBuffer b, String name, String childPath, String? doc) {
    _writeDoc(b, doc, _i2);
    b
      ..writeln('${_i2}public String $name() {')
      ..writeln('${_i3}String v = doc.content($childPath);')
      ..writeln('${_i3}return v == null ? "" : v;')
      ..writeln('$_i2}')
      ..writeln()
      ..writeln('${_i2}public void $name(String value) {')
      ..writeln('${_i3}doc.setContent($childPath, value);')
      ..writeln('$_i2}');
  }

  /// Emits the typed **section class** for a `@Form` field (YRB2): the section's
  /// own `content` text FIRST, then one correctly-typed member per `@Form`
  /// `Field(name, Type, …)` entry, in declaration order. A member's declared
  /// scalar type (`int` → `Integer`, `double`/`num` → `Double`, `bool` →
  /// `Boolean`) becomes its parsed Java return type; any non-primitive (enums,
  /// `List`, …) falls back to `String`. Members read/write through the generic
  /// form store, so the on-disk markdown format and the conformance golden stay
  /// byte-identical.
  String _emitFormClass(String name, SpecField f) {
    final hasContentMember = f.formFields.any((ff) => ff.name == 'content');
    final b = StringBuffer()
      ..writeln('$_i1// Generated section facade for the `${f.name}` @Form '
          'section: its own content')
      ..writeln('$_i1// text followed by one typed member per form field.')
      ..writeln('${_i1}public static final class $name extends SomNode {')
      ..writeln('${_i2}public $name(SpecDocument doc, String path) {')
      ..writeln('${_i3}super(doc, path);')
      ..writeln('$_i2}')
      ..writeln()
      ..writeln('$_i2@Override')
      ..writeln('${_i2}public boolean canHaveContent() {')
      ..writeln('${_i3}return true;')
      ..writeln('$_i2}');
    if (!hasContentMember) {
      b
        ..writeln()
        ..writeln('${_i2}public String content() {')
        ..writeln('${_i3}String v = doc.content(path);')
        ..writeln('${_i3}return v == null ? "" : v;')
        ..writeln('$_i2}')
        ..writeln()
        ..writeln('${_i2}public void content(String value) {')
        ..writeln('${_i3}doc.setContent(path, value);')
        ..writeln('$_i2}');
    }
    for (final ff in f.formFields) {
      _writeFormMember(b, ff);
    }
    b.writeln('$_i1}');
    return b.toString();
  }

  /// Emits a single typed `@Form` member accessor pair backed by the generic
  /// form store, so the on-disk format and the generic reading are unchanged;
  /// only the Java type mirrors the declared form-field type.
  void _writeFormMember(StringBuffer b, FormFieldSpec ff) {
    final field = '"${_jstr(ff.name)}"';
    // The form-field key string ($field) is preserved; only the Java accessor
    // identifier is keyword-sanitised.
    final acc = _acc(ff.name);
    b.writeln();
    switch (_scalarType(ff.type)) {
      case 'int':
        b
          ..writeln('${_i2}public Integer $acc() {')
          ..writeln('${_i3}String v = doc.formField(path, $field);')
          ..writeln('${_i3}if (v == null || v.isEmpty()) return null;')
          ..writeln('${_i3}try { return Integer.parseInt(v); } '
              'catch (NumberFormatException e) { return null; }')
          ..writeln('$_i2}')
          ..writeln()
          ..writeln('${_i2}public void $acc(Integer value) {')
          ..writeln('${_i3}doc.setFormField(path, $field, '
              'value == null ? "" : String.valueOf(value));')
          ..writeln('$_i2}');
      case 'double':
      case 'num':
        b
          ..writeln('${_i2}public Double $acc() {')
          ..writeln('${_i3}String v = doc.formField(path, $field);')
          ..writeln('${_i3}if (v == null || v.isEmpty()) return null;')
          ..writeln('${_i3}try { return Double.parseDouble(v); } '
              'catch (NumberFormatException e) { return null; }')
          ..writeln('$_i2}')
          ..writeln()
          ..writeln('${_i2}public void $acc(Double value) {')
          ..writeln('${_i3}doc.setFormField(path, $field, '
              'value == null ? "" : String.valueOf(value));')
          ..writeln('$_i2}');
      case 'bool':
        b
          ..writeln('${_i2}public Boolean $acc() {')
          ..writeln('${_i3}String v = doc.formField(path, $field);')
          ..writeln('${_i3}if (v == null) return null;')
          ..writeln('${_i3}return Boolean.valueOf("true".equals(v));')
          ..writeln('$_i2}')
          ..writeln()
          ..writeln('${_i2}public void $acc(Boolean value) {')
          ..writeln('${_i3}doc.setFormField(path, $field, '
              'value == null ? "" : (value ? "true" : "false"));')
          ..writeln('$_i2}');
      default:
        b
          ..writeln('${_i2}public String $acc() {')
          ..writeln('${_i3}String v = doc.formField(path, $field);')
          ..writeln('${_i3}return v == null ? "" : v;')
          ..writeln('$_i2}')
          ..writeln()
          ..writeln('${_i2}public void $acc(String value) {')
          ..writeln('${_i3}doc.setFormField(path, $field, value);')
          ..writeln('$_i2}');
    }
  }

  /// Maps a `@Form` field's declared type name to the primitive scalar kind the
  /// facade should expose, or `'String'` for any non-primitive (enums, `List`,
  /// unresolved types) so the generated code always round-trips as text.
  static String _scalarType(String typeName) {
    final base = typeName.endsWith('?')
        ? typeName.substring(0, typeName.length - 1)
        : typeName;
    switch (base) {
      case 'int':
      case 'double':
      case 'num':
      case 'bool':
        return base;
      default:
        return 'String';
    }
  }

  /// Emits a doc block as `//` line comments at [indent]. Java comments need no
  /// escaping (unlike Javadoc, a stray `*/` cannot terminate a line comment).
  void _writeDoc(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    for (final line in doc.trimRight().split('\n')) {
      final text = line.trimRight();
      b.writeln(text.isEmpty ? '$indent//' : '$indent// $text');
    }
  }

  /// Escapes a value for a double-quoted Java string literal.
  String _jstr(String s) => s
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r')
      .replaceAll('\t', '\\t');

  /// The Java reserved keywords (plus the boolean/null literals). Dart field and
  /// enum-constant names are otherwise valid Java identifiers, so these are the
  /// only names that need rewriting before they can appear as a method or enum
  /// constant.
  static const Set<String> _javaKeywords = {
    'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char',
    'class', 'const', 'continue', 'default', 'do', 'double', 'else', 'enum',
    'extends', 'final', 'finally', 'float', 'for', 'goto', 'if', 'implements',
    'import', 'instanceof', 'int', 'interface', 'long', 'native', 'new',
    'package', 'private', 'protected', 'public', 'return', 'short', 'static',
    'strictfp', 'super', 'switch', 'synchronized', 'this', 'throw', 'throws',
    'transient', 'try', 'void', 'volatile', 'while',
    'true', 'false', 'null',
  };

  /// Returns a Java-safe identifier for [name].
  ///
  /// A Dart identifier that happens to be a Java keyword (`for`, `class`,
  /// `new`, …) cannot be emitted as a method name or enum constant, so a
  /// trailing-underscore convention is applied (`for` → `for_`). Only the
  /// emitted Java identifier changes — the document path segment and the stored
  /// enum token are derived independently and stay byte-identical to the Dart
  /// facade, so cross-language documents remain compatible.
  String _acc(String name) => _javaKeywords.contains(name) ? '${name}_' : name;

  String _pascal(String s) {
    final parts = s.split(RegExp(r'[_\s]+')).where((p) => p.isNotEmpty);
    return parts.map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }
}

class _EnumType {
  final String name;
  final List<String> values;
  _EnumType(this.name, this.values);
}

class _FormClass {
  final String name;
  final String source;
  _FormClass(this.name, this.source);
}
