/// Emits the Dart **DocSpecs schema accessor** library,
/// `lib/<package>_schemas.dart`.
///
/// ## The gap this closes
///
/// The generator writes one DocSpecs schema per `@Document` root under
/// `schemas/<id>/<id>.<major>.0.docspecs-schema.yaml`. Those are *data files*,
/// so a consumer of the published package had to resolve the package's own
/// directory layout by hand:
///
/// ```dart
/// final lib = await Isolate.resolvePackageUri(
///     Uri.parse('package:tom_som_dart_v0/tom_som_dart_v0.dart'));
/// final text = File.fromUri(lib!.resolve(
///     'schemas/solution-blueprint/'
///     'solution-blueprint.1.0.docspecs-schema.yaml')).readAsStringSync();
/// final schema = DocSpecsSchema.fromYamlText(text);
/// ```
///
/// That is the same five lines `SomDartModelEmitter` was written to delete, in
/// three more places — and it fails the same way. `Isolate.resolvePackageUri`
/// **returns `null` once no `.dart_tool/package_config.json` is reachable**,
/// which is the normal state of a shipped AOT binary, and a `null` resolution
/// reads no file without saying so.
///
/// ## One library, not fourteen
///
/// The fourteen schemas are 3.7 MB of YAML together, the largest of them 1.65 MB.
/// A library per root would let a consumer pay only for the roots it opens, and
/// the sample evidence says consumers use one or three at a time — so that is a
/// real saving, not a theoretical one.
///
/// It is still one library, for now, because Dart cannot tree-shake individual
/// entries out of a `const Map` either way: the choice is between fourteen
/// imports a consumer has to know about and one that costs 3.7 MB when opted
/// into. The single library matches [SomDartModelEmitter]'s shape, which is
/// already the documented convention, and splitting it later is a mechanical
/// change to this one file rather than a change consumers have to follow.
///
/// ## Why it is its own library, not part of the facade
///
/// Same reason as the model accessor: the facade re-exports the metadata
/// library, so anything added there is compiled by every consumer. This library
/// is **not** exported — a consumer opts in with a second import — and the
/// accessor parses on first use, so importing it costs nothing until a schema
/// is actually read.
///
/// The shipped `schemas/` tree stays exactly as it was. It is the interchange
/// artifact the other eight language planes and any external validator read;
/// this library adds an API beside it rather than replacing it.
library;

import 'package:tom_doc_specs/tom_doc_specs.dart';

import 'docspecs_schema_generator.dart';

/// Emits `lib/<package>_schemas.dart` for one generation run.
class SomDartSchemasEmitter {
  /// The generated schemas, keyed as [DocSpecsSchemaGenerator.generateAll]
  /// returns them — the same objects written to the `schemas/` tree in the same
  /// run, so the embedded text and the shipped files cannot disagree.
  final Map<String, DocSpecSchema> schemas;

  /// The generated package's name, used for the library's own file name and in
  /// the doc comments that tell a reader how to import it.
  final String packageName;

  /// The `v0` / `v1` label of the project, used only in the generated banner.
  final String versionLabel;

  /// [schemas] and [packageName] are required; [versionLabel] defaults to the
  /// whole-model `v0` shape the CLI uses.
  SomDartSchemasEmitter(
    this.schemas, {
    required this.packageName,
    this.versionLabel = 'v0',
  });

  /// Schema id → the exact YAML text written to the `schemas/` tree.
  ///
  /// Sorted by id so the emitted library is stable across runs: an unordered
  /// map would reorder 3.7 MB of literals on any change to the model's class
  /// iteration order and make every diff unreadable.
  Map<String, String> get texts {
    final byId = {for (final s in schemas.values) s.id: s};
    final ids = byId.keys.toList()..sort();
    return {
      for (final id in ids) id: DocSpecsSchemaGenerator.toYamlString(byId[id]!),
    };
  }

  /// The Dart source of the schema-accessor library.
  String generateLibrary() {
    final entries = texts;
    final total = entries.values.fold<int>(0, (a, b) => a + b.length);
    final b = StringBuffer();
    b.writeln(
      '// GENERATED by tom_specs_clitool SomDartSchemasEmitter '
      '($versionLabel) — do not edit by hand.',
    );
    b.writeln('//');
    b.writeln('// The DocSpecs schema accessor (SOM §10.3). Each schema is');
    b.writeln('// embedded rather than read from the shipped `schemas/` tree');
    b.writeln('// because a package-relative file read cannot survive AOT');
    b.writeln('// compilation: `Isolate.resolvePackageUri` returns null once');
    b.writeln('// no package_config.json is reachable, and reads nothing');
    b.writeln('// without saying so.');
    b.writeln('// ignore_for_file: type=lint, document_ignores');
    b.writeln('library;');
    b.writeln();
    b.writeln(
      "import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';",
    );
    b.writeln();
    b.writeln('/// The generated DocSpecs schema for the document root [id].');
    b.writeln('///');
    b.writeln('/// [id] is the schema slug, which is the `@Document` name');
    b.writeln('/// lower-cased and hyphenated — `solution-blueprint`,');
    b.writeln('/// `information-model`, … — and is the same string that names');
    b.writeln("/// the schema's directory in the shipped `schemas/` tree.");
    b.writeln('///');
    b.writeln('/// Parsed on first use and cached per id, so importing this');
    b.writeln('/// library costs nothing until a schema is actually read.');
    b.writeln('///');
    b.writeln('/// ```dart');
    b.writeln("/// import 'package:$packageName/${packageName}_schemas.dart';");
    b.writeln('///');
    b.writeln("/// final schema = somDocSpecsSchema('solution-blueprint');");
    b.writeln('/// final violations = DocSpecsValidator(schema)');
    b.writeln('///     .validateMarkdown(markdown);');
    b.writeln('/// ```');
    b.writeln('///');
    b.writeln('/// Throws [ArgumentError] naming every known id when [id] is');
    b.writeln('/// not one of them — a typo must not read as an empty schema,');
    b.writeln('/// which would validate every document clean.');
    b.writeln('DocSpecsSchema somDocSpecsSchema(String id) {');
    b.writeln('  final cached = _cache[id];');
    b.writeln('  if (cached != null) return cached;');
    b.writeln('  final text = somDocSpecsSchemaYaml[id];');
    b.writeln('  if (text == null) {');
    b.writeln('    throw ArgumentError.value(');
    b.writeln("        id, 'id', 'unknown schema; known ids are '");
    b.writeln("        '\${somDocSpecsSchemaIds.join(', ')}');");
    b.writeln('  }');
    b.writeln('  return _cache[id] = DocSpecsSchema.fromYamlText(text);');
    b.writeln('}');
    b.writeln();
    b.writeln('final Map<String, DocSpecsSchema> _cache = {};');
    b.writeln();
    b.writeln('/// Every schema id this package carries, sorted.');
    b.writeln('///');
    b.writeln('/// The set is closed and generated: it is exactly the');
    b.writeln("/// `@Document` roots of the model this package was generated");
    b.writeln('/// from.');
    b.writeln('List<String> get somDocSpecsSchemaIds =>');
    b.writeln('    somDocSpecsSchemaYaml.keys.toList();');
    b.writeln();
    b.writeln('/// The embedded schemas, as the exact YAML of the shipped');
    b.writeln('/// `schemas/<id>/<id>.<major>.0.docspecs-schema.yaml` files.');
    b.writeln('///');
    b.writeln('/// Exposed because a consumer that wants to hand a schema to');
    b.writeln('/// something other than [DocSpecsSchema] — a different');
    b.writeln(
      '/// language runtime over a pipe, a file it writes out — should',
    );
    b.writeln('/// not have to re-encode a parsed schema to get it back.');
    b.writeln('///');
    b.writeln(
      '/// ${entries.length} schemas, ${_mb(total)} MB of YAML together.',
    );
    b.writeln('const Map<String, String> somDocSpecsSchemaYaml = {');
    for (final e in entries.entries) {
      b.writeln('  ${_literal(e.key)}: ${_literal(e.value)},');
    }
    b.writeln('};');
    return b.toString();
  }

  static String _mb(int chars) => (chars / 1e6).toStringAsFixed(2);

  /// A single-quoted Dart string literal for [s].
  ///
  /// Escapes backslash first — otherwise it would double the escapes it just
  /// introduced — then the quote and `$`. An unescaped `$` in a non-raw literal
  /// starts an interpolation, which is a compile error at best and a silent
  /// substitution at worst, and schema YAML carries `$` in its own keys.
  static String _literal(String s) {
    final e = s
        .replaceAll(r'\', r'\\')
        .replaceAll("'", r"\'")
        .replaceAll(r'$', r'\$')
        .replaceAll('\n', r'\n');
    return "'$e'";
  }
}
