/// Emits the generated Dart typed object model (`tom_som_dart_v0`) from a
/// resolved [SpecModel].
///
/// The generated classes are an **editing facade** over the generic
/// `tom_som_dart_runtime` [SpecDocument]: every typed accessor delegates to the
/// path-keyed memory representation, so a typed mutation is visible through the
/// generic path and vice-versa (spec §3). Each document-root class performs the
/// **instantiation-time version check** ([checkSomModelVersion]) against the
/// document's authoring stamp (§2.2) and exposes its own generated model version
/// (§2.1).
///
/// The emitter walks the model from the selected roots, collecting every
/// reachable class (followed through complex/section fields and complex list
/// elements) and every enum type, then emits a single deterministic library.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Generates the `tom_som_dart_v0` library source for a [SpecModel].
class SomDartEmitter {
  final SpecModel model;
  final SpecReflection _ref;

  /// The version label of the generated project (`v0`, `v1`, …); names the
  /// `tom_som_<slug>_<label>` output project. It no longer drives the reported
  /// model version — see [modelVersionString].
  final String versionLabel;

  /// The document-root type names to generate. Empty ⇒ every root in the model.
  final List<String> documentRoots;

  SomDartEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  }) : _ref = SpecReflection(model);

  /// The model version the generated object model reports (§2.1), `major.minor`,
  /// taken from the model's own version stamp (the `tom_specs_model` project
  /// version), not the project [versionLabel] — which only names the `_vN`
  /// output project.
  String get modelVersionString => model.modelVersionString;

  /// The roots to generate, resolved against [documentRoots] (empty ⇒ all).
  List<SpecRoot> get _selectedRoots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// Generated form-class names allocated so far in the current
  /// [generateLibrary] run, used to keep them globally unique (two distinct
  /// `(class, form-field)` pairs can derive the same base name). Reset at the
  /// start of every run so output stays deterministic.
  final Set<String> _usedFormNames = {};

  /// Returns a unique form-class name for [base], appending the smallest
  /// numeric suffix (`2`, `3`, …) that is not yet taken when [base] collides.
  String _allocFormName(String base) {
    if (_usedFormNames.add(base)) return base;
    var n = 2;
    while (!_usedFormNames.add('$base$n')) {
      n++;
    }
    return '$base$n';
  }

  /// Builds the complete generated library as a single source string.
  String generateLibrary() {
    _usedFormNames.clear();
    final rootTypes = _selectedRoots.map((r) => r.type).toSet();
    final reachable = _reachableClasses(rootTypes);
    final enums = _reachableEnums(reachable);
    final formClasses = <_FormClass>[];

    final classBlocks = <String>[];
    for (final name in reachable.toList()..sort()) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      classBlocks.add(_emitClass(cls, isRoot: rootTypes.contains(name),
          collectForm: (fc) => formClasses.add(fc)));
    }

    final buffer = StringBuffer()
      ..writeln('// GENERATED by tom_specs_clitool SomDartEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln('// ignore_for_file: type=lint, unused_import, '
          'document_ignores')
      ..writeln()
      ..writeln(
          "import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';")
      ..writeln()
      // DR8: the generated metadata library (populated SomMetaTrees + the
      // dot-notation and ID-tree access surfaces) replaces the retired flat
      // path-constant holders. Imported here too — the root `loadYaml` /
      // `loadFile` statics pass the root's populated tree to the codec.
      ..writeln("import 'tom_som_dart_${versionLabel}_meta.dart';")
      ..writeln("export 'tom_som_dart_${versionLabel}_meta.dart';")
      ..writeln();

    for (final e in enums) {
      buffer
        ..write(_emitEnum(e))
        ..writeln();
    }
    for (final block in classBlocks) {
      buffer
        ..write(block)
        ..writeln();
    }
    for (final fc in formClasses..sort((a, b) => a.name.compareTo(b.name))) {
      buffer
        ..write(fc.source)
        ..writeln();
    }
    // DR8: the former per-root `<Code>Paths` constant holders are retired
    // (DR1 §4) — the dot-notation and ID-tree surfaces in the exported meta
    // library carry the same paths as discoverable symbols.
    return buffer.toString();
  }

  // --- reachability -------------------------------------------------------

  Set<String> _reachableClasses(Set<String> rootTypes) {
    final visited = <String>{};
    final queue = <String>[...rootTypes];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      if (!visited.add(name)) continue;
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        switch (f.kind) {
          case SpecFieldKind.complex:
          case SpecFieldKind.section:
            if (f.type != null) queue.add(f.type!);
            break;
          case SpecFieldKind.list:
            if (f.elementIsComplex && f.elementType != null) {
              queue.add(f.elementType!);
            }
            break;
          case SpecFieldKind.form:
          case SpecFieldKind.content:
          case SpecFieldKind.enumValue:
          case SpecFieldKind.scalar:
            break;
        }
      }
    }
    return visited;
  }

  /// The distinct enum types referenced by reachable classes, with their
  /// values — both `enum`-kind leaves and enum-typed `@Form` fields (YRD7,
  /// which carry their constant names in [FormFieldSpec.enumValues]).
  List<_EnumType> _reachableEnums(Set<String> reachable) {
    final byName = <String, _EnumType>{};
    for (final name in reachable) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        if (f.kind == SpecFieldKind.enumValue && f.enumType != null) {
          byName.putIfAbsent(
              f.enumType!, () => _EnumType(f.enumType!, f.enumValues));
        }
        if (f.kind == SpecFieldKind.form) {
          for (final ff in f.formFields) {
            if (ff.enumValues.isNotEmpty) {
              final et = _scalarBaseName(ff.type);
              byName.putIfAbsent(et, () => _EnumType(et, ff.enumValues));
            }
          }
        }
      }
    }
    final result = byName.values.toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    return result;
  }

  // --- emit ---------------------------------------------------------------

  String _emitEnum(_EnumType e) {
    final b = StringBuffer()
      ..writeln('/// Generated enum for `${e.name}` values.')
      ..writeln('enum ${e.name} {');
    for (var i = 0; i < e.values.length; i++) {
      final sep = i == e.values.length - 1 ? ';' : ',';
      b.writeln('  ${e.values[i]}$sep');
    }
    b
      ..writeln('}')
      ..writeln()
      ..writeln('/// Parses a stored token into a [${e.name}], or `null`.')
      ..writeln('${e.name}? _parse${e.name}(String? token) {')
      ..writeln('  if (token == null || token.isEmpty) return null;')
      ..writeln('  for (final v in ${e.name}.values) {')
      ..writeln('    if (v.name == token) return v;')
      ..writeln('  }')
      ..writeln('  return null;')
      ..writeln('}');
    return b.toString();
  }

  String _emitClass(
    SpecClass cls, {
    required bool isRoot,
    required void Function(_FormClass) collectForm,
  }) {
    final b = StringBuffer();
    _writeDoc(b, cls.doc, '');
    b.writeln('class ${cls.name} extends SomNode {');

    if (isRoot) {
      final root = model.roots.firstWhere((r) => r.type == cls.name);
      final seg = _ref.rootSegment(root);
      b
        ..writeln('  /// The model version this object model was generated '
            'against (§2.1).')
        ..writeln("  static const String modelVersion = "
            "'$modelVersionString';")
        ..writeln()
        ..writeln('  /// Creates the typed facade over [doc] at the document '
            'root and verifies')
        ..writeln('  /// the document\'s authoring [documentVersion] is '
            'editable (§2.2).')
        ..writeln('  ${cls.name}(SpecDocument doc, {String? documentVersion})')
        ..writeln("      : super(doc, '${_escape(seg)}') {")
        ..writeln('    checkSomModelVersion(modelVersion, documentVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  /// Loads a `*.docspecs.yaml` document and returns the typed '
            'root with the')
        ..writeln('  /// document\'s authoring stamp already applied (§ item 4) '
            '— one call for')
        ..writeln('  /// the former decode → loadJson → thread-`documentVersion` '
            'sequence.')
        ..writeln('  static ${cls.name} loadYaml(String yaml) {')
        ..writeln('    final doc = SpecDocument.fromYaml(yaml, '
            '${_camelType(cls.name)}MetaTree);')
        ..writeln('    return ${cls.name}(doc, '
            'documentVersion: doc.modelVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  /// Loads a `*.docspecs.yaml` document from the file at '
            '[path] — the file')
        ..writeln('  /// companion to [loadYaml].')
        ..writeln('  static ${cls.name} loadFile(String path) {')
        ..writeln('    final doc = SpecDocument.fromFile(path, '
            '${_camelType(cls.name)}MetaTree);')
        ..writeln('    return ${cls.name}(doc, '
            'documentVersion: doc.modelVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  /// This object model\'s own model version (`major.minor`),'
            ' per spec §2.1.')
        ..writeln('  String get objectModelVersion => modelVersion;')
        ..writeln()
        ..writeln('  /// Classifies whether a document authored under '
            '[documentVersion] is')
        ..writeln('  /// editable by this object model, **without throwing** '
            '(§ item 8) — the')
        ..writeln('  /// non-throwing companion to the constructor\'s §2.2 '
            'check, so a read-only')
        ..writeln('  /// viewer can branch instead of catching '
            '[SomVersionException].')
        ..writeln('  static SomEditability editabilityFor(String? '
            'documentVersion) =>')
        ..writeln('      somEditabilityFor(modelVersion, documentVersion);');
    } else {
      b.writeln('  ${cls.name}(super.doc, super.path);');
    }

    // § item 10: a content-bearing section overrides the `SomNode.canHaveContent`
    // structural default (`false`) to `true`, so "can this section hold body
    // text?" is answerable at the type level without probing `.content`.
    if (_hasContentLeaf(cls)) {
      b
        ..writeln()
        ..writeln('  @override')
        ..writeln('  bool get canHaveContent => true;');
    }

    for (final f in cls.fields) {
      b.writeln();
      _writeField(b, cls, f, collectForm);
    }
    b.writeln('}');
    return b.toString();
  }

  /// Whether [cls] declares the standard `content` text leaf — the structural
  /// signal that its generated facade carries a `.content` accessor (§ item 10).
  bool _hasContentLeaf(SpecClass cls) => cls.fields
      .any((f) => f.name == 'content' && f.kind == SpecFieldKind.content);

  void _writeField(
    StringBuffer b,
    SpecClass cls,
    SpecField f,
    void Function(_FormClass) collectForm,
  ) {
    final seg = _ref.fieldSegment(f);
    final childPath = "'\$path/${_escape(seg)}'";
    _writeDoc(b, f.doc, '  ');
    switch (f.kind) {
      case SpecFieldKind.content:
      case SpecFieldKind.scalar:
        b
          ..writeln('  String get ${f.name} => doc.content($childPath) ?? \'\';')
          ..writeln(
              '  set ${f.name}(String value) => doc.setContent($childPath, value);');
        break;
      case SpecFieldKind.enumValue:
        if (f.enumType == null) {
          // No enum type name available — fall back to a string leaf.
          b
            ..writeln(
                '  String get ${f.name} => doc.content($childPath) ?? \'\';')
            ..writeln(
                '  set ${f.name}(String value) => doc.setContent($childPath, value);');
        } else {
          final et = f.enumType!;
          b
            ..writeln(
                '  $et? get ${f.name} => _parse$et(doc.content($childPath));')
            ..writeln('  set ${f.name}($et? value) => '
                'doc.setContent($childPath, value?.name ?? \'\');');
        }
        break;
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = f.type;
        if (target == null) {
          b.writeln('  // (skipped: ${f.name} has no target type)');
        } else {
          b.writeln('  $target get ${f.name} => $target(doc, $childPath);');
        }
        break;
      case SpecFieldKind.list:
        final patternArg = f.sectionIdPattern != null
            ? ", pattern: '${_escape(f.sectionIdPattern!)}'"
            : '';
        if (f.elementIsComplex && f.elementType != null) {
          final et = f.elementType!;
          b.writeln('  SomList<$et> get ${f.name} => '
              'SomList<$et>(doc, $childPath, (d, p) => $et(d, p)$patternArg);');
        } else {
          b.writeln('  SomList<SomScalar> get ${f.name} => '
              'SomList<SomScalar>(doc, $childPath, (d, p) => SomScalar(d, p)'
              '$patternArg);');
        }
        break;
      case SpecFieldKind.form:
        final formName = _allocFormName('${cls.name}${_pascal(f.name)}Form');
        collectForm(_FormClass(formName, _emitFormClass(formName, f)));
        b.writeln('  $formName get ${f.name} => $formName(doc, $childPath);');
        break;
    }
  }

  /// Emits the typed **section class** for a `@Form` field (YRB2): the
  /// section's own `content` text FIRST, then one correctly-typed member per
  /// `@Form` `Field(name, Type, …)` entry, in declaration order. The `@Form`
  /// members are the only place typed non-String scalars legitimately appear;
  /// their static type mirrors the declared field type (`String`/`int`/`bool`/
  /// `double`/`num`). Non-primitive member types (enums, `List`, …) fall back
  /// to `String` so the generated facade always compiles; the underlying value
  /// store and markdown format are unchanged (the members read/write through
  /// the generic `formField` store, so the golden reading is byte-identical).
  String _emitFormClass(String name, SpecField f) {
    final hasContentMember = f.formFields.any((ff) => ff.name == 'content');
    final b = StringBuffer()
      ..writeln('/// Generated section facade for the `${f.name}` `@Form` '
          'section:')
      ..writeln('/// its own `content` text followed by one typed member per '
          'form field.')
      ..writeln('class $name extends SomNode {')
      ..writeln('  $name(super.doc, super.path);')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  bool get canHaveContent => true;');
    if (!hasContentMember) {
      b
        ..writeln()
        ..writeln('  /// The section\'s own free-text content, before the form '
            'fields.')
        ..writeln('  String get content => doc.content(path) ?? \'\';')
        ..writeln('  set content(String value) => '
            'doc.setContent(path, value);');
    }
    for (final ff in f.formFields) {
      b.writeln();
      _writeFormMember(b, ff);
    }
    b.writeln('}');
    return b.toString();
  }

  /// Emits a single typed `@Form` member accessor. The value is stored through
  /// the generic form store (`formField`/`setFormField`), so the on-disk format
  /// and the generic reading are unchanged; only the facade's static type
  /// mirrors the declared form-field type.
  void _writeFormMember(StringBuffer b, FormFieldSpec ff) {
    final n = ff.name;
    final key = _escape(n);
    // YRD7: enum-typed form fields expose the generated enum natively; the
    // stored value stays the constant name (`_parse<Enum>` / `.name`).
    if (ff.enumValues.isNotEmpty) {
      final et = _scalarBaseName(ff.type);
      b
        ..writeln('  $et? get $n => '
            '_parse$et(doc.formField(path, \'$key\'));')
        ..writeln('  set $n($et? value) => '
            'doc.setFormField(path, \'$key\', value?.name ?? \'\');');
      return;
    }
    // YRD7: primitive typed members convert through the SAME shared boundary
    // helpers the generic SpecEditor uses (spec_typed_values.dart), so the
    // facade is provably a thin layer over the generic API.
    switch (_scalarType(ff.type)) {
      case 'int':
        b
          ..writeln('  int? get $n => '
              'somParseInt(doc.formField(path, \'$key\'));')
          ..writeln('  set $n(int? value) => '
              'doc.setFormField(path, \'$key\', somFormatInt(value));');
      case 'double':
        b
          ..writeln('  double? get $n => '
              'somParseDouble(doc.formField(path, \'$key\'));')
          ..writeln('  set $n(double? value) => '
              'doc.setFormField(path, \'$key\', somFormatDouble(value));');
      case 'num':
        b
          ..writeln('  num? get $n => '
              'somParseNum(doc.formField(path, \'$key\'));')
          ..writeln('  set $n(num? value) => '
              'doc.setFormField(path, \'$key\', somFormatNum(value));');
      case 'bool':
        b
          ..writeln('  bool? get $n => '
              'somParseBool(doc.formField(path, \'$key\'));')
          ..writeln('  set $n(bool? value) => '
              'doc.setFormField(path, \'$key\', somFormatBool(value));');
      default:
        b
          ..writeln('  String get $n => '
              'doc.formField(path, \'$key\') ?? \'\';')
          ..writeln('  set $n(String value) => '
              'doc.setFormField(path, \'$key\', value);');
    }
  }

  /// Maps a `@Form` field's declared type name to the primitive scalar kind the
  /// facade should expose, or `'String'` for any non-primitive (`List`,
  /// unresolved types) so the generated code always compiles. Enum-typed form
  /// fields are handled before this call (they carry `enumValues`).
  static String _scalarType(String typeName) {
    final base = _scalarBaseName(typeName);
    switch (base) {
      case 'int':
      case 'double':
      case 'num':
      case 'bool':
        return base;
      default:
        return 'String';
    }
  }

  /// The declared type name with a trailing `?` stripped.
  static String _scalarBaseName(String typeName) => typeName.endsWith('?')
      ? typeName.substring(0, typeName.length - 1)
      : typeName;

  void _writeDoc(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    for (final line in doc.trimRight().split('\n')) {
      b.writeln('$indent/// ${line.trimRight()}');
    }
  }

  String _escape(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\$', '\\\$');

  /// LowerCamel of a root type name — the generated meta library names its
  /// per-root `SomMetaTree` global `<camelType>MetaTree` (SomDartMetaEmitter).
  String _camelType(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  String _pascal(String s) {
    final parts = s.split(RegExp(r'[_\s]+')).where((p) => p.isNotEmpty);
    return parts
        .map((p) => p[0].toUpperCase() + p.substring(1))
        .join();
  }
}

class _EnumType {
  final String name;
  final List<String> values;
  _EnumType(this.name, this.values);
}

class _FormClass {
  final String name;
  final String source;
  _FormClass(this.name, this.source);
}
