/// Emits the generated Dart typed object model (`tom_som_dart_v0`) from a
/// resolved [SpecModel].
///
/// The generated classes are an **editing facade** over the generic
/// `tom_som_dart_runtime` [SpecDocument]: every typed accessor delegates to the
/// path-keyed memory representation, so a typed mutation is visible through the
/// generic path and vice-versa (spec §3). Each document-root class performs the
/// **instantiation-time version check** ([checkSomModelVersion]) against the
/// document's authoring stamp (§2.2) and exposes its own generated model version
/// (§2.1).
///
/// The emitter walks the model from the selected roots, collecting every
/// reachable class (followed through complex/section fields and complex list
/// elements) and every enum type, then emits a single deterministic library.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Generates the `tom_som_dart_v0` library source for a [SpecModel].
class SomDartEmitter {
  final SpecModel model;
  final SpecReflection _ref;

  /// The version label of the generated project (`v0`, `v1`, …). The major
  /// version is parsed from it; see [modelVersionString].
  final String versionLabel;

  /// The document-root type names to generate. Empty ⇒ every root in the model.
  final List<String> documentRoots;

  SomDartEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  }) : _ref = SpecReflection(model);

  /// The model version the generated object model reports (§2.1), `major.minor`.
  ///
  /// The major is parsed from [versionLabel] (`v0` → 0); the minor is `0` — the
  /// exported meta-data carries only an integer build counter (a different axis,
  /// per quest decision D15), not a semantic authoring minor, so conflating it
  /// would be wrong. A real minor source wires in when `release.md` introduces
  /// `major.minor` authoring versions.
  String get modelVersionString => '${_major()}.0';

  int _major() {
    final digits = versionLabel.replaceAll(RegExp(r'[^0-9]'), '');
    return int.tryParse(digits) ?? 0;
  }

  /// The roots to generate, resolved against [documentRoots] (empty ⇒ all).
  List<SpecRoot> get _selectedRoots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// Generated form-class names allocated so far in the current
  /// [generateLibrary] run, used to keep them globally unique (two distinct
  /// `(class, form-field)` pairs can derive the same base name). Reset at the
  /// start of every run so output stays deterministic.
  final Set<String> _usedFormNames = {};

  /// Returns a unique form-class name for [base], appending the smallest
  /// numeric suffix (`2`, `3`, …) that is not yet taken when [base] collides.
  String _allocFormName(String base) {
    if (_usedFormNames.add(base)) return base;
    var n = 2;
    while (!_usedFormNames.add('$base$n')) {
      n++;
    }
    return '$base$n';
  }

  /// Builds the complete generated library as a single source string.
  String generateLibrary() {
    _usedFormNames.clear();
    final rootTypes = _selectedRoots.map((r) => r.type).toSet();
    final reachable = _reachableClasses(rootTypes);
    final enums = _reachableEnums(reachable);
    final formClasses = <_FormClass>[];

    final classBlocks = <String>[];
    for (final name in reachable.toList()..sort()) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      classBlocks.add(_emitClass(cls, isRoot: rootTypes.contains(name),
          collectForm: (fc) => formClasses.add(fc)));
    }

    final buffer = StringBuffer()
      ..writeln('// GENERATED by tom_specs_clitool SomDartEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln('// ignore_for_file: type=lint, unused_import, '
          'document_ignores')
      ..writeln()
      ..writeln(
          "import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';")
      ..writeln();

    for (final e in enums) {
      buffer
        ..write(_emitEnum(e))
        ..writeln();
    }
    for (final block in classBlocks) {
      buffer
        ..write(block)
        ..writeln();
    }
    for (final fc in formClasses..sort((a, b) => a.name.compareTo(b.name))) {
      buffer
        ..write(fc.source)
        ..writeln();
    }
    return buffer.toString();
  }

  // --- reachability -------------------------------------------------------

  Set<String> _reachableClasses(Set<String> rootTypes) {
    final visited = <String>{};
    final queue = <String>[...rootTypes];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      if (!visited.add(name)) continue;
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        switch (f.kind) {
          case SpecFieldKind.complex:
          case SpecFieldKind.section:
            if (f.type != null) queue.add(f.type!);
            break;
          case SpecFieldKind.list:
            if (f.elementIsComplex && f.elementType != null) {
              queue.add(f.elementType!);
            }
            break;
          case SpecFieldKind.form:
          case SpecFieldKind.content:
          case SpecFieldKind.enumValue:
          case SpecFieldKind.scalar:
            break;
        }
      }
    }
    return visited;
  }

  /// The distinct enum types referenced by reachable classes, with their values.
  List<_EnumType> _reachableEnums(Set<String> reachable) {
    final byName = <String, _EnumType>{};
    for (final name in reachable) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        if (f.kind == SpecFieldKind.enumValue && f.enumType != null) {
          byName.putIfAbsent(
              f.enumType!, () => _EnumType(f.enumType!, f.enumValues));
        }
      }
    }
    final result = byName.values.toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    return result;
  }

  // --- emit ---------------------------------------------------------------

  String _emitEnum(_EnumType e) {
    final b = StringBuffer()
      ..writeln('/// Generated enum for `${e.name}` values.')
      ..writeln('enum ${e.name} {');
    for (var i = 0; i < e.values.length; i++) {
      final sep = i == e.values.length - 1 ? ';' : ',';
      b.writeln('  ${e.values[i]}$sep');
    }
    b
      ..writeln('}')
      ..writeln()
      ..writeln('/// Parses a stored token into a [${e.name}], or `null`.')
      ..writeln('${e.name}? _parse${e.name}(String? token) {')
      ..writeln('  if (token == null || token.isEmpty) return null;')
      ..writeln('  for (final v in ${e.name}.values) {')
      ..writeln('    if (v.name == token) return v;')
      ..writeln('  }')
      ..writeln('  return null;')
      ..writeln('}');
    return b.toString();
  }

  String _emitClass(
    SpecClass cls, {
    required bool isRoot,
    required void Function(_FormClass) collectForm,
  }) {
    final b = StringBuffer();
    _writeDoc(b, cls.doc, '');
    b.writeln('class ${cls.name} extends SomNode {');

    if (isRoot) {
      final root = model.roots.firstWhere((r) => r.type == cls.name);
      final seg = _ref.rootSegment(root);
      b
        ..writeln('  /// The model version this object model was generated '
            'against (§2.1).')
        ..writeln("  static const String modelVersion = "
            "'$modelVersionString';")
        ..writeln()
        ..writeln('  /// Creates the typed facade over [doc] at the document '
            'root and verifies')
        ..writeln('  /// the document\'s authoring [documentVersion] is '
            'editable (§2.2).')
        ..writeln('  ${cls.name}(SpecDocument doc, {String? documentVersion})')
        ..writeln("      : super(doc, '${_escape(seg)}') {")
        ..writeln('    checkSomModelVersion(modelVersion, documentVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  /// This object model\'s own model version (`major.minor`),'
            ' per spec §2.1.')
        ..writeln('  String get objectModelVersion => modelVersion;');
    } else {
      b.writeln('  ${cls.name}(super.doc, super.path);');
    }

    for (final f in cls.fields) {
      b.writeln();
      _writeField(b, cls, f, collectForm);
    }
    b.writeln('}');
    return b.toString();
  }

  void _writeField(
    StringBuffer b,
    SpecClass cls,
    SpecField f,
    void Function(_FormClass) collectForm,
  ) {
    final seg = _ref.fieldSegment(f);
    final childPath = "'\$path/${_escape(seg)}'";
    _writeDoc(b, f.doc, '  ');
    switch (f.kind) {
      case SpecFieldKind.content:
      case SpecFieldKind.scalar:
        b
          ..writeln('  String get ${f.name} => doc.content($childPath) ?? \'\';')
          ..writeln(
              '  set ${f.name}(String value) => doc.setContent($childPath, value);');
        break;
      case SpecFieldKind.enumValue:
        if (f.enumType == null) {
          // No enum type name available — fall back to a string leaf.
          b
            ..writeln(
                '  String get ${f.name} => doc.content($childPath) ?? \'\';')
            ..writeln(
                '  set ${f.name}(String value) => doc.setContent($childPath, value);');
        } else {
          final et = f.enumType!;
          b
            ..writeln(
                '  $et? get ${f.name} => _parse$et(doc.content($childPath));')
            ..writeln('  set ${f.name}($et? value) => '
                'doc.setContent($childPath, value?.name ?? \'\');');
        }
        break;
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = f.type;
        if (target == null) {
          b.writeln('  // (skipped: ${f.name} has no target type)');
        } else {
          b.writeln('  $target get ${f.name} => $target(doc, $childPath);');
        }
        break;
      case SpecFieldKind.list:
        if (f.elementIsComplex && f.elementType != null) {
          final et = f.elementType!;
          b.writeln('  SomList<$et> get ${f.name} => '
              'SomList<$et>(doc, $childPath, (d, p) => $et(d, p));');
        } else {
          b.writeln('  SomList<SomScalar> get ${f.name} => '
              'SomList<SomScalar>(doc, $childPath, (d, p) => SomScalar(d, p));');
        }
        break;
      case SpecFieldKind.form:
        final formName = _allocFormName('${cls.name}${_pascal(f.name)}Form');
        collectForm(_FormClass(formName, _emitFormClass(formName, f)));
        b.writeln('  $formName get ${f.name} => $formName(doc, $childPath);');
        break;
    }
  }

  String _emitFormClass(String name, SpecField f) {
    final b = StringBuffer()
      ..writeln('/// Generated form facade for the `${f.name}` `@Form` section.')
      ..writeln('class $name extends SomNode {')
      ..writeln('  $name(super.doc, super.path);');
    for (final ff in f.formFields) {
      b
        ..writeln()
        ..writeln(
            '  String get ${ff.name} => doc.formField(path, \'${_escape(ff.name)}\') ?? \'\';')
        ..writeln('  set ${ff.name}(String value) => '
            'doc.setFormField(path, \'${_escape(ff.name)}\', value);');
    }
    b.writeln('}');
    return b.toString();
  }

  void _writeDoc(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    for (final line in doc.trimRight().split('\n')) {
      b.writeln('$indent/// ${line.trimRight()}');
    }
  }

  String _escape(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\$', '\\\$');

  String _pascal(String s) {
    final parts = s.split(RegExp(r'[_\s]+')).where((p) => p.isNotEmpty);
    return parts
        .map((p) => p[0].toUpperCase() + p.substring(1))
        .join();
  }
}

class _EnumType {
  final String name;
  final List<String> values;
  _EnumType(this.name, this.values);
}

class _FormClass {
  final String name;
  final String source;
  _FormClass(this.name, this.source);
}
