/// Emits the generated TypeScript typed object model (`tom_som_typescript_v0`)
/// from a resolved [SpecModel].
///
/// The generated classes are an **editing facade** over the generic
/// `tom_som_typescript_runtime` `SpecDocument`: every typed accessor delegates to
/// the path-keyed memory representation, so a typed mutation is visible through
/// the generic path and vice-versa (spec §3). Each document-root class performs
/// the **instantiation-time version check** (`checkSomModelVersion`) against the
/// document's authoring stamp (§2.2) and exposes its own generated model version
/// (§2.1).
///
/// This is the TypeScript counterpart of [SomDartEmitter] / `SomPythonEmitter` /
/// `SomJavaEmitter` / `SomJavaScriptEmitter` — the same reachability walk, the
/// same deterministic ordering, the same field-kind mapping. The emitted surface
/// is a single TypeScript module of `export class` declarations with typed
/// `get`/`set` accessors over the shared runtime facade base classes. Like the
/// statically-compiled Java facade, the module imports the generic runtime
/// through a **fixed bare specifier** (`tom_som_typescript_runtime`); the
/// generator wires resolution by writing a `package.json` with a relative
/// `file:` dependency and a `tsconfig.json`, so the emitted source carries no
/// on-disk path and stays layout-independent / golden-stable.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Generates the `tom_som_typescript_v0` module source for a [SpecModel].
class SomTypeScriptEmitter {
  final SpecModel model;
  final SpecReflection _ref;

  /// The version label of the generated project (`v0`, `v1`, …); names the
  /// `tom_som_<slug>_<label>` output project. It no longer drives the reported
  /// model version — see [modelVersionString].
  final String versionLabel;

  /// The document-root type names to generate. Empty ⇒ every root in the model.
  final List<String> documentRoots;

  SomTypeScriptEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  }) : _ref = SpecReflection(model);

  /// The model version the generated object model reports (§2.1), `major.minor`,
  /// taken from the model's own version stamp (the `tom_specs_model` project
  /// version), not the project [versionLabel] — which only names the `_vN`
  /// output project.
  String get modelVersionString => model.modelVersionString;

  /// The roots to generate, resolved against [documentRoots] (empty ⇒ all).
  List<SpecRoot> get _selectedRoots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// Generated form-class names allocated so far in the current
  /// [generateLibrary] run, used to keep them globally unique. Reset at the
  /// start of every run so output stays deterministic.
  final Set<String> _usedFormNames = {};

  /// Returns a unique form-class name for [base], appending the smallest
  /// numeric suffix (`2`, `3`, …) that is not yet taken when [base] collides.
  String _allocFormName(String base) {
    if (_usedFormNames.add(base)) return base;
    var n = 2;
    while (!_usedFormNames.add('$base$n')) {
      n++;
    }
    return '$base$n';
  }

  /// Builds the complete generated module as a single TypeScript source string.
  String generateLibrary() {
    _usedFormNames.clear();
    final rootTypes = _selectedRoots.map((r) => r.type).toSet();
    final reachable = _reachableClasses(rootTypes);
    final enums = _reachableEnums(reachable);
    final formClasses = <_FormClass>[];

    final classBlocks = <String>[];
    for (final name in reachable.toList()..sort()) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      classBlocks.add(_emitClass(cls,
          isRoot: rootTypes.contains(name),
          collectForm: (fc) => formClasses.add(fc)));
    }

    final buffer = StringBuffer()
      ..writeln('// GENERATED by tom_specs_clitool SomTypeScriptEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln()
      ..writeln('// Typed object-model facade over the generic '
          '`tom_som_typescript_runtime` document.')
      ..writeln('//')
      ..writeln('// The generic runtime is imported through a fixed bare '
          'specifier; the generator')
      ..writeln('// wires resolution by writing a `package.json` `file:` '
          'dependency on the runtime')
      ..writeln('// and a `tsconfig.json`, so this module carries no on-disk '
          'path of its own.')
      ..writeln("import {")
      ..writeln('  SomEditability,')
      ..writeln('  SomList,')
      ..writeln('  SomNode,')
      ..writeln('  SomScalar,')
      ..writeln('  SpecDocument,')
      ..writeln('  checkSomModelVersion,')
      ..writeln('  somEditabilityFor,')
      ..writeln("} from 'tom_som_typescript_runtime';")
      ..writeln()
      ..writeln('// The generated metadata module (SOM §8): the populated '
          'SomMetaTrees plus')
      ..writeln('// the dot-notation and ID-tree access surfaces. Its exports '
          'are re-exported')
      ..writeln('// below, so one import of this facade surfaces both '
          'access styles.')
      ..writeln("import * as _meta from "
          "'./tom_som_typescript_${versionLabel}_meta';")
      ..writeln("export * from './tom_som_typescript_${versionLabel}_meta';")
      ..writeln();

    for (final e in enums) {
      buffer
        ..write(_emitEnum(e))
        ..writeln();
    }
    for (final block in classBlocks) {
      buffer
        ..write(block)
        ..writeln();
    }
    for (final fc in formClasses..sort((a, b) => a.name.compareTo(b.name))) {
      buffer
        ..write(fc.source)
        ..writeln();
    }
    // The flat path-constant holders (§ item 11) are retired (SOM §8): the
    // metadata module's dot-notation and ID-tree surfaces own path access.
    return buffer.toString();
  }

  // --- reachability -------------------------------------------------------

  Set<String> _reachableClasses(Set<String> rootTypes) {
    final visited = <String>{};
    final queue = <String>[...rootTypes];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      if (!visited.add(name)) continue;
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        switch (f.kind) {
          case SpecFieldKind.complex:
          case SpecFieldKind.section:
            if (f.type != null) queue.add(f.type!);
            break;
          case SpecFieldKind.list:
            if (f.elementIsComplex && f.elementType != null) {
              queue.add(f.elementType!);
            }
            break;
          case SpecFieldKind.form:
          case SpecFieldKind.content:
          case SpecFieldKind.enumValue:
          case SpecFieldKind.scalar:
            break;
        }
      }
    }
    return visited;
  }

  /// The distinct enum types referenced by reachable classes, with their values.
  List<_EnumType> _reachableEnums(Set<String> reachable) {
    final byName = <String, _EnumType>{};
    for (final name in reachable) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        if (f.kind == SpecFieldKind.enumValue && f.enumType != null) {
          byName.putIfAbsent(
              f.enumType!, () => _EnumType(f.enumType!, f.enumValues));
        }
      }
    }
    final result = byName.values.toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    return result;
  }

  // --- emit ---------------------------------------------------------------

  String _emitEnum(_EnumType e) {
    final b = StringBuffer()
      ..writeln('// Generated enum for `${e.name}` values.')
      ..writeln('export const ${e.name} = Object.freeze({');
    for (final v in e.values) {
      // Both the key and the value carry the original token (the Dart constant
      // name) verbatim — a TS object key is quoted so any token is valid, and
      // parse/encode round-trips through the stored token, keeping documents
      // cross-language compatible.
      b.writeln('  "${_jstr(v)}": "${_jstr(v)}",');
    }
    b
      ..writeln('});')
      ..writeln()
      ..writeln('// Parses a stored token into a ${e.name} value, or null.')
      ..writeln('function _parse${e.name}('
          'token: string | null | undefined): string | null {')
      ..writeln('  if (!token) {')
      ..writeln('    return null;')
      ..writeln('  }')
      ..writeln('  for (const value of Object.values(${e.name})) {')
      ..writeln('    if (value === token) {')
      ..writeln('      return value;')
      ..writeln('    }')
      ..writeln('  }')
      ..writeln('  return null;')
      ..writeln('}');
    return b.toString();
  }

  String _emitClass(
    SpecClass cls, {
    required bool isRoot,
    required void Function(_FormClass) collectForm,
  }) {
    final b = StringBuffer();
    _writeDoc(b, cls.doc, '');
    b.writeln('export class ${cls.name} extends SomNode {');

    if (isRoot) {
      final root = model.roots.firstWhere((r) => r.type == cls.name);
      final seg = _ref.rootSegment(root);
      b
        ..writeln('  // The model version this object model was generated '
            'against (§2.1).')
        ..writeln('  static readonly MODEL_VERSION: string = '
            '"$modelVersionString";')
        ..writeln()
        ..writeln('  // Creates the typed facade at the document root and '
            'verifies the')
        ..writeln("  // document's authoring documentVersion is editable "
            '(§2.2).')
        ..writeln('  constructor(doc: SpecDocument, '
            'documentVersion: string | null = null) {')
        ..writeln('    super(doc, "${_jstr(seg)}");')
        ..writeln('    checkSomModelVersion(${cls.name}.MODEL_VERSION, '
            'documentVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  // Loads a `*.docspecs.yaml` document and returns the typed '
            'root with the')
        ..writeln("  // document's authoring stamp already applied (§ item 4) — "
            'one call for')
        ..writeln('  // the former decode → loadJson → thread-`documentVersion` '
            'sequence.')
        ..writeln('  static loadYaml(yaml: string): ${cls.name} {')
        ..writeln('    const doc = SpecDocument.fromYaml(yaml, '
            '_meta.${_camelType(cls.name)}MetaTree);')
        ..writeln('    return new ${cls.name}(doc, doc.modelVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  // Loads a `*.docspecs.yaml` document from the file at '
            '`path` — the file')
        ..writeln('  // companion to loadYaml.')
        ..writeln('  static loadFile(path: string): ${cls.name} {')
        ..writeln('    const doc = SpecDocument.fromFile(path, '
            '_meta.${_camelType(cls.name)}MetaTree);')
        ..writeln('    return new ${cls.name}(doc, doc.modelVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln("  // This object model's own model version (major.minor), "
            'per §2.1.')
        ..writeln('  get objectModelVersion(): string {')
        ..writeln('    return ${cls.name}.MODEL_VERSION;')
        ..writeln('  }')
        ..writeln()
        ..writeln('  // Classifies whether a document authored under '
            '`documentVersion` is')
        ..writeln('  // editable by this object model, **without throwing** '
            '(§ item 8) — the')
        ..writeln("  // non-throwing companion to the constructor's §2.2 "
            'check, so a read-only')
        ..writeln('  // viewer can branch instead of catching '
            'SomVersionError.')
        ..writeln('  static editabilityFor(documentVersion: string | null): '
            'SomEditability {')
        ..writeln('    return somEditabilityFor(${cls.name}.MODEL_VERSION, '
            'documentVersion);')
        ..writeln('  }');
    } else {
      b
        ..writeln('  constructor(doc: SpecDocument, path: string) {')
        ..writeln('    super(doc, path);')
        ..writeln('  }');
    }

    // § item 10: a content-bearing section overrides the `SomNode.canHaveContent`
    // structural default (`false`) to `true`, so "can this section hold body
    // text?" is answerable at the type level without probing `.content`.
    if (_hasContentLeaf(cls)) {
      b
        ..writeln()
        ..writeln('  get canHaveContent(): boolean {')
        ..writeln('    return true;')
        ..writeln('  }');
    }

    for (final f in cls.fields) {
      b.writeln();
      _writeField(b, cls, f, collectForm);
    }
    b.writeln('}');
    return b.toString();
  }

  /// Whether [cls] declares the standard `content` text leaf — the structural
  /// signal that its generated facade carries a `.content` accessor (§ item 10).
  bool _hasContentLeaf(SpecClass cls) => cls.fields
      .any((f) => f.name == 'content' && f.kind == SpecFieldKind.content);

  void _writeField(
    StringBuffer b,
    SpecClass cls,
    SpecField f,
    void Function(_FormClass) collectForm,
  ) {
    final seg = _ref.fieldSegment(f);
    final childPath = 'this.path + "/${_jstr(seg)}"';
    // TS-safe accessor identifier (the path segment above is untouched).
    final acc = _acc(f.name);
    switch (f.kind) {
      case SpecFieldKind.content:
      case SpecFieldKind.scalar:
        _emitStringProperty(b, acc, childPath, f.doc);
        break;
      case SpecFieldKind.enumValue:
        if (f.enumType == null) {
          _emitStringProperty(b, acc, childPath, f.doc);
        } else {
          final et = f.enumType!;
          _writeComment(b, f.doc, '  ');
          b
            ..writeln('  get $acc(): string | null {')
            ..writeln('    return _parse$et(this.doc.content($childPath));')
            ..writeln('  }')
            ..writeln()
            ..writeln('  set $acc(value: string | null) {')
            ..writeln('    this.doc.setContent($childPath, '
                'value != null ? value : "");')
            ..writeln('  }');
        }
        break;
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = f.type;
        _writeComment(b, f.doc, '  ');
        if (target == null) {
          b.writeln('  // (skipped: ${f.name} has no target type)');
        } else {
          b
            ..writeln('  get $acc(): $target {')
            ..writeln('    return new $target(this.doc, $childPath);')
            ..writeln('  }');
        }
        break;
      case SpecFieldKind.list:
        _writeComment(b, f.doc, '  ');
        // The `@SectionIdPattern` (if any) becomes SomList's 4th constructor
        // argument, driving list-item section-id generation (AA1 criteria 3–5).
        final patternArg =
            f.sectionIdPattern != null ? ', "${_jstr(f.sectionIdPattern!)}"' : '';
        if (f.elementIsComplex && f.elementType != null) {
          final et = f.elementType!;
          b
            ..writeln('  get $acc(): SomList<$et> {')
            ..writeln('    return new SomList(this.doc, $childPath, '
                '(d: SpecDocument, p: string) => new $et(d, p)$patternArg);')
            ..writeln('  }');
        } else {
          b
            ..writeln('  get $acc(): SomList<SomScalar> {')
            ..writeln('    return new SomList(this.doc, $childPath, '
                '(d: SpecDocument, p: string) => new SomScalar(d, p)$patternArg);')
            ..writeln('  }');
        }
        break;
      case SpecFieldKind.form:
        final formName = _allocFormName('${cls.name}${_pascal(f.name)}Form');
        collectForm(_FormClass(formName, _emitFormClass(formName, f)));
        _writeComment(b, f.doc, '  ');
        b
          ..writeln('  get $acc(): $formName {')
          ..writeln('    return new $formName(this.doc, $childPath);')
          ..writeln('  }');
        break;
    }
  }

  void _emitStringProperty(
      StringBuffer b, String name, String childPath, String? doc) {
    _writeComment(b, doc, '  ');
    b
      ..writeln('  get $name(): string {')
      ..writeln("    return this.doc.content($childPath) || '';")
      ..writeln('  }')
      ..writeln()
      ..writeln('  set $name(value: string) {')
      ..writeln('    this.doc.setContent($childPath, value);')
      ..writeln('  }');
  }

  /// Emits the typed **section class** for a `@Form` field (YRB2): the section's
  /// own `content` text FIRST, then one correctly-typed member per `@Form`
  /// `Field(name, Type, …)` entry, in declaration order. A member's declared
  /// scalar type (`int`/`double`/`num` → `number`, `bool` → `boolean`) becomes
  /// its parsed TypeScript type; any non-primitive (enums, `List`, …) falls back
  /// to `string`. Members read/write through the generic form store, so the
  /// on-disk markdown format and the conformance golden stay byte-identical.
  String _emitFormClass(String name, SpecField f) {
    final hasContentMember = f.formFields.any((ff) => ff.name == 'content');
    final b = StringBuffer()
      ..writeln('// Generated section facade for the `${f.name}` @Form section: '
          'its own content text followed by one typed member per form field.')
      ..writeln('export class $name extends SomNode {')
      ..writeln('  constructor(doc: SpecDocument, path: string) {')
      ..writeln('    super(doc, path);')
      ..writeln('  }')
      ..writeln()
      ..writeln('  get canHaveContent(): boolean {')
      ..writeln('    return true;')
      ..writeln('  }');
    if (!hasContentMember) {
      b
        ..writeln()
        ..writeln('  get content(): string {')
        ..writeln("    return this.doc.content(this.path) || '';")
        ..writeln('  }')
        ..writeln()
        ..writeln('  set content(value: string) {')
        ..writeln('    this.doc.setContent(this.path, value);')
        ..writeln('  }');
    }
    for (final ff in f.formFields) {
      _writeFormMember(b, ff);
    }
    b.writeln('}');
    return b.toString();
  }

  /// Emits a single typed `@Form` member accessor pair backed by the generic
  /// form store, so the on-disk format and the generic reading are unchanged;
  /// only the TypeScript type mirrors the declared form-field type.
  void _writeFormMember(StringBuffer b, FormFieldSpec ff) {
    final field = '"${_jstr(ff.name)}"';
    // The form-field key string ($field) is preserved; only the TS accessor
    // identifier is keyword-sanitised.
    final acc = _acc(ff.name);
    b.writeln();
    switch (_scalarType(ff.type)) {
      case 'int':
        b
          ..writeln('  get $acc(): number | null {')
          ..writeln('    const v = this.doc.formField(this.path, $field);')
          ..writeln("    return v == null || v === '' ? null : "
              'Number.parseInt(v, 10);')
          ..writeln('  }')
          ..writeln()
          ..writeln('  set $acc(value: number | null) {')
          ..writeln('    this.doc.setFormField(this.path, $field, '
              "value == null ? '' : String(value));")
          ..writeln('  }');
      case 'double':
      case 'num':
        b
          ..writeln('  get $acc(): number | null {')
          ..writeln('    const v = this.doc.formField(this.path, $field);')
          ..writeln("    return v == null || v === '' ? null : "
              'Number.parseFloat(v);')
          ..writeln('  }')
          ..writeln()
          ..writeln('  set $acc(value: number | null) {')
          ..writeln('    this.doc.setFormField(this.path, $field, '
              "value == null ? '' : String(value));")
          ..writeln('  }');
      case 'bool':
        b
          ..writeln('  get $acc(): boolean | null {')
          ..writeln('    const v = this.doc.formField(this.path, $field);')
          ..writeln("    return v == null ? null : v === 'true';")
          ..writeln('  }')
          ..writeln()
          ..writeln('  set $acc(value: boolean | null) {')
          ..writeln('    this.doc.setFormField(this.path, $field, '
              "value == null ? '' : (value ? 'true' : 'false'));")
          ..writeln('  }');
      default:
        b
          ..writeln('  get $acc(): string {')
          ..writeln("    return this.doc.formField(this.path, $field) || '';")
          ..writeln('  }')
          ..writeln()
          ..writeln('  set $acc(value: string) {')
          ..writeln('    this.doc.setFormField(this.path, $field, value);')
          ..writeln('  }');
    }
  }

  /// Maps a `@Form` field's declared type name to the primitive scalar kind the
  /// facade should expose, or `'String'` for any non-primitive (enums, `List`,
  /// unresolved types) so the generated code always round-trips as text.
  static String _scalarType(String typeName) {
    final base = typeName.endsWith('?')
        ? typeName.substring(0, typeName.length - 1)
        : typeName;
    switch (base) {
      case 'int':
      case 'double':
      case 'num':
      case 'bool':
        return base;
      default:
        return 'String';
    }
  }

  /// Emits a doc block as `//` line comments at [indent]. A `*/` cannot
  /// terminate a `//` line comment, so no escaping is needed.
  void _writeDoc(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    for (final line in doc.trimRight().split('\n')) {
      final text = line.trimRight();
      b.writeln(text.isEmpty ? '$indent//' : '$indent// $text');
    }
  }

  /// Emits a field's doc as `//` comment lines above its accessor.
  void _writeComment(StringBuffer b, String? doc, String indent) =>
      _writeDoc(b, doc, indent);

  /// Escapes a value for a double-quoted TypeScript string literal.
  String _jstr(String s) => s
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r')
      .replaceAll('\t', '\\t');

  /// The TypeScript/JavaScript reserved words, the object-property names that are
  /// unsafe to use as a class accessor (`constructor` is special-cased by the
  /// language; `prototype` / `__proto__` shadow the prototype chain), **and the
  /// inherited [SomNode] instance fields `doc` / `path`**.
  ///
  /// Dart field and form-field names are otherwise valid TS accessor names, but a
  /// `get constructor()` is a syntax error and the others are footguns. The
  /// `doc` / `path` cases are TypeScript-specific: a generated `get path()` /
  /// `get doc()` would override the base **property** with an **accessor** (TS
  /// error TS2611) and, worse, the accessor body's own `this.path` reference
  /// would recurse — so a model field literally named `path` (e.g. an
  /// `InterfaceOperationEntry` content form) must be sanitised. A
  /// trailing-underscore convention is applied uniformly across the reserved set
  /// — matching the Python/Java/JavaScript facades for the keywords, with the
  /// extra base-member guard the static TS compiler requires.
  static const Set<String> _tsKeywords = {
    'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
    'default', 'delete', 'do', 'else', 'export', 'extends', 'finally', 'for',
    'function', 'if', 'import', 'in', 'instanceof', 'new', 'return', 'super',
    'switch', 'this', 'throw', 'try', 'typeof', 'var', 'void', 'while', 'with',
    'yield', 'enum', 'await', 'implements', 'interface', 'let', 'package',
    'private', 'protected', 'public', 'static', 'null', 'true', 'false',
    'constructor', 'prototype', '__proto__',
    // Inherited SomNode instance fields — a typed accessor of the same name
    // would shadow/override the base property (TS2611) and self-recurse.
    'doc', 'path',
  };

  /// Returns a TS-safe accessor identifier for [name].
  ///
  /// Only the emitted TS identifier changes — the document path segment and the
  /// stored enum token are derived independently and stay byte-identical to the
  /// other facades, so cross-language documents remain compatible.
  String _acc(String name) => _tsKeywords.contains(name) ? '${name}_' : name;

  /// The lowerCamelCase form of a type name — names the per-root
  /// `<camelType>MetaTree` constant in the generated metadata module.
  String _camelType(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  String _pascal(String s) {
    final parts = s.split(RegExp(r'[_\s]+')).where((p) => p.isNotEmpty);
    return parts.map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }
}

class _EnumType {
  final String name;
  final List<String> values;
  _EnumType(this.name, this.values);
}

class _FormClass {
  final String name;
  final String source;
  _FormClass(this.name, this.source);
}
