/// Emits the generated **metadata module** of the Python `v0` facade (DR12,
/// the Python counterpart of `som_dart_meta_emitter.dart` / DR8): the
/// populated `SomMetaTree`s as generated static data structures in code
/// (DR1 §3.2) plus the two discoverable access surfaces of DR1 §4 — the
/// **dot-notation tree** (member names, §4.1) and the **ID-tree** (section
/// ids, §4.2). This module replaces the retired flat path-constant holders
/// (`SbpPaths.…`) in the Python facade.
///
/// The emitted node values mirror `tom_som_python_runtime`'s
/// `build_som_meta_tree` (the meta-JSON bridge) **field for field**, sourced
/// from the same [SpecModel], so the generated trees and the bridge-built
/// trees are structurally identical — the facade test suite asserts this
/// exhaustively. Cycle handling matches the bridge: a class already on the
/// descent stack becomes a terminal re-entry node (`recursive=True`), which
/// the generated `_cx` helper reproduces at tree-construction time.
///
/// Surface shapes (mirroring the Dart reference implementation, DR1 §4.3;
/// Python has no `$` in identifiers, so `<Class>$Nav` / `<Class>$Id` become
/// `<Class>Nav` / `<Class>Id` — verified collision-free against the model):
///
///   * one `class <Class>Nav(SomMetaRef)` accessor class per model class —
///     `@property` getters named exactly after the model members;
///   * one `class <Class>Id(SomMetaRef)` accessor class per ID-reachable
///     class — getters named by section id (`-` → `_`), hoisting through
///     id-less complex/section members so `SBP.INSC…` skips no ids;
///   * per document root: a module-level `<camelRoot>MetaTree` (SomMetaTree),
///     the dot-notation entry `<camelRoot>` and the ID-tree entry
///     `<ROOT-SEGMENT>`. Unlike Dart's lazy top-level finals, Python executes
///     the module top-down, so the root globals are emitted **after** all
///     accessor classes.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Annotation names with a dedicated `SomMetaNode` slot — everything else is
/// captured into `extra`. Must stay identical to the bridge's set.
const Set<String> _slottedAnnotations = {
  'SectionId',
  'SectionIdPattern',
  'SerializationOrder',
  'Min',
  'Unused',
  'ContentType',
  'ContentHelp',
  'Headline',
  'Comment',
  'Form',
  'Document',
  'MapsTo',
  'DetailedIn',
  'SecondLevelSectionId',
};

/// Getter names a generated accessor class must never emit (instance members
/// of the runtime's `SomMetaRef` and the list accessor's `item`). A property
/// named `path`/`tree` would even break `SomMetaRef.__init__`'s attribute
/// assignment, so collisions fail generation loudly.
const Set<String> _reservedAccessorNames = {
  'path',
  'meta',
  'tree',
  'item',
};

/// Emits the Python source of the generated metadata module (see the library
/// doc above) for [model].
class SomPythonMetaEmitter {
  final SpecModel model;
  final String versionLabel;
  final List<String> documentRoots;

  SomPythonMetaEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  });

  List<SpecRoot> get _roots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// The complete generated metadata module source.
  String generateLibrary() {
    final b = StringBuffer()
      ..writeln('# GENERATED by tom_specs_clitool SomPythonMetaEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln('#')
      ..writeln('# The populated SOM metadata trees (DR1 §3.2) and the two')
      ..writeln('# generated access surfaces of DR1 §4: the dot-notation tree')
      ..writeln('# (model member names) and the ID-tree (section ids). Both')
      ..writeln('# resolve to the same SomMetaNode and byte-identical path')
      ..writeln('# strings; the flat path-constant holders are retired.')
      ..writeln()
      ..writeln('from tom_som_runtime import (')
      ..writeln('    SomContentTypeMeta,')
      ..writeln('    SomDocMeta,')
      ..writeln('    SomFormFieldMeta,')
      ..writeln('    SomFormMeta,')
      ..writeln('    SomListMetaRef,')
      ..writeln('    SomMetaExtra,')
      ..writeln('    SomMetaKind,')
      ..writeln('    SomMetaNode,')
      ..writeln('    SomMetaRef,')
      ..writeln('    SomMetaTree,')
      ..writeln('    SomSecondLevelId,')
      ..writeln(')')
      ..writeln();

    _emitCxHelper(b);

    final classNames = model.classes.keys.toList()..sort();

    // ── metadata children builders ─────────────────────────────────────────
    b
      ..writeln('# ── metadata tree builders (DR1 §3.2) '
          '─────────────────────────────────────')
      ..writeln();
    for (final name in classNames) {
      _emitMetaChildrenBuilder(b, model.classes[name]!);
    }

    // ── dot-notation accessor classes ──────────────────────────────────────
    b
      ..writeln('# ── dot-notation accessor classes (DR1 §4.1) '
          '──────────────────────────────')
      ..writeln();
    for (final name in classNames) {
      _emitNavClass(b, model.classes[name]!);
    }

    // ── ID-tree accessor classes ───────────────────────────────────────────
    b
      ..writeln('# ── ID-tree accessor classes (DR1 §4.2) '
          '───────────────────────────────────')
      ..writeln();
    for (final name in _idReachableClasses()) {
      _emitIdClass(b, model.classes[name]!);
    }

    // ── per-root trees + access-surface entry points (module tail: Python
    //    executes top-down, so these come after the classes they use) ───────
    b
      ..writeln('# ── document-root metadata trees + access surface roots '
          '───────────────────')
      ..writeln();
    for (final root in _roots) {
      _emitRoot(b, root);
    }

    return b.toString();
  }

  // ── shared helpers ─────────────────────────────────────────────────────────

  void _emitCxHelper(StringBuffer b) {
    b
      ..writeln('def _cx(cls, stack, kids, make):')
      ..writeln('    """Builds a complex/section (or list-element) node with '
          "the bridge's")
      ..writeln('    cycle rule: a class already on the descent *stack* '
          'becomes a terminal')
      ..writeln('    re-entry node (``recursive=True``, no children)."""')
      ..writeln('    if cls in stack:')
      ..writeln('        return make(True, [])')
      ..writeln('    stack.add(cls)')
      ..writeln('    c = kids(stack)')
      ..writeln('    stack.remove(cls)')
      ..writeln('    return make(False, c)')
      ..writeln();
  }

  /// The fields of [cls] in emission order: `@SerializationOrder` ascending,
  /// declaration index as tiebreaker/fallback — identical to the bridge.
  List<SpecField> _orderedFields(SpecClass cls) {
    final indexed = cls.fields.asMap().entries.toList()
      ..sort((a, b) {
        const fallback = 1 << 30;
        final oa = a.value.serializationOrder ?? fallback;
        final ob = b.value.serializationOrder ?? fallback;
        return oa != ob ? oa.compareTo(ob) : a.key.compareTo(b.key);
      });
    return [for (final e in indexed) e.value];
  }

  String _fieldSegment(SpecField f) => f.sectionId ?? f.name;

  String _rootSegment(SpecRoot root) => root.sectionId ?? root.type;

  String _camel(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  /// The Python `SomMetaKind` member for a [SpecFieldKind].
  String _kindMember(SpecFieldKind kind) {
    switch (kind) {
      case SpecFieldKind.list:
        return 'LIST';
      case SpecFieldKind.form:
        return 'FORM';
      case SpecFieldKind.section:
        return 'SECTION';
      case SpecFieldKind.content:
        return 'CONTENT';
      case SpecFieldKind.enumValue:
        return 'ENUM_VALUE';
      case SpecFieldKind.complex:
        return 'COMPLEX';
      case SpecFieldKind.scalar:
        return 'SCALAR';
    }
  }

  /// A Python double-quoted string literal for [s] (full control-character
  /// escaping — doc comments and descriptions carry newlines).
  String _str(String s) => '"${s.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n').replaceAll('\r', '\\r').replaceAll('\t', '\\t')}"';

  /// A Python literal for a JSON-shaped annotation-argument [value].
  String _lit(Object? value) {
    if (value == null) return 'None';
    if (value is String) return _str(value);
    if (value is bool) return value ? 'True' : 'False';
    if (value is num) return '$value';
    if (value is List) return '[${value.map(_lit).join(', ')}]';
    if (value is Map) {
      final entries = value.entries
          .map((e) => '${_str('${e.key}')}: ${_lit(e.value)}')
          .join(', ');
      return '{$entries}';
    }
    throw StateError('unsupported annotation argument literal: '
        '${value.runtimeType} ($value)');
  }

  // ── metadata builders ──────────────────────────────────────────────────────

  void _emitMetaChildrenBuilder(StringBuffer b, SpecClass cls) {
    b
      ..writeln('def _mc_${cls.name}(s):')
      ..writeln('    return [');
    for (final f in _orderedFields(cls)) {
      b.writeln('${_fieldNodeExpr(cls, f, indent: '        ')},');
    }
    b
      ..writeln('    ]')
      ..writeln()
      ..writeln();
  }

  /// The expression building the `SomMetaNode` for field [f] of [owner] —
  /// value-for-value the bridge's `_field_node`.
  String _fieldNodeExpr(SpecClass owner, SpecField f,
      {required String indent}) {
    final isComplexLike =
        f.kind == SpecFieldKind.complex || f.kind == SpecFieldKind.section;
    final target = isComplexLike ? model.classNamed(f.type ?? '') : null;

    final args = <String>[];
    void add(String name, String? expr) {
      if (expr != null) args.add('$name=$expr');
    }

    add('class_name', _str(target?.name ?? owner.name));
    add('member_name', _str(f.name));
    if (f.sectionId != null) add('section_id', _str(f.sectionId!));
    if (target?.sectionId != null) {
      add('class_section_id', _str(target!.sectionId!));
    }
    if (f.sectionIdPattern != null) {
      add('section_id_pattern', _str(f.sectionIdPattern!));
    }
    add('kind', 'SomMetaKind.${_kindMember(f.kind)}');
    add('type_name', _str(f.type ?? f.elementType ?? f.enumType ?? 'String'));
    if (f.serializationOrder != null) {
      add('serialization_order', '${f.serializationOrder}');
    }
    if (f.min != null) add('min', '${f.min}');
    if (f.annotation('Unused') != null) add('unused', 'True');
    if (f.contentType != null) {
      final desc =
          '${f.annotation('ContentType')?.argument('description') ?? ''}';
      add(
          'content_type',
          'SomContentTypeMeta(type=${_str(f.contentType!)}, '
              'description=${_str(desc)})');
    }
    if (f.help != null) add('content_help', _str(f.help!));
    final headline = f.headline ?? target?.headline;
    if (headline != null) add('headline', _str(headline));
    final comment = '${f.annotation('Comment')?.argument('text') ?? ''}';
    if (comment.isNotEmpty) add('comment', _str(comment));
    final docComment = f.doc ?? target?.doc;
    if (docComment != null) add('doc_comment', _str(docComment));
    if (target?.doc != null) add('class_doc_comment', _str(target!.doc!));
    if (f.kind == SpecFieldKind.form) {
      final fields = <String>[];
      for (var i = 0; i < f.formFields.length; i++) {
        final ff = f.formFields[i];
        final ffArgs = <String>[
          'name=${_str(ff.name)}',
          'type_name=${_str(ff.type)}',
          'description=${_str(ff.label)}',
          if (ff.required) 'required=True',
          if (ff.hint != null) 'hint=${_str(ff.hint!)}',
          'order=$i',
          if (ff.enumValues.isNotEmpty)
            'enum_values=[${ff.enumValues.map(_str).join(', ')}]',
        ];
        fields.add('SomFormFieldMeta(${ffArgs.join(', ')})');
      }
      add('form', 'SomFormMeta(fields=[${fields.join(', ')}])');
    }
    if (target?.mapsTo != null) add('maps_to', _str(target!.mapsTo!));
    if (target?.detailedIn != null) {
      add('detailed_in', _str(target!.detailedIn!));
    }
    final secondLevel = _secondLevelIdsExpr(f.annotations);
    if (secondLevel != null) add('second_level_ids', secondLevel);
    final extra = _extrasExpr(f.annotations);
    if (extra != null) add('extra', extra);

    // Element subtree of a complex-element list.
    if (f.kind == SpecFieldKind.list && f.elementIsComplex) {
      final element = model.classNamed(f.elementType ?? '');
      if (element != null) {
        final elemArgs = <String>[
          'class_name=${_str(element.name)}',
          if (element.sectionId != null)
            'class_section_id=${_str(element.sectionId!)}',
          'kind=SomMetaKind.COMPLEX',
          'type_name=${_str(element.name)}',
          if (element.headline != null)
            'headline=${_str(element.headline!)}',
          if (element.doc != null) 'doc_comment=${_str(element.doc!)}',
          if (element.doc != null) 'class_doc_comment=${_str(element.doc!)}',
          if (element.mapsTo != null) 'maps_to=${_str(element.mapsTo!)}',
          if (element.detailedIn != null)
            'detailed_in=${_str(element.detailedIn!)}',
          'recursive=r',
          'children=c',
        ];
        add(
            'element_node',
            '_cx(${_str(element.name)}, s, _mc_${element.name}, '
                'lambda r, c: SomMetaNode(${elemArgs.join(', ')}))');
      }
    }

    final body = args.join(',\n$indent    ');
    if (target != null) {
      // Complex/section: children/recursive resolved by the cycle helper.
      return '$indent _cx(${_str(target.name)}, s, _mc_${target.name},\n'
          '$indent    lambda r, c: SomMetaNode(\n$indent        '
          '${args.join(',\n$indent        ')},\n'
          '$indent        recursive=r,\n$indent        children=c))';
    }
    return '$indent SomMetaNode(\n$indent    $body)';
  }

  String? _secondLevelIdsExpr(List<SpecAnnotation> annotations) {
    final entries = [
      for (final a in annotations)
        if (a.name == 'SecondLevelSectionId')
          'SomSecondLevelId(document_class='
              "${_str('${a.argument('documentClass') ?? ''}')}, "
              "id=${_str('${a.argument('id') ?? ''}')})",
    ];
    return entries.isEmpty ? null : '[${entries.join(', ')}]';
  }

  String? _extrasExpr(List<SpecAnnotation> annotations) {
    final entries = [
      for (final a in annotations)
        if (!_slottedAnnotations.contains(a.name))
          'SomMetaExtra(annotation=${_str(a.name)}, '
              'args=${_lit(a.arguments)})',
    ];
    return entries.isEmpty ? null : '[${entries.join(', ')}]';
  }

  // ── per-root emission ──────────────────────────────────────────────────────

  void _emitRoot(StringBuffer b, SpecRoot root) {
    final cls = model.classNamed(root.type);
    final seg = _rootSegment(root);
    final camel = _camel(root.type);
    final idSymbol = _idName(seg);

    final args = <String>['class_name=${_str(root.type)}'];
    final sectionId = root.sectionId ?? cls?.sectionId;
    if (sectionId != null) args.add('section_id=${_str(sectionId)}');
    if (cls?.sectionId != null) {
      args.add('class_section_id=${_str(cls!.sectionId!)}');
    }
    args
      ..add('kind=SomMetaKind.SECTION')
      ..add('type_name=${_str(root.type)}');
    if (cls?.headline != null) args.add('headline=${_str(cls!.headline!)}');
    final doc = root.doc ?? cls?.doc;
    if (doc != null) args.add('doc_comment=${_str(doc)}');
    if (cls?.doc != null) args.add('class_doc_comment=${_str(cls!.doc!)}');
    if (cls?.mapsTo != null) args.add('maps_to=${_str(cls!.mapsTo!)}');
    if (cls?.detailedIn != null) {
      args.add('detailed_in=${_str(cls!.detailedIn!)}');
    }
    final basedOn = _basedOn(cls);
    args.add('document=SomDocMeta(name=${_str(root.title)}, '
        'description=${_str(root.description ?? '')}'
        '${basedOn.isEmpty ? '' : ', based_on=[${basedOn.map(_str).join(', ')}]'})');
    final secondLevel = _secondLevelIdsExpr(cls?.annotations ?? const []);
    if (secondLevel != null) args.add('second_level_ids=$secondLevel');
    final extra = _extrasExpr(cls?.annotations ?? const []);
    if (extra != null) args.add('extra=$extra');
    args.add(cls == null
        ? 'children=[]'
        : 'children=_mc_${root.type}({${_str(root.type)}})');

    b
      ..writeln('#: The populated metadata tree of the `${root.type}` '
          'document root (DR1 §3.2).')
      ..writeln('${camel}MetaTree = SomMetaTree(SomMetaNode(')
      ..writeln('    ${args.join(',\n    ')},')
      ..writeln('))')
      ..writeln()
      ..writeln('#: Dot-notation access root of `${root.type}` (DR1 §4.1):')
      ..writeln('#: `$camel.<member>….path` / `.meta`.')
      ..writeln('$camel = ${root.type}Nav(${camel}MetaTree, ${_str(seg)})')
      ..writeln()
      ..writeln('#: ID-tree access root of `${root.type}` (DR1 §4.2):')
      ..writeln('#: `$idSymbol.<SECTION-ID>….path` / `.meta`.')
      ..writeln('$idSymbol = ${root.type}Id(${camel}MetaTree, ${_str(seg)})')
      ..writeln();
  }

  List<String> _basedOn(SpecClass? cls) {
    final raw = cls?.annotation('Document')?.argument('basedOn');
    if (raw is List) return raw.map((e) => '$e').toList();
    return const [];
  }

  // ── dot-notation accessor classes (§4.1) ───────────────────────────────────

  void _emitNavClass(StringBuffer b, SpecClass cls) {
    b
      ..writeln('class ${cls.name}Nav(SomMetaRef):')
      ..writeln('    """Dot-notation accessors of ``${cls.name}`` (DR1 §4.1). '
          'Every getter is')
      ..writeln('    one navigable position: ``.path`` is the absolute '
          'document path, ``.meta``')
      ..writeln('    the metadata node. Past a recursive re-entry ``.path`` '
          'chains remain valid')
      ..writeln('    document positions while ``.meta`` raises (the metadata '
          'tree ends there)."""');
    for (final f in _orderedFields(cls)) {
      if (_reservedAccessorNames.contains(f.name)) {
        throw StateError('model field ${cls.name}.${f.name} collides with a '
            'reserved accessor member name');
      }
      final seg = _fieldSegment(f);
      b
        ..writeln()
        ..writeln('    @property')
        ..writeln('    def ${f.name}(self):')
        ..writeln('        return ${_navGetterExpr(f, seg)}');
    }
    b
      ..writeln()
      ..writeln();
  }

  String _navGetterExpr(SpecField f, String seg) {
    final rel = 'f"{self.path}/${_fseg(seg)}"';
    switch (f.kind) {
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = model.classNamed(f.type ?? '');
        if (target != null) {
          return '${target.name}Nav(self.tree, $rel)';
        }
        return 'SomMetaRef(self.tree, $rel)';
      case SpecFieldKind.list:
        final element =
            f.elementIsComplex ? model.classNamed(f.elementType ?? '') : null;
        if (element != null) {
          return 'SomListMetaRef(self.tree, $rel, ${element.name}Nav)';
        }
        return 'SomListMetaRef(self.tree, $rel, SomMetaRef)';
      case SpecFieldKind.form:
      case SpecFieldKind.content:
      case SpecFieldKind.enumValue:
      case SpecFieldKind.scalar:
        return 'SomMetaRef(self.tree, $rel)';
    }
  }

  /// Escapes a path segment for inclusion inside a double-quoted generated
  /// f-string (segments are ids/identifiers — quotes/braces unexpected,
  /// guarded anyway).
  String _fseg(String seg) => seg
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('{', '{{')
      .replaceAll('}', '}}');

  // ── ID-tree accessor classes (§4.2) ────────────────────────────────────────

  /// The classes needing a `<Class>Id` accessor class: the selected roots
  /// plus every class reachable as an ID-node target (through id-bearing
  /// complex/section fields, id-bearing complex-element lists, and hoisting
  /// through id-less complex/section members).
  List<String> _idReachableClasses() {
    final reachable = <String>{};
    final queue = <String>[for (final r in _roots) r.type];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      final cls = model.classNamed(name);
      if (cls == null || !reachable.add(name)) continue;
      for (final child in _idChildren(cls)) {
        if (child.targetClass != null) queue.add(child.targetClass!);
      }
    }
    final sorted = reachable.toList()..sort();
    return sorted;
  }

  void _emitIdClass(StringBuffer b, SpecClass cls) {
    b
      ..writeln('class ${cls.name}Id(SomMetaRef):')
      ..writeln('    """ID-tree accessors of ``${cls.name}`` (DR1 §4.2): '
          'getters named by')
      ..writeln('    section id (``-`` → ``_``), hoisted through id-less '
          'members so every')
      ..writeln('    reachable id is one step. ``.path`` and ``.meta`` agree '
          'with the')
      ..writeln('    dot-notation surface."""');
    for (final child in _idChildren(cls)) {
      if (_reservedAccessorNames.contains(child.name)) {
        throw StateError('section id ${child.name} of ${cls.name} collides '
            'with a reserved accessor member name');
      }
      final rel = 'f"{self.path}/${_fseg(child.relPath)}"';
      final String expr;
      if (child.isList) {
        final elem = child.targetClass;
        expr = elem != null
            ? 'SomListMetaRef(self.tree, $rel, ${elem}Id)'
            : 'SomListMetaRef(self.tree, $rel, SomMetaRef)';
      } else if (child.targetClass != null) {
        expr = '${child.targetClass}Id(self.tree, $rel)';
      } else {
        expr = 'SomMetaRef(self.tree, $rel)';
      }
      b
        ..writeln()
        ..writeln('    @property')
        ..writeln('    def ${child.name}(self):')
        ..writeln('        return $expr');
    }
    b
      ..writeln()
      ..writeln();
  }

  /// The ID-children of [cls]: one entry per id-bearing position reachable
  /// without crossing another id (hoisting through id-less complex/section
  /// members, with a cycle guard). Id-less lists and id-less leaves carry no
  /// id and are skipped (list items are dynamic — no static hoist through
  /// them). Identical to the Dart reference implementation.
  List<_IdChild> _idChildren(SpecClass cls) {
    final children = <_IdChild>[];
    final used = <String>{};

    void walk(SpecClass c, String prefix, Set<String> stack) {
      for (final f in _orderedFields(c)) {
        final isComplexLike = f.kind == SpecFieldKind.complex ||
            f.kind == SpecFieldKind.section;
        if (f.sectionId != null) {
          var name = _idName(f.sectionId!);
          var n = 2;
          while (!used.add(name)) {
            name = '${_idName(f.sectionId!)}_$n';
            n++;
          }
          final rel = '$prefix${f.sectionId!}';
          if (f.kind == SpecFieldKind.list) {
            final elem = f.elementIsComplex
                ? model.classNamed(f.elementType ?? '')?.name
                : null;
            children.add(_IdChild(
                name: name, relPath: rel, targetClass: elem, isList: true));
          } else if (isComplexLike) {
            children.add(_IdChild(
                name: name,
                relPath: rel,
                targetClass: model.classNamed(f.type ?? '')?.name));
          } else {
            children.add(_IdChild(name: name, relPath: rel));
          }
        } else if (isComplexLike) {
          final target = model.classNamed(f.type ?? '');
          if (target != null && !stack.contains(target.name)) {
            stack.add(target.name);
            walk(target, '$prefix${f.name}/', stack);
            stack.remove(target.name);
          }
        }
      }
    }

    walk(cls, '', <String>{cls.name});
    return children;
  }

  /// A section id as a Python identifier: `-` → `_`, digit-leading ids
  /// prefixed with `n` (Python has no `$`; the model currently carries no
  /// digit-leading ids — this is a generation-time safety net).
  String _idName(String id) {
    final name = id.replaceAll('-', '_');
    return RegExp(r'^[0-9]').hasMatch(name) ? 'n$name' : name;
  }
}

/// One ID-tree child position of a class (see `_idChildren`).
class _IdChild {
  final String name;
  final String relPath;
  final String? targetClass;
  final bool isList;

  const _IdChild({
    required this.name,
    required this.relPath,
    this.targetClass,
    this.isList = false,
  });
}
