/// Emits the Dart **whole-model accessor** library, `lib/<package>_model.dart`.
///
/// ## The gap this closes
///
/// `toMarkdown` and `validateDocument` both take a whole [SpecModel], and until
/// this library existed no generated facade exposed one. The model shipped only
/// as the data file `meta/spec_model.meta.json`, so a consumer of the
/// *published* package had to resolve the package's own directory layout by
/// hand:
///
/// ```dart
/// final lib = await Isolate.resolvePackageUri(
///     Uri.parse('package:tom_som_dart_v0/tom_som_dart_v0.dart'));
/// final meta = File.fromUri(lib!.resolve('../meta/spec_model.meta.json'));
/// final model = SpecModel.fromJson(
///     jsonDecode(meta.readAsStringSync()) as Map<String, dynamic>);
/// ```
///
/// ## Why the JSON is embedded rather than read from the shipped file
///
/// Measured, not assumed. A file-reading accessor would have to locate the
/// package, and `Isolate.resolvePackageUri` **returns `null` once no
/// `.dart_tool/package_config.json` is reachable** — which is the normal state
/// of a shipped AOT binary, the very form most consumers ship. The failure is
/// silent: a `null` resolution reads no file and the caller sees an empty or
/// missing model rather than a build error. Flutter is the same story from the
/// other side — package files are not readable at all without being declared as
/// assets, which is why the two Flutter apps in this workspace each bundle their
/// own copy of the model instead.
///
/// So the accessor embeds the payload:
///
/// | form | size |
/// |------|------|
/// | shipped `meta/spec_model.meta.json`, pretty-printed | 10.41 MB |
/// | the same JSON minified — what is embedded here | 6.42 MB |
///
/// A 6.42 MB string literal is cheap enough to be uncontroversial: a cold
/// `dart run` that decodes the whole thing measured **1.44 s**, JIT compilation
/// of the literal included.
///
/// ## Why it is its own library, not part of the facade
///
/// The main facade re-exports the metadata library, so anything added there is
/// compiled by every consumer. This library is **not** exported from the facade
/// — a consumer opts in with a second import — so the payload costs nothing to
/// anyone who does not ask for the model. That is also why the accessor is a
/// lazily-parsed getter rather than a top-level `final`: importing the library
/// must not cost a 6 MB parse until the model is actually read.
///
/// The shipped `meta/spec_model.meta.json` stays exactly as it was. It is the
/// documented interchange artifact and other tools read it; this library adds
/// an API beside it rather than replacing it.
library;

import 'dart:convert';

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Emits `lib/<package>_model.dart` for one generation run.
class SomDartModelEmitter {
  /// The resolved meta-data map — the same one written to
  /// `meta/spec_model.meta.json` in the same run, so the embedded payload and
  /// the shipped file can never disagree. Taking the map rather than the
  /// [SpecModel] is deliberate: re-encoding a parsed model would round-trip
  /// through two conversions that are each allowed to be lossy, and the point
  /// of this library is that it carries the file's bytes.
  final Map<String, dynamic> meta;

  /// The generated package's name, used for the library's own file name and in
  /// the doc comments that tell a reader how to import it.
  final String packageName;

  /// The `v0` / `v1` label of the project, used only in the generated banner.
  final String versionLabel;

  /// [meta] and [packageName] are required; [versionLabel] defaults to the
  /// whole-model `v0` shape the CLI uses.
  SomDartModelEmitter(
    this.meta, {
    required this.packageName,
    this.versionLabel = 'v0',
  });

  /// The minified payload that gets embedded.
  ///
  /// Minified rather than pretty-printed because the two parse to the same
  /// model and the indentation is 4 MB of it. `jsonEncode` without an indent is
  /// exactly the shipped encoder's output minus that whitespace.
  String get payload => jsonEncode(meta);

  /// The Dart source of the model-accessor library.
  String generateLibrary() {
    final b = StringBuffer();
    b.writeln(
      '// GENERATED by tom_specs_clitool SomDartModelEmitter '
      '($versionLabel) — do not edit by hand.',
    );
    b.writeln('//');
    b.writeln('// The whole-model accessor (SOM §10.3). The model is embedded');
    b.writeln('// rather than read from `meta/spec_model.meta.json` because a');
    b.writeln('// package-relative file read cannot survive AOT compilation:');
    b.writeln('// `Isolate.resolvePackageUri` returns null once no');
    b.writeln('// package_config.json is reachable, and reads nothing without');
    b.writeln('// saying so.');
    b.writeln('// ignore_for_file: type=lint, document_ignores');
    b.writeln('library;');
    b.writeln();
    b.writeln("import 'dart:convert';");
    b.writeln();
    b.writeln(
      "import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';",
    );
    b.writeln();
    b.writeln('/// The whole object model this package was generated from.');
    b.writeln('///');
    b.writeln('/// Parsed on first use and cached, so importing this library');
    b.writeln('/// costs nothing until the model is actually read. The parse');
    b.writeln('/// walks a ${_mb(payload.length)} MB payload.');
    b.writeln('///');
    b.writeln('/// ```dart');
    b.writeln("/// import 'package:$packageName/${packageName}_model.dart';");
    b.writeln('///');
    b.writeln('/// final md = toMarkdown(doc, somSpecModel);');
    b.writeln('/// final findings = validateDocument(doc, somSpecModel);');
    b.writeln('/// ```');
    b.writeln('///');
    b.writeln('/// This is the same content as the shipped');
    b.writeln('/// `meta/spec_model.meta.json`; that file remains the');
    b.writeln('/// interchange artifact for tools outside Dart.');
    b.writeln('SpecModel get somSpecModel =>');
    b.writeln('    _somSpecModel ??= SpecModel.fromJson(');
    b.writeln('        jsonDecode(somSpecModelJson) as Map<String, dynamic>);');
    b.writeln();
    b.writeln('SpecModel? _somSpecModel;');
    b.writeln();
    b.writeln('/// The embedded model, as the minified JSON of');
    b.writeln('/// `meta/spec_model.meta.json`.');
    b.writeln('///');
    b.writeln('/// Exposed because a consumer that wants to hand the payload');
    b.writeln('/// to something other than [SpecModel] — a schema tool, a');
    b.writeln(
      '/// different language runtime over a pipe — should not have to',
    );
    b.writeln('/// re-encode a parsed model to get it back.');
    b.writeln('const String somSpecModelJson = ${_literal(payload)};');
    return b.toString();
  }

  static String _mb(int chars) => (chars / 1e6).toStringAsFixed(2);

  /// A single-quoted Dart string literal for [s].
  ///
  /// Escapes the three characters that can end or reopen the literal —
  /// backslash first, or it would double the escapes it just introduced.
  /// `$` matters as much as the quote: JSON content is free to contain one and
  /// an unescaped `$` in a non-raw literal starts an interpolation, which is a
  /// compile error at best and a silent substitution at worst. A raw string
  /// (`r'...'`) would avoid all three, but only until the payload contains a
  /// single quote — this one contains 2,908 of them.
  static String _literal(String s) {
    final e = s
        .replaceAll(r'\', r'\\')
        .replaceAll("'", r"\'")
        .replaceAll(r'$', r'\$');
    return "'$e'";
  }
}
