/// Emits the generated JavaScript typed object model (`tom_som_javascript_v0`)
/// from a resolved [SpecModel].
///
/// The generated classes are an **editing facade** over the generic
/// `tom_som_javascript_runtime` `SpecDocument`: every typed accessor delegates to
/// the path-keyed memory representation, so a typed mutation is visible through
/// the generic path and vice-versa (spec §3). Each document-root class performs
/// the **instantiation-time version check** (`checkSomModelVersion`) against the
/// document's authoring stamp (§2.2) and exposes its own generated model version
/// (§2.1).
///
/// This is the JavaScript counterpart of [SomDartEmitter] / `SomPythonEmitter` /
/// `SomJavaEmitter` — the same reachability walk, the same deterministic
/// ordering, the same field-kind mapping. The emitted surface is a single
/// CommonJS module exporting ES6 classes with `get`/`set` accessors over the
/// shared `tom_som_runtime` facade base classes. The module locates the generic
/// runtime at load time through the `tomSom.runtimePath` recorded in the sibling
/// `package.json` (written by the generator), so the emitted source carries no
/// on-disk path and stays layout-independent / golden-stable.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Generates the `tom_som_javascript_v0` module source for a [SpecModel].
class SomJavaScriptEmitter {
  final SpecModel model;
  final SpecReflection _ref;

  /// The version label of the generated project (`v0`, `v1`, …); names the
  /// `tom_som_<slug>_<label>` output project. It no longer drives the reported
  /// model version — see [modelVersionString].
  final String versionLabel;

  /// The document-root type names to generate. Empty ⇒ every root in the model.
  final List<String> documentRoots;

  SomJavaScriptEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  }) : _ref = SpecReflection(model);

  /// The model version the generated object model reports (§2.1), `major.minor`,
  /// taken from the model's own version stamp (the `tom_specs_model` project
  /// version), not the project [versionLabel] — which only names the `_vN`
  /// output project.
  String get modelVersionString => model.modelVersionString;

  /// The roots to generate, resolved against [documentRoots] (empty ⇒ all).
  List<SpecRoot> get _selectedRoots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// Generated form-class names allocated so far in the current
  /// [generateLibrary] run, used to keep them globally unique. Reset at the
  /// start of every run so output stays deterministic.
  final Set<String> _usedFormNames = {};

  /// Returns a unique form-class name for [base], appending the smallest
  /// numeric suffix (`2`, `3`, …) that is not yet taken when [base] collides.
  String _allocFormName(String base) {
    if (_usedFormNames.add(base)) return base;
    var n = 2;
    while (!_usedFormNames.add('$base$n')) {
      n++;
    }
    return '$base$n';
  }

  /// Builds the complete generated module as a single JavaScript source string.
  String generateLibrary() {
    _usedFormNames.clear();
    final rootTypes = _selectedRoots.map((r) => r.type).toSet();
    final reachable = _reachableClasses(rootTypes);
    final enums = _reachableEnums(reachable);
    final formClasses = <_FormClass>[];

    // The names exported from the module, in emission order (enums, then
    // classes, then form classes), so `module.exports` is deterministic.
    final exported = <String>[];

    final classBlocks = <String>[];
    for (final name in reachable.toList()..sort()) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      classBlocks.add(_emitClass(cls,
          isRoot: rootTypes.contains(name),
          collectForm: (fc) => formClasses.add(fc)));
    }

    final buffer = StringBuffer()
      ..writeln('// GENERATED by tom_specs_clitool SomJavaScriptEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln("'use strict';")
      ..writeln()
      ..writeln('// Typed object-model facade over the generic '
          '`tom_som_runtime` document.')
      ..writeln('//')
      ..writeln('// The generic runtime is located at load time through the '
          '`tomSom.runtimePath`')
      ..writeln('// recorded in this package\'s `package.json` (written by the '
          'generator), so')
      ..writeln('// this module carries no on-disk path of its own.')
      ..writeln("const _path = require('path');")
      ..writeln("const _manifest = require('./package.json');")
      ..writeln('const {')
      ..writeln('  SomList,')
      ..writeln('  SomNode,')
      ..writeln('  SomScalar,')
      ..writeln('  SpecDocument,')
      ..writeln('  checkSomModelVersion,')
      ..writeln('  somEditabilityFor,')
      ..writeln('} = require(_path.resolve(__dirname, '
          '_manifest.tomSom.runtimePath));')
      ..writeln();

    for (final e in enums) {
      buffer
        ..write(_emitEnum(e))
        ..writeln();
      exported.add(e.name);
    }
    for (var i = 0; i < classBlocks.length; i++) {
      buffer
        ..write(classBlocks[i])
        ..writeln();
    }
    for (final name in reachable.toList()..sort()) {
      if (model.classNamed(name) != null) exported.add(name);
    }
    for (final fc in formClasses..sort((a, b) => a.name.compareTo(b.name))) {
      buffer
        ..write(fc.source)
        ..writeln();
      exported.add(fc.name);
    }

    buffer.writeln('module.exports = {');
    for (final name in exported) {
      buffer.writeln('  $name,');
    }
    buffer.writeln('};');
    return buffer.toString();
  }

  // --- reachability -------------------------------------------------------

  Set<String> _reachableClasses(Set<String> rootTypes) {
    final visited = <String>{};
    final queue = <String>[...rootTypes];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      if (!visited.add(name)) continue;
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        switch (f.kind) {
          case SpecFieldKind.complex:
          case SpecFieldKind.section:
            if (f.type != null) queue.add(f.type!);
            break;
          case SpecFieldKind.list:
            if (f.elementIsComplex && f.elementType != null) {
              queue.add(f.elementType!);
            }
            break;
          case SpecFieldKind.form:
          case SpecFieldKind.content:
          case SpecFieldKind.enumValue:
          case SpecFieldKind.scalar:
            break;
        }
      }
    }
    return visited;
  }

  /// The distinct enum types referenced by reachable classes, with their values.
  List<_EnumType> _reachableEnums(Set<String> reachable) {
    final byName = <String, _EnumType>{};
    for (final name in reachable) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        if (f.kind == SpecFieldKind.enumValue && f.enumType != null) {
          byName.putIfAbsent(
              f.enumType!, () => _EnumType(f.enumType!, f.enumValues));
        }
      }
    }
    final result = byName.values.toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    return result;
  }

  // --- emit ---------------------------------------------------------------

  String _emitEnum(_EnumType e) {
    final b = StringBuffer()
      ..writeln('// Generated enum for `${e.name}` values.')
      ..writeln('const ${e.name} = Object.freeze({');
    for (final v in e.values) {
      // Both the key and the value carry the original token (the Dart constant
      // name) verbatim — a JS object key is quoted so any token is valid, and
      // parse/encode round-trips through the stored token, keeping documents
      // cross-language compatible.
      b.writeln('  "${_jstr(v)}": "${_jstr(v)}",');
    }
    b
      ..writeln('});')
      ..writeln()
      ..writeln('// Parses a stored token into a ${e.name} value, or null.')
      ..writeln('function _parse${e.name}(token) {')
      ..writeln('  if (!token) {')
      ..writeln('    return null;')
      ..writeln('  }')
      ..writeln('  for (const value of Object.values(${e.name})) {')
      ..writeln('    if (value === token) {')
      ..writeln('      return value;')
      ..writeln('    }')
      ..writeln('  }')
      ..writeln('  return null;')
      ..writeln('}');
    return b.toString();
  }

  String _emitClass(
    SpecClass cls, {
    required bool isRoot,
    required void Function(_FormClass) collectForm,
  }) {
    final b = StringBuffer();
    _writeDoc(b, cls.doc, '');
    b.writeln('class ${cls.name} extends SomNode {');

    if (isRoot) {
      final root = model.roots.firstWhere((r) => r.type == cls.name);
      final seg = _ref.rootSegment(root);
      b
        ..writeln('  // The model version this object model was generated '
            'against (§2.1).')
        ..writeln('  static MODEL_VERSION = "$modelVersionString";')
        ..writeln()
        ..writeln('  // Creates the typed facade at the document root and '
            'verifies the')
        ..writeln("  // document's authoring documentVersion is editable "
            '(§2.2).')
        ..writeln('  constructor(doc, documentVersion = null) {')
        ..writeln('    super(doc, "${_jstr(seg)}");')
        ..writeln('    checkSomModelVersion(${cls.name}.MODEL_VERSION, '
            'documentVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  // Loads a `*.docspecs.yaml` document and returns the typed '
            'root with the')
        ..writeln("  // document's authoring stamp already applied (§ item 4) — "
            'one call for')
        ..writeln('  // the former decode → loadJson → thread-`documentVersion` '
            'sequence.')
        ..writeln('  static loadYaml(yaml) {')
        ..writeln('    const doc = SpecDocument.fromYaml(yaml);')
        ..writeln('    return new ${cls.name}(doc, doc.modelVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln('  // Loads a `*.docspecs.yaml` document from the file at '
            '`path` — the file')
        ..writeln('  // companion to `loadYaml`.')
        ..writeln('  static loadFile(path) {')
        ..writeln('    const doc = SpecDocument.fromFile(path);')
        ..writeln('    return new ${cls.name}(doc, doc.modelVersion);')
        ..writeln('  }')
        ..writeln()
        ..writeln("  // This object model's own model version (major.minor), "
            'per §2.1.')
        ..writeln('  get objectModelVersion() {')
        ..writeln('    return ${cls.name}.MODEL_VERSION;')
        ..writeln('  }')
        ..writeln()
        ..writeln('  // Classifies whether a document authored under '
            '`documentVersion` is')
        ..writeln('  // editable by this object model, **without throwing** '
            '(§ item 8) — the')
        ..writeln("  // non-throwing companion to the constructor's §2.2 check, "
            'so a read-only')
        ..writeln('  // viewer can branch instead of catching a '
            'SomVersionError.')
        ..writeln('  static editabilityFor(documentVersion) {')
        ..writeln('    return somEditabilityFor(${cls.name}.MODEL_VERSION, '
            'documentVersion);')
        ..writeln('  }');
    } else {
      b
        ..writeln('  constructor(doc, path) {')
        ..writeln('    super(doc, path);')
        ..writeln('  }');
    }

    for (final f in cls.fields) {
      b.writeln();
      _writeField(b, cls, f, collectForm);
    }
    b.writeln('}');
    return b.toString();
  }

  void _writeField(
    StringBuffer b,
    SpecClass cls,
    SpecField f,
    void Function(_FormClass) collectForm,
  ) {
    final seg = _ref.fieldSegment(f);
    final childPath = 'this.path + "/${_jstr(seg)}"';
    // JS-safe accessor identifier (the path segment above is untouched).
    final acc = _acc(f.name);
    switch (f.kind) {
      case SpecFieldKind.content:
      case SpecFieldKind.scalar:
        _emitStringProperty(b, acc, childPath, f.doc);
        break;
      case SpecFieldKind.enumValue:
        if (f.enumType == null) {
          _emitStringProperty(b, acc, childPath, f.doc);
        } else {
          final et = f.enumType!;
          _writeComment(b, f.doc, '  ');
          b
            ..writeln('  get $acc() {')
            ..writeln('    return _parse$et(this.doc.content($childPath));')
            ..writeln('  }')
            ..writeln()
            ..writeln('  set $acc(value) {')
            ..writeln('    this.doc.setContent($childPath, '
                'value != null ? value : "");')
            ..writeln('  }');
        }
        break;
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = f.type;
        _writeComment(b, f.doc, '  ');
        if (target == null) {
          b
            ..writeln('  get $acc() {')
            ..writeln('    return null; // (skipped: no target type)')
            ..writeln('  }');
        } else {
          b
            ..writeln('  get $acc() {')
            ..writeln('    return new $target(this.doc, $childPath);')
            ..writeln('  }');
        }
        break;
      case SpecFieldKind.list:
        _writeComment(b, f.doc, '  ');
        // A pattern-bearing list passes its `@SectionIdPattern` so the facade
        // can auto-generate section ids on `add` (AA1 criteria 3–5); a scalar
        // list omits it (pattern-less, `add` ignores id args).
        final patternArg = f.sectionIdPattern != null
            ? ', "${_jstr(f.sectionIdPattern!)}"'
            : '';
        if (f.elementIsComplex && f.elementType != null) {
          final et = f.elementType!;
          b
            ..writeln('  get $acc() {')
            ..writeln('    return new SomList(this.doc, $childPath, '
                '(d, p) => new $et(d, p)$patternArg);')
            ..writeln('  }');
        } else {
          b
            ..writeln('  get $acc() {')
            ..writeln('    return new SomList(this.doc, $childPath, '
                '(d, p) => new SomScalar(d, p)$patternArg);')
            ..writeln('  }');
        }
        break;
      case SpecFieldKind.form:
        final formName = _allocFormName('${cls.name}${_pascal(f.name)}Form');
        collectForm(_FormClass(formName, _emitFormClass(formName, f)));
        _writeComment(b, f.doc, '  ');
        b
          ..writeln('  get $acc() {')
          ..writeln('    return new $formName(this.doc, $childPath);')
          ..writeln('  }');
        break;
    }
  }

  void _emitStringProperty(
      StringBuffer b, String name, String childPath, String? doc) {
    _writeComment(b, doc, '  ');
    b
      ..writeln('  get $name() {')
      ..writeln("    return this.doc.content($childPath) || '';")
      ..writeln('  }')
      ..writeln()
      ..writeln('  set $name(value) {')
      ..writeln('    this.doc.setContent($childPath, value);')
      ..writeln('  }');
  }

  String _emitFormClass(String name, SpecField f) {
    final b = StringBuffer()
      ..writeln('// Generated form facade for the `${f.name}` @Form section.')
      ..writeln('class $name extends SomNode {')
      ..writeln('  constructor(doc, path) {')
      ..writeln('    super(doc, path);')
      ..writeln('  }');
    for (final ff in f.formFields) {
      final field = '"${_jstr(ff.name)}"';
      // The form-field key string ($field) is preserved; only the JS accessor
      // identifier is keyword-sanitised.
      final acc = _acc(ff.name);
      b
        ..writeln()
        ..writeln('  get $acc() {')
        ..writeln("    return this.doc.formField(this.path, $field) || '';")
        ..writeln('  }')
        ..writeln()
        ..writeln('  set $acc(value) {')
        ..writeln('    this.doc.setFormField(this.path, $field, value);')
        ..writeln('  }');
    }
    b.writeln('}');
    return b.toString();
  }

  /// Emits a doc block as `//` line comments at [indent]. A `*/` cannot
  /// terminate a `//` line comment, so no escaping is needed.
  void _writeDoc(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    for (final line in doc.trimRight().split('\n')) {
      final text = line.trimRight();
      b.writeln(text.isEmpty ? '$indent//' : '$indent// $text');
    }
  }

  /// Emits a field's doc as `//` comment lines above its accessor.
  void _writeComment(StringBuffer b, String? doc, String indent) =>
      _writeDoc(b, doc, indent);

  /// Escapes a value for a double-quoted JavaScript string literal.
  String _jstr(String s) => s
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r')
      .replaceAll('\t', '\\t');

  /// The JavaScript reserved words, plus the object-property names that are
  /// unsafe to use as a class accessor (`constructor` is special-cased by the
  /// language; `prototype` / `__proto__` shadow the prototype chain).
  ///
  /// Dart field and form-field names are otherwise valid JS accessor names
  /// (getters/setters may even be reserved words in object literals), but a
  /// `get constructor()` is a syntax error and the others are footguns, so a
  /// trailing-underscore convention is applied uniformly across the reserved
  /// set — matching the Python/Java facades.
  static const Set<String> _jsKeywords = {
    'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
    'default', 'delete', 'do', 'else', 'export', 'extends', 'finally', 'for',
    'function', 'if', 'import', 'in', 'instanceof', 'new', 'return', 'super',
    'switch', 'this', 'throw', 'try', 'typeof', 'var', 'void', 'while', 'with',
    'yield', 'enum', 'await', 'implements', 'interface', 'let', 'package',
    'private', 'protected', 'public', 'static', 'null', 'true', 'false',
    'constructor', 'prototype', '__proto__',
  };

  /// Returns a JS-safe accessor identifier for [name].
  ///
  /// Only the emitted JS identifier changes — the document path segment and the
  /// stored enum token are derived independently and stay byte-identical to the
  /// other facades, so cross-language documents remain compatible.
  String _acc(String name) => _jsKeywords.contains(name) ? '${name}_' : name;

  String _pascal(String s) {
    final parts = s.split(RegExp(r'[_\s]+')).where((p) => p.isNotEmpty);
    return parts.map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }
}

class _EnumType {
  final String name;
  final List<String> values;
  _EnumType(this.name, this.values);
}

class _FormClass {
  final String name;
  final String source;
  _FormClass(this.name, this.source);
}
