/// Emits the generated Python typed object model (`tom_som_python_v0`) from a
/// resolved [SpecModel].
///
/// The generated classes are an **editing facade** over the generic
/// `tom_som_python_runtime` `SpecDocument`: every typed accessor delegates to
/// the path-keyed memory representation, so a typed mutation is visible through
/// the generic path and vice-versa (spec §3). Each document-root class performs
/// the **instantiation-time version check** (`check_som_model_version`) against
/// the document's authoring stamp (§2.2) and exposes its own generated model
/// version (§2.1).
///
/// This is the Python counterpart of [SomDartEmitter] — the same reachability
/// walk, the same deterministic ordering, the same field-kind mapping — only the
/// emitted surface syntax differs (Python ``@property`` accessors over the
/// shared `tom_som_runtime` facade base classes).
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Generates the `tom_som_python_v0` package module source for a [SpecModel].
class SomPythonEmitter {
  final SpecModel model;
  final SpecReflection _ref;

  /// The version label of the generated project (`v0`, `v1`, …); names the
  /// `tom_som_<slug>_<label>` output project. It no longer drives the reported
  /// model version — see [modelVersionString].
  final String versionLabel;

  /// The document-root type names to generate. Empty ⇒ every root in the model.
  final List<String> documentRoots;

  SomPythonEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  }) : _ref = SpecReflection(model);

  /// The model version the generated object model reports (§2.1), `major.minor`,
  /// taken from the model's own version stamp (the `tom_specs_model` project
  /// version), not the project [versionLabel] — which only names the `_vN`
  /// output project.
  String get modelVersionString => model.modelVersionString;

  /// The roots to generate, resolved against [documentRoots] (empty ⇒ all).
  List<SpecRoot> get _selectedRoots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// Generated form-class names allocated so far in the current
  /// [generateLibrary] run, used to keep them globally unique. Reset at the
  /// start of every run so output stays deterministic.
  final Set<String> _usedFormNames = {};

  /// Returns a unique form-class name for [base], appending the smallest
  /// numeric suffix (`2`, `3`, …) that is not yet taken when [base] collides.
  String _allocFormName(String base) {
    if (_usedFormNames.add(base)) return base;
    var n = 2;
    while (!_usedFormNames.add('$base$n')) {
      n++;
    }
    return '$base$n';
  }

  /// Builds the complete generated module as a single Python source string.
  String generateLibrary() {
    _usedFormNames.clear();
    final rootTypes = _selectedRoots.map((r) => r.type).toSet();
    final reachable = _reachableClasses(rootTypes);
    final enums = _reachableEnums(reachable);
    final formClasses = <_FormClass>[];

    final classBlocks = <String>[];
    for (final name in reachable.toList()..sort()) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      classBlocks.add(_emitClass(cls,
          isRoot: rootTypes.contains(name),
          collectForm: (fc) => formClasses.add(fc)));
    }

    final buffer = StringBuffer()
      ..writeln('# GENERATED by tom_specs_clitool SomPythonEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln('"""Typed object-model facade over the generic '
          '`tom_som_runtime` document."""')
      ..writeln()
      ..writeln('from __future__ import annotations')
      ..writeln();

    if (enums.isNotEmpty) {
      buffer.writeln('from enum import Enum');
    }
    buffer
      ..writeln('from tom_som_runtime import (')
      ..writeln('    SomList,')
      ..writeln('    SomNode,')
      ..writeln('    SomScalar,')
      ..writeln('    SpecDocument,')
      ..writeln('    check_som_model_version,')
      ..writeln('    som_editability_for,')
      ..writeln('    spec_parent_path,')
      ..writeln(')')
      ..writeln()
      // DR8/DR12: the generated metadata module (populated SomMetaTrees + the
      // dot-notation and ID-tree access surfaces) replaces the retired flat
      // path-constant holders. Imported here too — the root `load_yaml` /
      // `load_file` classmethods pass the root's populated tree to the codec.
      // The wildcard import re-exports the meta surface through this module.
      ..writeln('from tom_som_python_${versionLabel}_meta import *  '
          '# noqa: F401,F403')
      ..writeln();

    for (final e in enums) {
      buffer
        ..write(_emitEnum(e))
        ..writeln();
    }
    for (final block in classBlocks) {
      buffer
        ..write(block)
        ..writeln();
    }
    for (final fc in formClasses..sort((a, b) => a.name.compareTo(b.name))) {
      buffer
        ..write(fc.source)
        ..writeln();
    }
    // DR8/DR12: the flat `<Code>Paths` constant holders are retired — the
    // generated metadata module (`tom_som_python_<label>_meta`) supplies the
    // dot-notation and ID-tree access surfaces instead.
    return buffer.toString();
  }

  /// The lowerCamelCase form of a root type name, used to reference the
  /// per-root `SomMetaTree` global `<camelType>MetaTree` (SomPythonMetaEmitter).
  String _camelType(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  // --- reachability -------------------------------------------------------

  Set<String> _reachableClasses(Set<String> rootTypes) {
    final visited = <String>{};
    final queue = <String>[...rootTypes];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      if (!visited.add(name)) continue;
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        switch (f.kind) {
          case SpecFieldKind.complex:
          case SpecFieldKind.section:
            if (f.type != null) queue.add(f.type!);
            break;
          case SpecFieldKind.list:
            if (f.elementIsComplex && f.elementType != null) {
              queue.add(f.elementType!);
            }
            break;
          case SpecFieldKind.form:
          case SpecFieldKind.content:
          case SpecFieldKind.enumValue:
          case SpecFieldKind.scalar:
            break;
        }
      }
    }
    return visited;
  }

  /// The distinct enum types referenced by reachable classes, with their values.
  List<_EnumType> _reachableEnums(Set<String> reachable) {
    final byName = <String, _EnumType>{};
    for (final name in reachable) {
      final cls = model.classNamed(name);
      if (cls == null) continue;
      for (final f in cls.fields) {
        if (f.kind == SpecFieldKind.enumValue && f.enumType != null) {
          byName.putIfAbsent(
              f.enumType!, () => _EnumType(f.enumType!, f.enumValues));
        }
      }
    }
    final result = byName.values.toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    return result;
  }

  // --- emit ---------------------------------------------------------------

  String _emitEnum(_EnumType e) {
    final b = StringBuffer()
      ..writeln('class ${e.name}(Enum):')
      ..writeln('    """Generated enum for `${e.name}` values."""')
      ..writeln();
    for (final v in e.values) {
      // The member *value* carries the original token (the Dart constant name);
      // the member *identifier* may be keyword-sanitised, so parsing/encoding
      // round-trips through `.value`, not `.name` (keeps the stored token
      // identical to the Dart path — see `_acc`).
      b.writeln('    ${_acc(v)} = "${_pystr(v)}"');
    }
    b
      ..writeln()
      ..writeln()
      ..writeln('def _parse_${e.name}(token):')
      ..writeln('    """Parses a stored token into a ${e.name}, or None."""')
      ..writeln('    if not token:')
      ..writeln('        return None')
      ..writeln('    for v in ${e.name}:')
      ..writeln('        if v.value == token:')
      ..writeln('            return v')
      ..writeln('    return None');
    return b.toString();
  }

  String _emitClass(
    SpecClass cls, {
    required bool isRoot,
    required void Function(_FormClass) collectForm,
  }) {
    final b = StringBuffer();
    b.writeln('class ${cls.name}(SomNode):');
    _writeDoc(b, cls.doc, '    ');

    if (isRoot) {
      final root = model.roots.firstWhere((r) => r.type == cls.name);
      final seg = _ref.rootSegment(root);
      b
        ..writeln('    #: The model version this object model was generated '
            'against (§2.1).')
        ..writeln("    model_version = '$modelVersionString'")
        ..writeln()
        ..writeln('    def __init__(self, doc, document_version=None):')
        ..writeln('        super().__init__(doc, "${_pystr(seg)}")')
        ..writeln('        check_som_model_version('
            '${cls.name}.model_version, document_version)')
        ..writeln()
        ..writeln('    @classmethod')
        ..writeln('    def load_yaml(cls, yaml):')
        ..writeln('        """Loads a `*.docspecs.yaml` document and returns the '
            'typed root with the')
        ..writeln("        document's authoring stamp already applied (§ item 4) "
            '— one call for')
        ..writeln('        the former decode → load_json → thread-'
            '`document_version` sequence."""')
        ..writeln('        doc = SpecDocument.from_yaml(yaml, '
            '${_camelType(cls.name)}MetaTree)')
        ..writeln('        return cls(doc, document_version=doc.model_version)')
        ..writeln()
        ..writeln('    @classmethod')
        ..writeln('    def load_file(cls, path):')
        ..writeln('        """Loads a `*.docspecs.yaml` document from the file at '
            '*path* — the file')
        ..writeln('        companion to :meth:`load_yaml`."""')
        ..writeln('        doc = SpecDocument.from_file(path, '
            '${_camelType(cls.name)}MetaTree)')
        ..writeln('        return cls(doc, document_version=doc.model_version)')
        ..writeln()
        ..writeln('    @property')
        ..writeln('    def object_model_version(self):')
        ..writeln("        \"\"\"This object model's own model version "
            "(major.minor), per §2.1.\"\"\"")
        ..writeln('        return ${cls.name}.model_version')
        ..writeln()
        ..writeln('    @classmethod')
        ..writeln('    def editability_for(cls, document_version):')
        ..writeln('        """Classifies whether a document authored under '
            '*document_version* is')
        ..writeln('        editable by this object model, **without raising** '
            '(§ item 8) — the')
        ..writeln("        non-throwing companion to the constructor's §2.2 "
            'check, so a read-only')
        ..writeln('        viewer can branch instead of catching '
            'SomVersionError."""')
        ..writeln('        return som_editability_for('
            'cls.model_version, document_version)');
    } else {
      b
        ..writeln('    def __init__(self, doc, path):')
        ..writeln('        super().__init__(doc, path)');
    }

    // § item 10: a content-bearing section overrides the `SomNode`
    // `can_have_content` structural default (`False`) to `True`, so "can this
    // section hold body text?" is answerable at the type level without probing
    // `.content`.
    if (_hasContentLeaf(cls)) {
      b
        ..writeln()
        ..writeln('    @property')
        ..writeln('    def can_have_content(self):')
        ..writeln('        return True');
    }

    var emittedField = false;
    for (final f in cls.fields) {
      b.writeln();
      _writeField(b, cls, f, collectForm);
      emittedField = true;
    }
    if (!emittedField) {
      // A class with no fields still needs a body; __init__ already provided it.
    }
    return b.toString();
  }

  /// Whether [cls] declares the standard `content` text leaf — the structural
  /// signal that its generated facade carries a `.content` accessor (§ item 10).
  bool _hasContentLeaf(SpecClass cls) => cls.fields
      .any((f) => f.name == 'content' && f.kind == SpecFieldKind.content);

  void _writeField(
    StringBuffer b,
    SpecClass cls,
    SpecField f,
    void Function(_FormClass) collectForm,
  ) {
    final seg = _ref.fieldSegment(f);
    final childPath = 'f"{self.path}/${_fstr(seg)}"';
    // Python-safe accessor identifier (the path segment above is untouched).
    final acc = _acc(f.name);
    switch (f.kind) {
      case SpecFieldKind.content:
      case SpecFieldKind.scalar:
        _emitStringProperty(b, acc, childPath, f.doc);
        break;
      case SpecFieldKind.enumValue:
        if (f.enumType == null) {
          _emitStringProperty(b, acc, childPath, f.doc);
        } else {
          final et = f.enumType!;
          _writeComment(b, f.doc, '    ');
          b
            ..writeln('    @property')
            ..writeln('    def $acc(self):')
            ..writeln('        return _parse_$et(self.doc.content($childPath))')
            ..writeln()
            ..writeln('    @$acc.setter')
            ..writeln('    def $acc(self, value):')
            ..writeln('        self.doc.set_content($childPath, '
                'value.value if value is not None else "")');
        }
        break;
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = f.type;
        _writeComment(b, f.doc, '    ');
        if (target == null) {
          b
            ..writeln('    @property')
            ..writeln('    def $acc(self):')
            ..writeln('        return None  # (skipped: no target type)');
        } else {
          b
            ..writeln('    @property')
            ..writeln('    def $acc(self):')
            ..writeln('        return $target(self.doc, $childPath)');
        }
        break;
      case SpecFieldKind.list:
        _writeComment(b, f.doc, '    ');
        // A pattern-bearing list passes its `@SectionIdPattern` so the facade
        // can auto-generate section ids on `add` (AA1 criteria 3–5); a scalar
        // list omits it (pattern-less, `add` ignores id args).
        final patternArg = f.sectionIdPattern != null
            ? ", pattern=\"${_pystr(f.sectionIdPattern!)}\""
            : '';
        if (f.elementIsComplex && f.elementType != null) {
          final et = f.elementType!;
          b
            ..writeln('    @property')
            ..writeln('    def $acc(self):')
            ..writeln('        return SomList(self.doc, $childPath, '
                'lambda d, p: $et(d, p)$patternArg)');
        } else {
          b
            ..writeln('    @property')
            ..writeln('    def $acc(self):')
            ..writeln('        return SomList(self.doc, $childPath, '
                'lambda d, p: SomScalar(d, p)$patternArg)');
        }
        break;
      case SpecFieldKind.form:
        final formName = _allocFormName('${cls.name}${_pascal(f.name)}Form');
        collectForm(_FormClass(formName, _emitFormClass(formName, f)));
        _writeComment(b, f.doc, '    ');
        b
          ..writeln('    @property')
          ..writeln('    def $acc(self):')
          ..writeln('        return $formName(self.doc, $childPath)');
        break;
    }
  }

  void _emitStringProperty(
      StringBuffer b, String name, String childPath, String? doc) {
    _writeComment(b, doc, '    ');
    b
      ..writeln('    @property')
      ..writeln('    def $name(self):')
      ..writeln('        return self.doc.content($childPath) or ""')
      ..writeln()
      ..writeln('    @$name.setter')
      ..writeln('    def $name(self, value):')
      ..writeln('        self.doc.set_content($childPath, value)');
  }

  /// Emits the typed **section class** for a `@Form` field (YRB2): the section's
  /// own `content` text FIRST, then one correctly-typed member per `@Form`
  /// `Field(name, Type, …)` entry, in declaration order. A member's declared
  /// scalar type (`int`/`double`/`num`/`bool`) becomes its parsed Python return
  /// type; any non-primitive (enums, `List`, …) falls back to `str`. Members
  /// read/write through the generic form store, so the on-disk markdown format
  /// and the conformance golden stay byte-identical.
  String _emitFormClass(String name, SpecField f) {
    final hasContentMember = f.formFields.any((ff) => ff.name == 'content');
    final b = StringBuffer()
      ..writeln('class $name(SomNode):')
      ..writeln('    """Generated section facade for the `${f.name}` @Form '
          'section: its own content text followed by one typed member per form '
          'field."""')
      ..writeln()
      ..writeln('    def __init__(self, doc, path):')
      ..writeln('        super().__init__(doc, path)')
      ..writeln()
      ..writeln('    def can_have_content(self):')
      ..writeln('        return True');
    if (!hasContentMember) {
      b
        ..writeln()
        ..writeln('    @property')
        ..writeln('    def content(self) -> str:')
        ..writeln('        return self.doc.content(self.path) or ""')
        ..writeln()
        ..writeln('    @content.setter')
        ..writeln('    def content(self, value):')
        ..writeln('        self.doc.set_content(self.path, value)');
    }
    // YRD6: role fields bind to the OWNING section — the form's own path when
    // the member heads its own `@SectionId` section, else the parent path (a
    // transparent/class-level form hoisted into the parent's body).
    final ownerExpr =
        f.sectionId != null ? 'self.path' : 'spec_parent_path(self.path)';
    for (final ff in f.formFields) {
      _writeFormMember(b, ff, ownerExpr);
    }
    return b.toString();
  }

  /// Emits a single typed `@Form` member property. The value is stored through
  /// the generic form store, so the on-disk format and the generic reading are
  /// unchanged; only the parsed Python type mirrors the declared form-field
  /// type. A role field (YRD6) is instead a pure view onto the owning
  /// section's headline / stored section id at [ownerExpr] — its value never
  /// touches the form store.
  void _writeFormMember(StringBuffer b, FormFieldSpec ff, String ownerExpr) {
    final field = '"${_pystr(ff.name)}"';
    // The form-field key string ($field) is preserved; only the Python accessor
    // identifier is keyword-sanitised.
    final acc = _acc(ff.name);
    if (ff.role == 'title') {
      b
        ..writeln()
        ..writeln("    # Title-role field (YRD6): a view onto the owning "
            "section's headline.")
        ..writeln('    @property')
        ..writeln('    def $acc(self) -> str:')
        ..writeln('        return self.doc.headline($ownerExpr) or ""')
        ..writeln()
        ..writeln('    @$acc.setter')
        ..writeln('    def $acc(self, value):')
        ..writeln('        self.doc.set_headline($ownerExpr, value)');
      return;
    }
    if (ff.role == 'id') {
      b
        ..writeln()
        ..writeln("    # Id-role field (YRD6): a view onto the owning list "
            "item's stored section id")
        ..writeln('    # (uniqueness validated on write; empty writes are '
            'ignored).')
        ..writeln('    @property')
        ..writeln('    def $acc(self) -> str:')
        ..writeln('        return self.doc.item_section_id($ownerExpr) or ""')
        ..writeln()
        ..writeln('    @$acc.setter')
        ..writeln('    def $acc(self, value):')
        ..writeln('        if not value:')
        ..writeln('            return')
        ..writeln('        self.doc.set_item_section_id($ownerExpr, value)');
      return;
    }
    b..writeln()..writeln('    @property');
    switch (_scalarType(ff.type)) {
      case 'int':
        b
          ..writeln('    def $acc(self) -> "int | None":')
          ..writeln('        v = self.doc.form_field(self.path, $field)')
          ..writeln('        if v is None or v == "":')
          ..writeln('            return None')
          ..writeln('        try:')
          ..writeln('            return int(v)')
          ..writeln('        except (TypeError, ValueError):')
          ..writeln('            return None')
          ..writeln()
          ..writeln('    @$acc.setter')
          ..writeln('    def $acc(self, value):')
          ..writeln('        self.doc.set_form_field(self.path, $field, '
              '"" if value is None else str(value))');
      case 'double':
      case 'num':
        b
          ..writeln('    def $acc(self) -> "float | None":')
          ..writeln('        v = self.doc.form_field(self.path, $field)')
          ..writeln('        if v is None or v == "":')
          ..writeln('            return None')
          ..writeln('        try:')
          ..writeln('            return float(v)')
          ..writeln('        except (TypeError, ValueError):')
          ..writeln('            return None')
          ..writeln()
          ..writeln('    @$acc.setter')
          ..writeln('    def $acc(self, value):')
          ..writeln('        self.doc.set_form_field(self.path, $field, '
              '"" if value is None else str(value))');
      case 'bool':
        b
          ..writeln('    def $acc(self) -> "bool | None":')
          ..writeln('        v = self.doc.form_field(self.path, $field)')
          ..writeln('        return None if v is None else (v == "true")')
          ..writeln()
          ..writeln('    @$acc.setter')
          ..writeln('    def $acc(self, value):')
          ..writeln('        self.doc.set_form_field(self.path, $field, '
              '"" if value is None else ("true" if value else "false"))');
      default:
        b
          ..writeln('    def $acc(self) -> str:')
          ..writeln('        return self.doc.form_field(self.path, $field) or ""')
          ..writeln()
          ..writeln('    @$acc.setter')
          ..writeln('    def $acc(self, value):')
          ..writeln('        self.doc.set_form_field(self.path, $field, value)');
    }
  }

  /// Maps a `@Form` field's declared type name to the primitive scalar kind the
  /// facade should expose, or `'String'` for any non-primitive (enums, `List`,
  /// unresolved types) so the generated code always round-trips as text.
  static String _scalarType(String typeName) {
    final base = typeName.endsWith('?')
        ? typeName.substring(0, typeName.length - 1)
        : typeName;
    switch (base) {
      case 'int':
      case 'double':
      case 'num':
      case 'bool':
        return base;
      default:
        return 'String';
    }
  }

  void _writeDoc(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    final lines = doc.trimRight().split('\n').map((l) => l.trimRight()).toList();
    if (lines.length == 1) {
      b.writeln('$indent"""${_docEscape(lines.first)}"""');
      return;
    }
    b.writeln('$indent"""${_docEscape(lines.first)}');
    for (var i = 1; i < lines.length; i++) {
      b.writeln('$indent${_docEscape(lines[i])}');
    }
    b.writeln('$indent"""');
  }

  /// Emits a field's doc as `#` comment lines — field accessors carry their
  /// description as a comment, not a stray triple-quoted expression statement
  /// (only class/enum/form-class docs are real docstrings, which must be the
  /// first statement of their block).
  void _writeComment(StringBuffer b, String? doc, String indent) {
    if (doc == null || doc.trim().isEmpty) return;
    for (final line in doc.trimRight().split('\n')) {
      final text = line.trimRight();
      b.writeln(text.isEmpty ? '$indent#' : '$indent# $text');
    }
  }

  /// Escapes a docstring line so a stray `"""` or trailing backslash cannot
  /// terminate the triple-quoted string early.
  String _docEscape(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll('"""', r'\"\"\"');

  /// Escapes a value for a plain double-quoted Python string literal.
  String _pystr(String s) =>
      s.replaceAll('\\', '\\\\').replaceAll('"', '\\"');

  /// Escapes a value for embedding inside a double-quoted Python f-string: the
  /// string escapes plus doubled braces so `{`/`}` are treated as literals.
  String _fstr(String s) => _pystr(s).replaceAll('{', '{{').replaceAll('}', '}}');

  /// The Python 3 reserved keywords. Dart field and enum-constant names are
  /// otherwise valid Python identifiers, so these are the only names that need
  /// rewriting before they can appear as a `def`/`@property`/enum member.
  static const Set<String> _pyKeywords = {
    'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break',
    'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally',
    'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
    'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
  };

  /// Returns a Python-safe identifier for [name].
  ///
  /// A Dart identifier that happens to be a Python keyword (`from`, `and`,
  /// `class`, …) cannot be emitted as a `def`/`@property`/enum member, so PEP 8's
  /// trailing-underscore convention is applied (`from` → `from_`). Only the
  /// emitted Python identifier changes — the document path segment and the
  /// stored enum token are derived independently and stay byte-identical to the
  /// Dart facade, so cross-language documents remain compatible.
  String _acc(String name) => _pyKeywords.contains(name) ? '${name}_' : name;

  String _pascal(String s) {
    final parts = s.split(RegExp(r'[_\s]+')).where((p) => p.isNotEmpty);
    return parts.map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }
}

class _EnumType {
  final String name;
  final List<String> values;
  _EnumType(this.name, this.values);
}

class _FormClass {
  final String name;
  final String source;
  _FormClass(this.name, this.source);
}
