/// Emits the generated **metadata module** of the TypeScript `v0` facade
/// (the TypeScript counterpart of `som_javascript_meta_emitter.dart` /
/// `som_python_meta_emitter.dart` / `som_dart_meta_emitter.dart`): the
/// populated `SomMetaTree`s as generated static data structures in code
/// (SOM §7.2) plus the two discoverable access surfaces of SOM §8 — the
/// **dot-notation tree** (member names, SOM §8) and the **ID-tree** (section
/// ids, SOM §8). This module replaces the retired flat path-constant holders
/// (`SbpPaths.…`) in the TypeScript facade.
///
/// The emitted node values mirror `tom_som_typescript_runtime`'s
/// `buildSomMetaTree` (the meta-JSON bridge) **field for field**, sourced from
/// the same [SpecModel], so the generated trees and the bridge-built trees are
/// structurally identical — the facade test suite asserts this exhaustively.
/// Cycle handling matches the bridge: a class already on the descent stack
/// becomes a terminal re-entry node (`recursive: true`), which the generated
/// `_cx` helper reproduces at tree-construction time.
///
/// Surface shapes (mirroring the Dart reference implementation, SOM §10;
/// `$` is a legal TypeScript identifier character, so the Dart names carry
/// over verbatim and are collision-free against the model class names):
///
///   * one `export class <Class>$Nav extends SomMetaRef` accessor class per
///     model class — getters named exactly after the model members;
///   * one `export class <Class>$Id extends SomMetaRef` accessor class per
///     ID-reachable class — getters named by section id (`-` → `_`), hoisting
///     through id-less complex/section members so `SBP.INSC…` skips no ids;
///   * per document root: a module-level `<camelRoot>MetaTree` (SomMetaTree),
///     the dot-notation entry `<camelRoot>` and the ID-tree entry
///     `<ROOT-SEGMENT>`. Like Python/JavaScript, a CommonJS module executes
///     top-down, so the root constants are emitted **after** all accessor
///     classes.
///
/// Like the JavaScript module (and unlike Python), `SomListMetaRef`'s element
/// parameter is a **factory function** `(t, p) => ref`; the TS factories are
/// fully type-annotated so the module compiles under strict `tsc`. Unlike the
/// JavaScript module (which resolves the runtime through a `runtimePath`
/// recorded in `package.json`), this module — like the facade — imports the
/// generic runtime through the **fixed bare specifier**
/// `tom_som_typescript_runtime`, wired by the generator's `package.json`
/// `file:` dependency.
library;

import 'package:tom_som_dart_runtime/tom_som_dart_runtime.dart';

/// Annotation names with a dedicated `SomMetaNode` slot — everything else is
/// captured into `extra`. Must stay identical to the bridge's set.
const Set<String> _slottedAnnotations = {
  'SectionId',
  'SectionIdPattern',
  'SerializationOrder',
  'Min',
  'Unused',
  'ContentType',
  'ContentHelp',
  'Headline',
  'Comment',
  'Form',
  'Document',
  'MapsTo',
  'DetailedIn',
};

/// Getter names a generated accessor class must never emit: the instance
/// members of the runtime's `SomMetaRef` / `SomListMetaRef` (`path`, `meta`,
/// `tree`, `item`) plus `constructor` (a `get constructor()` in a class body
/// is a syntax error; `path` / `tree` are base **properties**, so a getter of
/// the same name is TS2611). Collisions fail generation loudly.
const Set<String> _reservedAccessorNames = {
  'path',
  'meta',
  'tree',
  'item',
  'constructor',
};

/// Emits the TypeScript source of the generated metadata module (see the
/// library doc above) for [model].
class SomTypeScriptMetaEmitter {
  final SpecModel model;
  final String versionLabel;
  final List<String> documentRoots;

  SomTypeScriptMetaEmitter(
    this.model, {
    this.versionLabel = 'v0',
    this.documentRoots = const [],
  });

  List<SpecRoot> get _roots {
    if (documentRoots.isEmpty) return model.roots;
    final wanted = documentRoots.toSet();
    return model.roots.where((r) => wanted.contains(r.type)).toList();
  }

  /// The complete generated metadata module source.
  String generateLibrary() {
    final b = StringBuffer()
      ..writeln('// GENERATED by tom_specs_clitool SomTypeScriptMetaEmitter '
          '($versionLabel) — do not edit by hand.')
      ..writeln('//')
      ..writeln('// The populated SOM metadata trees (SOM §7.2) and the two')
      ..writeln('// generated access surfaces of SOM §8: the dot-notation '
          'tree')
      ..writeln('// (model member names) and the ID-tree (section ids). Both')
      ..writeln('// resolve to the same SomMetaNode and byte-identical path')
      ..writeln('// strings; the flat path-constant holders are retired.')
      ..writeln()
      ..writeln('// Like the facade module, the generic runtime is imported '
          'through a fixed bare')
      ..writeln('// specifier (resolution is wired by the generated '
          '`package.json` `file:`')
      ..writeln('// dependency), so this module carries no on-disk path of '
          'its own.')
      ..writeln('import {')
      ..writeln('  SomContentTypeMeta,')
      ..writeln('  SomDocMeta,')
      ..writeln('  SomFormFieldMeta,')
      ..writeln('  SomFormMeta,')
      ..writeln('  SomListMetaRef,')
      ..writeln('  SomMetaExtra,')
      ..writeln('  SomMetaKind,')
      ..writeln('  SomMetaNode,')
      ..writeln('  SomMetaRef,')
      ..writeln('  SomMetaTree,')
      ..writeln("} from 'tom_som_typescript_runtime';")
      ..writeln();

    _emitCxHelper(b);

    final classNames = model.classes.keys.toList()..sort();
    final idClasses = _idReachableClasses();

    // ── metadata children builders ─────────────────────────────────────────
    b
      ..writeln('// ── metadata tree builders (SOM §7.2) '
          '─────────────────────────────────────')
      ..writeln();
    for (final name in classNames) {
      _emitMetaChildrenBuilder(b, model.classes[name]!);
    }

    // ── dot-notation accessor classes ──────────────────────────────────────
    b
      ..writeln('// ── dot-notation accessor classes (SOM §8) '
          '────────────────────────────────')
      ..writeln();
    for (final name in classNames) {
      _emitNavClass(b, model.classes[name]!);
    }

    // ── ID-tree accessor classes ───────────────────────────────────────────
    b
      ..writeln('// ── ID-tree accessor classes (SOM §8) '
          '─────────────────────────────────────')
      ..writeln();
    for (final name in idClasses) {
      _emitIdClass(b, model.classes[name]!);
    }

    // ── per-root trees + access-surface entry points (module tail: the
    //    module body executes top-down, so these come after the classes) ────
    b
      ..writeln('// ── document-root metadata trees + access surface roots '
          '───────────────────')
      ..writeln();
    for (final root in _roots) {
      _emitRoot(b, root);
    }

    return b.toString();
  }

  // ── shared helpers ─────────────────────────────────────────────────────────

  void _emitCxHelper(StringBuffer b) {
    b
      ..writeln('// Builds a complex/section (or list-element) node with the '
          "bridge's cycle")
      ..writeln('// rule: a class already on the descent `stack` becomes a '
          'terminal re-entry')
      ..writeln('// node (`recursive: true`, no children).')
      ..writeln('function _cx(')
      ..writeln('  cls: string,')
      ..writeln('  stack: Set<string>,')
      ..writeln('  kids: (s: Set<string>) => SomMetaNode[],')
      ..writeln('  make: (r: boolean, c: SomMetaNode[]) => SomMetaNode,')
      ..writeln('): SomMetaNode {')
      ..writeln('  if (stack.has(cls)) {')
      ..writeln('    return make(true, []);')
      ..writeln('  }')
      ..writeln('  stack.add(cls);')
      ..writeln('  const c = kids(stack);')
      ..writeln('  stack.delete(cls);')
      ..writeln('  return make(false, c);')
      ..writeln('}')
      ..writeln();
  }

  /// The fields of [cls] in emission order: `@SerializationOrder` ascending,
  /// declaration index as tiebreaker/fallback — identical to the bridge.
  List<SpecField> _orderedFields(SpecClass cls) {
    final indexed = cls.fields.asMap().entries.toList()
      ..sort((a, b) {
        const fallback = 1 << 30;
        final oa = a.value.serializationOrder ?? fallback;
        final ob = b.value.serializationOrder ?? fallback;
        return oa != ob ? oa.compareTo(ob) : a.key.compareTo(b.key);
      });
    return [for (final e in indexed) e.value];
  }

  String _fieldSegment(SpecField f) => f.sectionId ?? f.name;

  String _rootSegment(SpecRoot root) => root.sectionId ?? root.type;

  String _camel(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  /// The TypeScript `SomMetaKind` member for a [SpecFieldKind].
  String _kindMember(SpecFieldKind kind) {
    switch (kind) {
      case SpecFieldKind.list:
        return 'LIST';
      case SpecFieldKind.form:
        return 'FORM';
      case SpecFieldKind.section:
        return 'SECTION';
      case SpecFieldKind.content:
        return 'CONTENT';
      case SpecFieldKind.enumValue:
        return 'ENUM_VALUE';
      case SpecFieldKind.complex:
        return 'COMPLEX';
      case SpecFieldKind.scalar:
        return 'SCALAR';
    }
  }

  /// A TypeScript double-quoted string literal for [s] (full
  /// control-character escaping — doc comments and descriptions carry
  /// newlines).
  String _str(String s) => '"${s.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n').replaceAll('\r', '\\r').replaceAll('\t', '\\t')}"';

  /// A TypeScript literal for a JSON-shaped annotation-argument [value].
  String _lit(Object? value) {
    if (value == null) return 'null';
    if (value is String) return _str(value);
    if (value is bool) return value ? 'true' : 'false';
    if (value is num) return '$value';
    if (value is List) return '[${value.map(_lit).join(', ')}]';
    if (value is Map) {
      final entries = value.entries
          .map((e) => '${_str('${e.key}')}: ${_lit(e.value)}')
          .join(', ');
      return '{$entries}';
    }
    throw StateError('unsupported annotation argument literal: '
        '${value.runtimeType} ($value)');
  }

  // ── metadata builders ──────────────────────────────────────────────────────

  void _emitMetaChildrenBuilder(StringBuffer b, SpecClass cls) {
    b
      ..writeln('function _mc_${cls.name}(s: Set<string>): SomMetaNode[] {')
      ..writeln('  return [');
    for (final f in _orderedFields(cls)) {
      b.writeln('${_fieldNodeExpr(cls, f, indent: '    ')},');
    }
    b
      ..writeln('  ];')
      ..writeln('}')
      ..writeln();
  }

  /// The expression building the `SomMetaNode` for field [f] of [owner] —
  /// value-for-value the bridge's `_fieldNode`.
  String _fieldNodeExpr(SpecClass owner, SpecField f,
      {required String indent}) {
    final isComplexLike =
        f.kind == SpecFieldKind.complex || f.kind == SpecFieldKind.section;
    final target = isComplexLike ? model.classNamed(f.type ?? '') : null;

    final args = <String>[];
    void add(String name, String? expr) {
      if (expr != null) args.add('$name: $expr');
    }

    add('className', _str(target?.name ?? owner.name));
    add('memberName', _str(f.name));
    if (f.sectionId != null) add('sectionId', _str(f.sectionId!));
    if (target?.sectionId != null) {
      add('classSectionId', _str(target!.sectionId!));
    }
    if (f.sectionIdPattern != null) {
      add('sectionIdPattern', _str(f.sectionIdPattern!));
    }
    add('kind', 'SomMetaKind.${_kindMember(f.kind)}');
    add('typeName', _str(f.type ?? f.elementType ?? f.enumType ?? 'String'));
    if (f.serializationOrder != null) {
      add('serializationOrder', '${f.serializationOrder}');
    }
    if (f.min != null) add('min', '${f.min}');
    if (f.annotation('Unused') != null) add('unused', 'true');
    if (f.contentType != null) {
      final desc =
          '${f.annotation('ContentType')?.argument('description') ?? ''}';
      add(
          'contentType',
          'new SomContentTypeMeta(${_str(f.contentType!)}, '
              '${_str(desc)})');
    }
    if (f.help != null) add('contentHelp', _str(f.help!));
    final headline = f.headline ?? target?.headline;
    if (headline != null) add('headline', _str(headline));
    final comment = '${f.annotation('Comment')?.argument('text') ?? ''}';
    if (comment.isNotEmpty) add('comment', _str(comment));
    final docComment = f.doc ?? target?.doc;
    if (docComment != null) add('docComment', _str(docComment));
    if (target?.doc != null) add('classDocComment', _str(target!.doc!));
    if (f.kind == SpecFieldKind.form) {
      final fields = <String>[];
      for (var i = 0; i < f.formFields.length; i++) {
        final ff = f.formFields[i];
        final ffArgs = <String>[
          'name: ${_str(ff.name)}',
          'typeName: ${_str(ff.type)}',
          'description: ${_str(ff.label)}',
          if (ff.required) 'required: true',
          if (ff.hint != null) 'hint: ${_str(ff.hint!)}',
          'order: $i',
          if (ff.enumValues.isNotEmpty)
            'enumValues: [${ff.enumValues.map(_str).join(', ')}]',
        ];
        fields.add('new SomFormFieldMeta({${ffArgs.join(', ')}})');
      }
      add('form', 'new SomFormMeta([${fields.join(', ')}])');
    }
    if (target?.mapsTo != null) add('mapsTo', _str(target!.mapsTo!));
    if (target?.detailedIn != null) {
      add('detailedIn', _str(target!.detailedIn!));
    }
    final extra = _extrasExpr(f.annotations);
    if (extra != null) add('extra', extra);

    // Element subtree of a complex-element list.
    if (f.kind == SpecFieldKind.list && f.elementIsComplex) {
      final element = model.classNamed(f.elementType ?? '');
      if (element != null) {
        final elemArgs = <String>[
          'className: ${_str(element.name)}',
          if (element.sectionId != null)
            'classSectionId: ${_str(element.sectionId!)}',
          'kind: SomMetaKind.COMPLEX',
          'typeName: ${_str(element.name)}',
          if (element.headline != null)
            'headline: ${_str(element.headline!)}',
          if (element.doc != null) 'docComment: ${_str(element.doc!)}',
          if (element.doc != null) 'classDocComment: ${_str(element.doc!)}',
          if (element.mapsTo != null) 'mapsTo: ${_str(element.mapsTo!)}',
          if (element.detailedIn != null)
            'detailedIn: ${_str(element.detailedIn!)}',
          'recursive: r',
          'children: c',
        ];
        add(
            'elementNode',
            '_cx(${_str(element.name)}, s, _mc_${element.name}, '
                '(r, c) => new SomMetaNode({${elemArgs.join(', ')}}))');
      }
    }

    final body = args.join(',\n$indent  ');
    if (target != null) {
      // Complex/section: children/recursive resolved by the cycle helper.
      return '$indent _cx(${_str(target.name)}, s, _mc_${target.name},\n'
          '$indent  (r, c) => new SomMetaNode({\n$indent    '
          '${args.join(',\n$indent    ')},\n'
          '$indent    recursive: r,\n$indent    children: c}))';
    }
    return '$indent new SomMetaNode({\n$indent  $body})';
  }

  String? _extrasExpr(List<SpecAnnotation> annotations) {
    final entries = [
      for (final a in annotations)
        if (!_slottedAnnotations.contains(a.name))
          'new SomMetaExtra(${_str(a.name)}, ${_lit(a.arguments)})',
    ];
    return entries.isEmpty ? null : '[${entries.join(', ')}]';
  }

  // ── per-root emission ──────────────────────────────────────────────────────

  /// Emits the tree + entry-point constants of [root] (tree, dot-notation
  /// root, ID-tree root), each an `export const`.
  void _emitRoot(StringBuffer b, SpecRoot root) {
    final cls = model.classNamed(root.type);
    final seg = _rootSegment(root);
    final camel = _camel(root.type);
    final idSymbol = _idName(seg);

    final args = <String>['className: ${_str(root.type)}'];
    final sectionId = root.sectionId ?? cls?.sectionId;
    if (sectionId != null) args.add('sectionId: ${_str(sectionId)}');
    if (cls?.sectionId != null) {
      args.add('classSectionId: ${_str(cls!.sectionId!)}');
    }
    args
      ..add('kind: SomMetaKind.SECTION')
      ..add('typeName: ${_str(root.type)}');
    if (cls?.headline != null) {
      args.add('headline: ${_str(cls!.headline!)}');
    }
    final doc = root.doc ?? cls?.doc;
    if (doc != null) args.add('docComment: ${_str(doc)}');
    if (cls?.doc != null) args.add('classDocComment: ${_str(cls!.doc!)}');
    if (cls?.mapsTo != null) args.add('mapsTo: ${_str(cls!.mapsTo!)}');
    if (cls?.detailedIn != null) {
      args.add('detailedIn: ${_str(cls!.detailedIn!)}');
    }
    final basedOn = _basedOn(cls);
    args.add('document: new SomDocMeta({name: ${_str(root.title)}, '
        'description: ${_str(root.description ?? '')}'
        '${basedOn.isEmpty ? '' : ', basedOn: [${basedOn.map(_str).join(', ')}]'}})');
    final extra = _extrasExpr(cls?.annotations ?? const []);
    if (extra != null) args.add('extra: $extra');
    args.add(cls == null
        ? 'children: []'
        : 'children: _mc_${root.type}(new Set([${_str(root.type)}]))');

    b
      ..writeln('// The populated metadata tree of the `${root.type}` '
          'document root (SOM §7.2).')
      ..writeln('export const ${camel}MetaTree: SomMetaTree = '
          'new SomMetaTree(new SomMetaNode({')
      ..writeln('  ${args.join(',\n  ')},')
      ..writeln('}));')
      ..writeln()
      ..writeln('// Dot-notation access root of `${root.type}` (SOM §8):')
      ..writeln('// `$camel.<member>….path` / `.meta`.')
      ..writeln('export const $camel: ${root.type}\$Nav = '
          'new ${root.type}\$Nav(${camel}MetaTree, ${_str(seg)});')
      ..writeln()
      ..writeln('// ID-tree access root of `${root.type}` (SOM §8):')
      ..writeln('// `$idSymbol.<SECTION-ID>….path` / `.meta`.')
      ..writeln('export const $idSymbol: ${root.type}\$Id = '
          'new ${root.type}\$Id(${camel}MetaTree, ${_str(seg)});')
      ..writeln();
  }

  List<String> _basedOn(SpecClass? cls) {
    final raw = cls?.annotation('Document')?.argument('basedOn');
    if (raw is List) return raw.map((e) => '$e').toList();
    return const [];
  }

  // ── dot-notation accessor classes (SOM §8) ─────────────────────────────────

  void _emitNavClass(StringBuffer b, SpecClass cls) {
    b
      ..writeln('// Dot-notation accessors of `${cls.name}` (SOM §8). '
          'Every getter is one')
      ..writeln('// navigable position: `.path` is the absolute document '
          'path, `.meta` the')
      ..writeln('// metadata node. Past a recursive re-entry `.path` chains '
          'remain valid')
      ..writeln('// document positions while `.meta` throws (the metadata '
          'tree ends there).')
      ..writeln('export class ${cls.name}\$Nav extends SomMetaRef {');
    var first = true;
    for (final f in _orderedFields(cls)) {
      if (_reservedAccessorNames.contains(f.name)) {
        throw StateError('model field ${cls.name}.${f.name} collides with a '
            'reserved accessor member name');
      }
      if (!first) b.writeln();
      first = false;
      final seg = _fieldSegment(f);
      final getter = _navGetter(f, seg);
      b
        ..writeln('  get ${f.name}(): ${getter.type} {')
        ..writeln('    return ${getter.expr};')
        ..writeln('  }');
    }
    b
      ..writeln('}')
      ..writeln();
  }

  _TypedExpr _navGetter(SpecField f, String seg) {
    final rel = 'this.tree, this.path + "/${_jseg(seg)}"';
    switch (f.kind) {
      case SpecFieldKind.complex:
      case SpecFieldKind.section:
        final target = model.classNamed(f.type ?? '');
        if (target != null) {
          return _TypedExpr(
              '${target.name}\$Nav', 'new ${target.name}\$Nav($rel)');
        }
        return _TypedExpr('SomMetaRef', 'new SomMetaRef($rel)');
      case SpecFieldKind.list:
        final element =
            f.elementIsComplex ? model.classNamed(f.elementType ?? '') : null;
        if (element != null) {
          return _TypedExpr(
              'SomListMetaRef<${element.name}\$Nav>',
              'new SomListMetaRef($rel, '
                  '(t: SomMetaTree, p: string) => '
                  'new ${element.name}\$Nav(t, p))');
        }
        return _TypedExpr(
            'SomListMetaRef<SomMetaRef>',
            'new SomListMetaRef($rel, '
                '(t: SomMetaTree, p: string) => new SomMetaRef(t, p))');
      case SpecFieldKind.form:
      case SpecFieldKind.content:
      case SpecFieldKind.enumValue:
      case SpecFieldKind.scalar:
        return _TypedExpr('SomMetaRef', 'new SomMetaRef($rel)');
    }
  }

  /// Escapes a path segment for inclusion inside a double-quoted generated
  /// string literal (segments are ids/identifiers — quotes unexpected,
  /// guarded anyway).
  String _jseg(String seg) =>
      seg.replaceAll('\\', '\\\\').replaceAll('"', '\\"');

  // ── ID-tree accessor classes (SOM §8) ──────────────────────────────────────

  /// The classes needing a `<Class>$Id` accessor class: the selected roots
  /// plus every class reachable as an ID-node target (through id-bearing
  /// complex/section fields, id-bearing complex-element lists, and hoisting
  /// through id-less complex/section members).
  List<String> _idReachableClasses() {
    final reachable = <String>{};
    final queue = <String>[for (final r in _roots) r.type];
    while (queue.isNotEmpty) {
      final name = queue.removeLast();
      final cls = model.classNamed(name);
      if (cls == null || !reachable.add(name)) continue;
      for (final child in _idChildren(cls)) {
        if (child.targetClass != null) queue.add(child.targetClass!);
      }
    }
    final sorted = reachable.toList()..sort();
    return sorted;
  }

  void _emitIdClass(StringBuffer b, SpecClass cls) {
    b
      ..writeln('// ID-tree accessors of `${cls.name}` (SOM §8): getters '
          'named by section id')
      ..writeln('// (`-` → `_`), hoisted through id-less members so every '
          'reachable id is one')
      ..writeln('// step. `.path` and `.meta` agree with the dot-notation '
          'surface.')
      ..writeln('export class ${cls.name}\$Id extends SomMetaRef {');
    var first = true;
    for (final child in _idChildren(cls)) {
      if (_reservedAccessorNames.contains(child.name)) {
        throw StateError('section id ${child.name} of ${cls.name} collides '
            'with a reserved accessor member name');
      }
      final rel = 'this.tree, this.path + "/${_jseg(child.relPath)}"';
      final String type;
      final String expr;
      if (child.isList) {
        final elem = child.targetClass;
        if (elem != null) {
          type = 'SomListMetaRef<$elem\$Id>';
          expr = 'new SomListMetaRef($rel, '
              '(t: SomMetaTree, p: string) => new $elem\$Id(t, p))';
        } else {
          type = 'SomListMetaRef<SomMetaRef>';
          expr = 'new SomListMetaRef($rel, '
              '(t: SomMetaTree, p: string) => new SomMetaRef(t, p))';
        }
      } else if (child.targetClass != null) {
        type = '${child.targetClass}\$Id';
        expr = 'new ${child.targetClass}\$Id($rel)';
      } else {
        type = 'SomMetaRef';
        expr = 'new SomMetaRef($rel)';
      }
      if (!first) b.writeln();
      first = false;
      b
        ..writeln('  get ${child.name}(): $type {')
        ..writeln('    return $expr;')
        ..writeln('  }');
    }
    b
      ..writeln('}')
      ..writeln();
  }

  /// The ID-children of [cls]: one entry per id-bearing position reachable
  /// without crossing another id (hoisting through id-less complex/section
  /// members, with a cycle guard). Id-less lists and id-less leaves carry no
  /// id and are skipped (list items are dynamic — no static hoist through
  /// them). Identical to the Dart reference implementation.
  List<_IdChild> _idChildren(SpecClass cls) {
    final children = <_IdChild>[];
    final used = <String>{};

    void walk(SpecClass c, String prefix, Set<String> stack) {
      for (final f in _orderedFields(c)) {
        final isComplexLike = f.kind == SpecFieldKind.complex ||
            f.kind == SpecFieldKind.section;
        if (f.sectionId != null) {
          var name = _idName(f.sectionId!);
          var n = 2;
          while (!used.add(name)) {
            name = '${_idName(f.sectionId!)}_$n';
            n++;
          }
          final rel = '$prefix${f.sectionId!}';
          if (f.kind == SpecFieldKind.list) {
            final elem = f.elementIsComplex
                ? model.classNamed(f.elementType ?? '')?.name
                : null;
            children.add(_IdChild(
                name: name, relPath: rel, targetClass: elem, isList: true));
          } else if (isComplexLike) {
            children.add(_IdChild(
                name: name,
                relPath: rel,
                targetClass: model.classNamed(f.type ?? '')?.name));
          } else {
            children.add(_IdChild(name: name, relPath: rel));
          }
        } else if (isComplexLike) {
          final target = model.classNamed(f.type ?? '');
          if (target != null && !stack.contains(target.name)) {
            stack.add(target.name);
            walk(target, '$prefix${f.name}/', stack);
            stack.remove(target.name);
          }
        }
      }
    }

    walk(cls, '', <String>{cls.name});
    return children;
  }

  /// A section id as a TypeScript identifier: `-` → `_`, digit-leading ids
  /// prefixed with `$` (matching the Dart reference; the model currently
  /// carries no digit-leading ids — this is a generation-time safety net).
  String _idName(String id) {
    final name = id.replaceAll('-', '_');
    return RegExp(r'^[0-9]').hasMatch(name) ? '\$$name' : name;
  }
}

/// A generated getter's TS return type + body expression.
class _TypedExpr {
  final String type;
  final String expr;
  const _TypedExpr(this.type, this.expr);
}

/// One ID-tree child position of a class (see `_idChildren`).
class _IdChild {
  final String name;
  final String relPath;
  final String? targetClass;
  final bool isList;

  const _IdChild({
    required this.name,
    required this.relPath,
    this.targetClass,
    this.isList = false,
  });
}
