import 'model_reader.dart';

/// Emits the `spec_ops.g.dart` registry that adopts the snapshot/serialization
/// contract across every TomSpecs model class **without editing their source**
/// (OE-2).
///
/// ## Why a registry instead of a mixin
///
/// The engine ([SpecNode]/`SpecSnapshotter`/`SpecYaml` in `tom_specs_model`)
/// drives the model through a reflection-free per-class contract: child
/// relationships ([specSlots]), a shallow clone ([cloneShallow]) and a node's
/// own scalar ([yamlScalar]). Hand-written leaves adopt it by mixing in
/// `SpecNode`; the ~3000 generated model classes cannot — Dart 3.11 has no
/// augmentation support, so generated code cannot add a mixin or methods to a
/// hand-written class declaration. Instead, this generator emits one
/// `registerSpecOps()` that registers a `SpecClassOps` per concrete type,
/// closing over each class's **public fields**. The model classes stay pristine
/// (no new fields/getters), so the analyzer-based [ModelReader] that builds
/// `spec_model.json` and feeds the `tom_specs_model_rules.md` §10.2 validator sees them unchanged.
///
/// ## Field classification (matches `ModelJsonExporter` kinds)
///
///  - **Child node slots** — recursed into by the snapshotter and serializer:
///    a single complex/section field → `SpecSlot.node`; a `List<Complex>` →
///    `SpecSlot.list` (narrowed back with `.cast<Element>()`).
///  - **Scalars** — `String`/enum/primitive fields: copied by value in
///    `cloneShallow`; the canonical `content` scalar (or the lone scalar) is
///    returned by `yamlScalar`. Multi-scalar classes serialize only `content`
///    for now — the fuller multi-field YAML packing is not yet supported.
///
/// The two hand-written `SpecNode` leaves (`DocumentHeader`, `SectionMeta`) are
/// skipped: they adopt the contract via the mixin fast-path, which the resolver
/// checks before the registry.
class SpecOpsGenerator {
  final Map<String, ModelClass> classes;

  /// Leaves that already mix in `SpecNode` — excluded from the registry because
  /// the resolver's `is SpecNode` fast-path serves them directly.
  static const _mixinLeaves = {'DocumentHeader', 'SectionMeta'};

  /// Section content leaves defined in `tom_specs_core` (outside the scanned
  /// model package). Each is a `String? content` leaf; registered by hand here
  /// so trees that embed them snapshot/serialize without a missing-ops error.
  static const _sectionLeafTypes = [
    'TextSection',
    'DiagramSection',
    'ErDiagramSection',
    'FlowDiagramSection',
    'GanttDiagramSection',
    'SequenceDiagramSection',
    'CodeSection',
    'DartCodeSection',
    'SqlCodeSection',
    'DdlCodeSection',
  ];

  SpecOpsGenerator(this.classes);

  String generate() {
    final buffer = StringBuffer();
    _writeHeader(buffer);

    final names = classes.keys.where((n) => !_mixinLeaves.contains(n)).toList()
      ..sort();

    buffer.writeln('  // --- Section content leaves (tom_specs_core) ---');
    // YRD5: the universal section base type itself is a content leaf — model
    // members typed `DocSpecsSection?` / `List<DocSpecsSection>` hold plain
    // instances of it unless a subclass was assigned.
    _writeContentLeaf(buffer, 'DocSpecsSection');
    for (final type in _sectionLeafTypes) {
      _writeContentLeaf(buffer, type);
    }
    buffer.writeln();
    buffer.writeln('  // --- Model classes (tom_specs_model) ---');
    for (final name in names) {
      _writeClassOps(buffer, classes[name]!);
    }

    buffer.writeln('}');
    return buffer.toString();
  }

  void _writeHeader(StringBuffer b) {
    b.writeln('// GENERATED by tom_specs_clitool/bin/spec_ops.dart — '
        'do not edit by hand.');
    b.writeln('//');
    b.writeln('// Registers the snapshot/serialization contract '
        '(SpecClassOps) for every');
    b.writeln('// TomSpecs model class + section leaf, so the reflection-free '
        'engine can');
    b.writeln('// snapshot, clone and serialize the model without dart:mirrors '
        '(OE-2).');
    b.writeln('//');
    b.writeln('// ignore_for_file: type=lint, '
        'unnecessary_cast, prefer_const_constructors');
    b.writeln();
    b.writeln("import 'package:tom_specs_core/tom_specs_core.dart';");
    b.writeln("import 'package:tom_specs_model/tom_specs_model.dart';");
    b.writeln();
    b.writeln('bool _registered = false;');
    b.writeln();
    b.writeln('/// Registers [SpecClassOps] for every model class and section '
        'leaf.');
    b.writeln('/// Idempotent — safe to call more than once.');
    b.writeln('void registerSpecOps() {');
    b.writeln('  if (_registered) return;');
    b.writeln('  _registered = true;');
    b.writeln();
  }

  void _writeContentLeaf(StringBuffer b, String type) {
    // YRD5: section leaves extend DocSpecsSection, so the shallow clone copies
    // the full stored state — headline, id, content, the parsed form and the
    // csmb1 codeSpec forward link.
    b.writeln('  SpecRegistry.register($type, SpecClassOps(');
    b.writeln('    slots: (o) => const [],');
    b.writeln('    cloneShallow: (o) {');
    b.writeln('      final n = o as $type;');
    b.writeln('      return $type()');
    b.writeln('        ..headline = n.headline');
    b.writeln('        ..id = n.id');
    b.writeln('        ..content = n.content');
    b.writeln('        ..codeSpec = n.codeSpec');
    b.writeln('        ..form = n.form;');
    b.writeln('    },');
    b.writeln('    yamlScalar: (o) => (o as $type).content,');
    b.writeln('  ));');
  }

  void _writeClassOps(StringBuffer b, ModelClass cls) {
    final name = cls.name;
    final childNodes = cls.fields.where(_isChildNode).toList();
    final scalar = _yamlScalarField(cls);

    b.writeln('  SpecRegistry.register($name, SpecClassOps(');

    // slots
    if (childNodes.isEmpty) {
      b.writeln('    slots: (o) => const [],');
    } else {
      b.writeln('    slots: (o) {');
      b.writeln('      final n = o as $name;');
      b.writeln('      return [');
      for (final f in childNodes) {
        b.writeln('        ${_slotExpr(f)}');
      }
      b.writeln('      ];');
      b.writeln('    },');
    }

    // cloneShallow — copy every field (scalars by value, child refs shared).
    if (cls.fields.isEmpty) {
      b.writeln('    cloneShallow: (o) => $name(),');
    } else {
      b.writeln('    cloneShallow: (o) {');
      b.writeln('      final n = o as $name;');
      b.writeln('      return $name()');
      for (var i = 0; i < cls.fields.length; i++) {
        final f = cls.fields[i];
        final tail = i == cls.fields.length - 1 ? ';' : '';
        b.writeln('        ..${f.name} = n.${f.name}$tail');
      }
      b.writeln('    },');
    }

    // yamlScalar
    if (scalar != null) {
      b.writeln('    yamlScalar: (o) => (o as $name).$scalar,');
    }

    b.writeln('  ));');
  }

  String _slotExpr(ModelField f) {
    if (f.isList && (f.listElementIsComplex || f.listElementIsContentSection)) {
      final elem = f.listElementTypeName;
      return 'SpecSlot.list(() => n.${f.name}, '
          "(v) => n.${f.name} = v.cast<$elem>(), label: '${f.name}'),";
    }
    final base = f.typeName.replaceAll('?', '');
    final cast = f.isNullable ? '$base?' : base;
    return 'SpecSlot.node(() => n.${f.name}, '
        "(v) => n.${f.name} = v as $cast, label: '${f.name}'),";
  }

  bool _isChildNode(ModelField f) {
    // YRD5: `DocSpecsSection` members are child nodes of the object tree (the
    // engine recurses into them), even though the *meta* tree renders them as
    // content leaves.
    if (f.isList) return f.listElementIsComplex || f.listElementIsContentSection;
    return f.isSectionType || f.isComplex || f.isContentSection;
  }

  /// The String field used for [yamlScalar]: the canonical `content`, or the
  /// lone String scalar when the class has exactly one. Multi-scalar classes
  /// without a `content` field return `null` (deferred fuller packing).
  String? _yamlScalarField(ModelClass cls) {
    final strings =
        cls.fields.where((f) => f.isString && !_isChildNode(f)).toList();
    if (strings.isEmpty) return null;
    final content = strings.where((f) => f.name == 'content').toList();
    if (content.isNotEmpty) return 'content';
    if (strings.length == 1) return strings.single.name;
    return null;
  }
}
